### ISSUE TITLE
Testing section references nonexistent reusage instructions in Usage section

### ISSUE THREAD

**Issue by elazar** [silexphp/Silex#1003]
See [these lines](https://github.com/silexphp/Silex/blame/0328d904085c4defa60bdc7e21e515841d59d356/doc/testing.rst#L76-77). The "Reusing applications" instructions referenced as being in the Usage section don't appear to exist.

**Comment by fabpot** [comment]
fixed in 4cb970b8d1102f1db4b711d8875018ebeea2169b
