### ISSUE TITLE
Silex error handler and Symfony\Component\Debug\ErrorHandler misleading param description

### ISSUE THREAD

**Issue by 1emming** [silexphp/Silex#1012]
Hi all,
In one of my productions env. I run multiple front-end servers and use the php ssl2 lib. to move stuff around. I saw some errors didn't end up in my (central database) error log and start looking what was going on.
My Silex code (when stripped from all not relevant stuff) is something like this:

```php
<?php
use Symfony\Component\Debug\ErrorHandler;
use Symfony\Component\Debug\ExceptionHandler;

require_once __DIR__.'/../vendor/autoload.php';

$app = new Silex\Application();
//$app['debug'] = true;

ErrorHandler::register(null, $app['debug']);

$app->error(function (\Exception $e, $code) {
	echo 'Write exception to database: ' . $e->getMessage();
	// serve some error page to the user
});

$app->get('/image/{id}', function () use ($app) {

	// if not on this server, fetch image from other server
	$connection = ssh2_connect('x.x.x.x');
	ssh2_auth_password($connection, 'lemming', 'xxxxxx');
	ssh2_exec($connection, '/usr/local/bin/php -i'); // some scp command
	return 'Image page';
});

$app->run();
```

In short, the Silex ```error``` function is not called for an  (fatal) error if the ```Errorhandler ``` is registered without the ```$displayErrors``` argument set to ```true```. However the description states:
```Display errors (for dev environment) or just log them (production usage)```.
I would like to log the errors, should I change to some other hook then ```$app->error()``` to log the error using a custom logger?

**Comment by fabpot** [comment]
Fatal errors can be handled by the `ExceptionHandler` class -- see http://silex.sensiolabs.org/doc/cookbook/error_handler.html

**Comment by SpacePossum** [comment]
:+1:   thanks, sorry for keeping this open so long ..

**Comment by 1emming** [comment]
thanks! sorry for keeping this one open for so long, it kind of slipped my mind
