### ISSUE TITLE
request is NULL in route conditions

### ISSUE THREAD

**Issue by hinzundcode** [silexphp/Silex#1013]
I wan't to use route conditions in Silex, but request is NULL, only context is provided.

**Comment by anasofiapaixao** [comment]
I still have this issue, with silex 1.3.5 and symfony/expression-language 3.0.4. This example triggers it:

```php
$app->get('/', function() { return "test"; })
    ->getRoute()->setCondition('request.getPort() === 1234');
```

**Comment by GromNaN** [comment]
@anasofiapaixao You should create a new issue with a runnable code sample that demonstrates the issue.

**Comment by anasofiapaixao** [comment]
Looks like @SpacePossum 's test case in https://github.com/silexphp/Silex/pull/1334 already shows the issue.
