### ISSUE TITLE
Silex doesn't catch fatal errors by the error handler.

### ISSUE THREAD

**Issue by AlexeyKupershtokh** [silexphp/Silex#1016]
Hello.
I'm trying to use Symfony\Component\Debug\ErrorHandler in order to handle fatal errors (converted to fatal exceptions) with Silex error callback.

I've written a minimal script reproducing the situation:
```php
<?php
 
require_once __DIR__ . '/vendor/autoload.php';
 
use Symfony\Component\Debug\ErrorHandler;
 
$app = new Silex\Application();
 
// emulate E_NOTICE
//$app->get('/', function () use ($app) { $a + 1; });
 
// emulate fatal error
$app->get('/', function () use ($app) { asd(); });
 
$app->error(
    function ($e) use ($app) {
        // notices go here with $e of type
        // $e is instance of \Symfony\Component\Debug\Exception\ContextErrorException
        var_dump('silex error handler', get_class($e));
    }
);
 
ErrorHandler::register();
set_exception_handler(function($e) {
    // fatals come here instead of $app->error callback :(
    // $e is instance of \Symfony\Component\Debug\Exception\UndefinedFunctionException
    var_dump('exception handler', get_class($e));
});
 
$app->run();
```

With non-fatal errors-exceptions everything is perfect (uncomment the ```//$app->get('/', function () use ($app) { $a + 1; });``` to test). But fatal errors-exceptions are not bubbled to the error callback but are caught by the set_exception_handler one instead.

What I'm trying to achieve (in larger project) is to have an HTTP API that can return json even on fatal errors. Error handler is the best place to do so and it works well for many cases. I would like to avoid doing something like:
```php
set_exception_handler(function($e) { print json_encode($e->getMessage()); exit(); });
```
Is it possible to rely on Silex in this case?

**Comment by chrisvoo** [comment]
At the moment I choose to use an error handler registered in index.php and implemented inside my Application:
```php
register_shutdown_function(array($app, 'fatal_handler'));
```

**Comment by mivanov93** [comment]
I don't think one should try catching fatal errors with Silex as they may appear before Silex has loaded. Hence use => set_error_handler and register_shutdown_function. And after that do a 
\Symfony\Component\Debug\ErrorHandler::register();
\Symfony\Component\Debug\ExceptionHandler::register($DEBUG);

**Comment by juanrmn** [comment]
I've solved this by using a little hack, although I'm not sure it is an elegant solution:

```php
class CustomExceptionHandler extends ExceptionHandler{
	public function handle($exception){
		//Let's print the exception, for example:
		echo nl2br(print_r($exception, true));
	}
}

//... and then
//Setup error handling on the Silex application
ErrorHandler::register();
CustomExceptionHandler::register($debug);
```

Then all exceptions and even fatal errors go through the `handle` method.

**Comment by fabpot** [comment]
Closing as Silex/Symfony provide the `ExceptionHandler` class that manages such errors. If you need more, it's up to you and outside the scope of Silex itself.

**Comment by Duvo** [comment]
I encounter this case today, and find a way to bind fatal error with Silex.

First, you need to bind an exception handler with Silex :
```
$app->error(function (\Exception $exception, $code) {
    // Something that build a nice \Symfony\Component\HttpFoundation\Response. This part is up to you.
    $response = MyExceptionFormatter::format($exception, $code);

    // A Silex exception handler must return a Response.
    return $response;
});
```
Now, we use the [Symfony Debug Component](http://symfony.com/doc/current/components/debug/introduction.html) to [convert our errors](http://silex.sensiolabs.org/doc/cookbook/error_handler.html).
```
// Convert simple errors into nice Exception, automaticaly handled by Silex.
Symfony\Component\Debug\ErrorHandler::register();

// Now, the hard part, handle fatal error.
$handler = Symfony\Component\Debug\ExceptionHandler::register($app['debug']);
$handler->setHandler(function ($exception) use ($app) {
    
    // Create an ExceptionEvent with all the informations needed.
    $event = new Symfony\Component\HttpKernel\Event\GetResponseForExceptionEvent(
        $app,
        $app['request'],
        Symfony\Component\HttpKernel\HttpKernelInterface::MASTER_REQUEST,
        $exception
    );

    // Hey Silex ! We have something for you, can you handle it with your exception handler ?
    $app['dispatcher']->dispatch(Symfony\Component\HttpKernel\KernelEvents::EXCEPTION, $event);
    
    // And now, just display the response ;)
    $response = $event->getResponse();
    $response->sendHeaders();
    $response->sendContent();
    //$response->send(); We can't do that, something happened with the buffer, and Symfony still return its HTML.
});
```

**Comment by tiemevanveen** [comment]
@Duvo I'm not sure what would be a better approach. But I think you shouldn't use `$app['request']`. See https://github.com/silexphp/Silex/issues/1257#issuecomment-141058724

**Comment by Duvo** [comment]
In your linked comment, it's suggested to use the request provide in the `GetResponseForExceptionEvent`, but in my case I want to create this `GetResponseForExceptionEvent`.

**Comment by tiemevanveen** [comment]
Correct. But they also say: 
> $app['request'] should NEVER be used and is deprecated.

**Comment by Duvo** [comment]
As you can see, the solution above is old.

Rather than sending all the exception to the little Silex handler by dispatching an error with the KernelEvent, I prefer to use the Symfony handler.

Here is my last way of doing it :

```
// Disable the default Silex exception handler, so... all our exceptions can go to the same handler.
// It's deprecated but I dont find the new way of doing it (I did not search that far)
$app['exception_handler']->disable();

// Convert simple errors into nice Exception, automaticaly handled by Silex.
$errorHandler = \Symfony\Component\Debug\ErrorHandler::register();

// Define the level when the error should throw.
$errorLevel = E_ALL & ~E_NOTICE & ~E_USER_NOTICE & ~E_STRICT & ~E_DEPRECATED & ~E_USER_DEPRECATED;
$errorHandler->throwAt($errorLevel, true);

// In case of exception...
$errorHandler->setExceptionHandler(function (\Exception $exception) use ($app) {
    // ...build some fancy Response with a nice HTTP error code and send it.
    $response = new JsonResponse(['message'=>$exception->getMessage()], 500);
    $response->send();
});
```

If there is a new way to disable the default handler with Silex 2, I would be happy to know :wink:
