### ISSUE TITLE
HEAD http method?

### ISSUE THREAD

**Issue by davidwinter** [silexphp/Silex#103]
I've noticed in my log files that some requests are using the HEAD method on my app. This throws up an Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException, and I don't know of a way to handle this.

Is there a workaround? Or is this something that would need to be looked at?

**Comment by ashishtilara** [comment]
I am trying to do following...
can some one tell me what I am doing wrong because it is only matching first one.
```
$app->match("/user/{name}", function ($name, Request $req) use ($app) {
    return $app->json(array("get" => $name), 200);
})->method("GET");
$app->match("/user/{name}", function ($name, Request $req) use ($app) {
    return $app->json(array("head" => $name), 200);
})->method("HEAD");
```

**Comment by daltones** [comment]
@ashishtilara I had almost the same problem with GET or HEAD methos and I found this in ```Symfony\Component\Routing\Matcher\UrlMatcher``` (Symfony 2.7.7):

```php
// check HTTP method requirement
if ($requiredMethods = $route->getMethods()) {
    // HEAD and GET are equivalent as per RFC
    if ('HEAD' === $method = $this->context->getMethod()) {
        $method = 'GET';
    }

    if (!in_array($method, $requiredMethods)) {
        $this->allow = array_merge($this->allow, $requiredMethods);

        continue;
    }
}
```

I don't know which RFC is that, but it seems very weird.

**Comment by henrikbjorn** [comment]
@daltones @ashishtilara GET and HEAD is the same thing, expect HEAD requests MUST NOT return a body. That is why it is aliased.
