### ISSUE TITLE
security.context: 'The "context" authentication entry is not registered.

### ISSUE THREAD

**Issue by silvios** [silexphp/Silex#1045]
I have  '"silex/silex": "~1.2",' defined in my composer file. I need to be able to use the context for naming firewall rules it.

I keep getting:
LogicException' with message 'The "context" authentication entry is not registered.' 

I see that it exists in the master branch but not in the 1.2 branch, is it possible to have it merged over?

https://github.com/silexphp/Silex/pull/964/files

Or is it already and I am doing something wrong?

I have manually added the change, but shouldn't this change be merged into the main 1.2 branch? I cant see how its possible for it to break anything. If i am not looking at this correctly please let me know.

**Comment by mivanov93** [comment]
It's not in the 1.3 either, but it's a perfectly fine change. Should be merged in 1.3.

**Comment by fabpot** [comment]
I've cherry-picked the changes from master into 1.3.

**Comment by fabpot** [comment]
see fcefc535c0f29c724be9133c54816e3d0d712012
