### ISSUE TITLE
Strange 404 exception with GET User-Agent instead of path

### ISSUE THREAD

**Issue by kai11** [silexphp/Silex#1051]
On my live site I receive a LOT of Symfony\Component\HttpKernel\Exception\NotFoundHttpException
with message No route found for "GET User-Agent:"

Any ideas what it is? How to debug it?

PS. I added http headers logging with http://devel-m6w6.rhcloud.com/mdref/http/Env/getRequestHeader - no results so far.

**Comment by naxhh** [comment]
Do you have this GET in the access logs?

**Comment by kai11** [comment]
I don't see it in Apache logs (as an error). Did not checked access logs - hard to figure out which url.

However, it appears in my 404 handler ( $app->error(function... ) ) and:
Exception class is Symfony\Component\HttpKernel\Exception\NotFoundHttpException 
Message is 'No route found for "GET User-Agent:"'

Around 5 events daily.

**Comment by kai11** [comment]
More details about request environment

URL:	http://www.__site__.comUser-Agent:
Method:	GET

Headers:	
Accept	*/*
Connection	Keep-Alive
Host  	www.__site__.com

Environment (partial):
GATEWAY_INTERFACE	CGI/1.1
PATH	/usr/local/bin:/usr/bin:/bin
PHP_SELF	/index.php
QUERY_STRING	
REQUEST_METHOD	GET
REQUEST_URI	User-Agent:
SCRIPT_FILENAME	/www/www/site/index.php
SCRIPT_NAME	/index.php
SCRIPT_URI	http://www.__site__.com/
SCRIPT_URL	/

**Comment by naxhh** [comment]
Well there you have your explanation.

Someone is doing a call to that url and the exception is that you don't have a controller matching that URI.

Is not really a Silex problem but an App problem.
Maybe you have some code generating that url or someone is accesing that url for some reason.

I think this issue can be closed.
