### ISSUE TITLE
[2.0] Lower Pimple dependency to 2.1 or 2.0 in composer.json

### ISSUE THREAD

**Issue by astax-t** [silexphp/Silex#1076]
Silex 2.0 is fully compatible with Pimple 2.1, so there is no need to require 3.0. Wouldn't it be better to require Pimple 2.1 or 3.0 instead of 3.0 only?

Some packages still depend on Pimple 2.x and it's difficult to install them with Silex 2.0 due to this.

**Comment by henrikbjorn** [comment]
You cannot make this happen before 2.0

**Comment by dominikzogg** [comment]
Hello @astax-t 

2.0 => no service provider interface
2.1 => broken C implementation cause renaming class and using class alias
3.0 => same as 2.1, but without class aliasing => working c extension

I am sure @henrikbjorn dlike to explain you better why he "hates" 2.1 ;-)

**Comment by fabpot** [comment]
Closing for the reasons explained by @dominikzogg an others.
