### ISSUE TITLE
[1.2] Broken phpunit tests

### ISSUE THREAD

**Issue by Stelian** [silexphp/Silex#1085]
Hello, there are currently 6 failed and 14 warning when running the tests for the 1.2 branch. Most of them are caused by the deprecation messages and mainly the Form / Security changes.

Question is, would a PR replacing the deprecated classes with the new ones be suited or should another approach to this be taken?

**Comment by davedevelopment** [comment]
@Stelian it really depends, I'm not up to date with the changes that are being made upstream. Given silex 2.0 is on the horizon, it might be time to lock down the deps on 1.2, which might mean some of these problems go away.

**Comment by fabpot** [comment]
We are still working on the Symfony side to see how to limit those problems. When it's stabilized, we will be able to update Twig to take those issues into account and limit them.

**Comment by Stelian** [comment]
@davedevelopment locking down deps seems the sensitive approach right now in my opinion, especially with silex 2.0 being in the works.

@fabpot Would locking down the deps for 1.2 be something acceptable for the time being? That would fix all existing issues in phpunit without affecting any of the existing code base.

**Comment by stof** [comment]
@Stelian just use stable dependencies for Symfony components (either through ``minimum-stability: stable`` which is the default in Composer, or using ``prefer-stable: true`` if you change the min stability).

**Comment by Stelian** [comment]
@stof  I was just referring to the default composer.json from the 1.2 branch, not an actual production issue especially since most of the output from phpunit is deprecation warnings.

**Comment by stof** [comment]
I suggest changing the 1.2 branch to make it use stable versions of the dependencies when running tests to avoid that. What do you think @fabpot ?
