### ISSUE TITLE
How to use the config component with Silex

### ISSUE THREAD

**Issue by Whyounes** [silexphp/Silex#1099]
What's the best way to wire the symfony config component with the silex application?

**Comment by henrikbjorn** [comment]
My attempt at doing it is http://github.com/flint/tacker

**Comment by Whyounes** [comment]
```
// src/MyApp/AppKernel.php

class AppKernel extends Kernel{
   //...
    public function registerContainerConfiguration(LoaderInterface $loader)
    {
        $loader->load($this->rootDir.'/app/config/app_'.$this->getEnvironment().'.php');
    }
}


// public/index.php

$app = new Silex\Application();

$kernel = new AppKernel("dev", false);

$app->run(); 
```

How can i attach the Kernel to the Silex application to make it load my specific configuration!

**Comment by henrikbjorn** [comment]
You cannot, the AppKernel uses the DependencyInjection component, so it is not possible to just add all those services to pimple. If you just want the AppKernel to be accessible then you could just add it like so:

``` php
<?php

$kernel = new AppKernel('dev', false);

$app = new Silex\Application['app_kernel' => $kernel]);
$app->run();

**Comment by Whyounes** [comment]
Do you know where the `registerContainerConfiguration` is called?

**Comment by henrikbjorn** [comment]
I assume it is called in the boot method or something, isnt that hard to look up with a search on github or in the class.

This is not really a support forum.
