### ISSUE TITLE
Dot in route

### ISSUE THREAD

**Issue by elfet** [silexphp/Silex#1103]
--Why i can't to serve this url?-- Sorry)
```php
$app->get('/manifest.json', ...);
```

**Comment by doalex** [comment]
had the same problem with `php -S`, can be fixed if you specify the php script:

    php -S localhost:8080 index.php

**Comment by GromNaN** [comment]
The PHP internal server usage is documented here: http://silex.sensiolabs.org/doc/web_servers.html#php-5-4
