### ISSUE TITLE
$app['session.storage.options'] ignored

### ISSUE THREAD

**Issue by domnuprofesor** [silexphp/Silex#1105]
for the SessionServiceProvider the docs say that ```session.storage.options``` should be sent as parameters like this:
$app->register(new Silex\Provider\SessionServiceProvider(), $params);
but this does not work.

The code expects the $params to be injected prior in the $app.
Even if this is done, line 68:

```$app['session.storage.options'] = array();```
messes things up. It should be deleted.

**Comment by indeyets** [comment]
you misunderstand how it works.

line 68 is default value and it is executed BEFORE your options are applied. your options would be applied lazily (pimple is about lazy initialization of services), not earlier than `boot()` is called so they will override whatever is set in body of `register()` method

**Comment by domnuprofesor** [comment]
exactly. it is executed BEFORE, so that is clears out the values that are set externally in $app.

so this is how it goes (as I understand it).

1. user code fills in ```$app['session.storage.options']``` with desired values
2. SessionServiceProvider::register() executes
3. SessionServiceProvider clears the values of ```session.storage.options```
4. lazily, the session native storages inits and finds no custom data in ```session.storage.options```

**Comment by indeyets** [comment]
proper way to do:

`$app->register(new Silex\Provider\SessionServiceProvider(), ['session.storage.options' => […]]);`

this will preserve options and set them after initial zeroing is done

**Comment by domnuprofesor** [comment]
thanks for feedback, it works.

if one chooses to inject the values via $app (not 2nd param), one has to inject after the provider::register call. otherwise the provider clears the values.
