### ISSUE TITLE
Sub-mounts with same name clash

### ISSUE THREAD

**Issue by mgurov** [silexphp/Silex#1106]
Given: 

```php
$app = new Silex\Application();

$app->mount('/rootA', $rootA = $app['controllers_factory']);
$rootA->mount('/sub', $subA = $app['controllers_factory']);
$subA->get('/leaf', function() {
    return '/rootA/sub/leaf';
});

$app->mount('/rootB', $rootB = $app['controllers_factory']);
$rootB->mount('/sub', $subB = $app['controllers_factory']);
/*Comment this out to get `/rootA/sub/leaf` working*/
$subB->get('/leaf', function() {
    return '/rootB/sub/leaf';
});

$app->run();
```

Expected behavior: both `/rootA/sub/leaf`and `/rootB/sub/leaf`routes should be accessible. 

Actual behavior: only the later (`/rootB/sub/leaf` ) route is available, and the first one (`/rootA/sub/leaf`) returns HTTP 404.

**Comment by mgurov** [comment]
Tested against `1.3.x-dev 244dbef` and `dev-master e12be31`

**Comment by ikhsan017** [comment]
Facing the same problem with this, I am creating a static class wrapper that make the group routing easier, so the end result will be look like:

(the class is located here: https://github.com/xsanisty/SilexStarter/blob/develop/src/SilexStarter/StaticProxy/RouteProxy.php#L44-L58 )

```php
Route::group('/groupA', function(){
    Route::group('/test', function(){
        Route::group('/leaf', function(){
            Route::get('/next', function(){
                return 'groupA/test/leaf/next';
            });
        });
    });
});

Route::group('/groupB', function(){
    Route::group('/test', function(){
        Route::group('/leaf', function(){
            Route::get('/next', function(){
                return 'groupB/test/leaf/next';
            });
        });
    });
});
```

```groupA/test/leaf/next``` return 404, while ```groupB/test/leaf/next``` return exact ```groupB/test/leaf/next```, and its only affect more than 2 level nested route.

on the route below, both return ```groupA/test``` and ```groupB/test```
```php
Route::group('/groupA', function(){
    Route::get('/test', function(){
        return 'groupA/test';
    });
});

Route::group('/groupB', function(){
    Route::get('/test', function(){
        return 'groupB/test';
    });
});
```

**Comment by mivanov93** [comment]
This problem still hasn't been fixed.
