### ISSUE TITLE
Security - Add a note about generating MessageDigest passwords

### ISSUE THREAD

**Issue by adatta02** [silexphp/Silex#1109]
It's a tad bit confusing that the docs mention being able to secure a route with HTTP Basic Auth (http://silex.sensiolabs.org/doc/providers/security.html#securing-a-path-with-http-authentication) but then don't explicitly mention how to generate a MessageDigest when you don't have a User class setup.

https://gist.github.com/jreinke/3349922 seems to work. Any objection to adding that snippet along with a note after the "Securing a Path with HTTP Authentication" section?

**Comment by fabpot** [comment]
It's already in the docs, look for `security.encoder_factory`
