### ISSUE TITLE
NotFoundHttpException: No route found for "GET /blog"

### ISSUE THREAD

**Issue by Trioblack** [silexphp/Silex#1111]
Hello everybody. I am new to Silex and I'm testing the documentation of code:

$blogPosts = array(
	1 => array(
			'date'   => '2011-03-29',
			'author' => 'igorw',
			'title'  => 'Using Silex',
			'body'   => '...',
	),
	2 => array(
			'date'   => '2011-03-29',
			'author' => 'igorw',
			'title'  => 'Testing Silex',
			'body'   => '...',
	),
);

$app->get('/blog/{id}/', function (Silex\Application $app, $id) use ($blogPosts) {
    if (!isset($blogPosts[$id])) {
        $app->abort(404, "Post $id does not exist.");
    }

    $post = $blogPosts[$id];

    return  "<h1>{$post['title']}</h1>".
            "<p>{$post['body']}</p>";
});

But when I run I get this error:

NotFoundHttpException: No route found for "GET /blog"

ResourceNotFoundException

My request: http://localhost/TestSilex/silex/web/blog?id=1

**Comment by SpacePossum** [comment]
Hi,
This is most likely because you didn't setup a route for `/blog`, you did setup one for `/blog/{id}`. Please try `/blog/1` for example. If you would like some better/more complete help, please try the mailing list :)

**Comment by Trioblack** [comment]
Sorry for the delay. 
And if I have to send more than one parameter in the URL? How do I? 
Can you show an example? 

Thank U
