### ISSUE TITLE
Override SwitchUserListener in SecurityServiceProvider

### ISSUE THREAD

**Issue by feedmeastraycat** [silexphp/Silex#1117]
I've searched all over but I can't find anything about this in regards to Silex. I've tried different things that I found as solutions for Symfony but without success in Silex.

Wouldn't it be good if you could override the SwitchUserListener in SecurityServiceProvider? Somehow.

I want to use the impersonation feature and switch user but I only want to allow users to switch to other users below their own role in the role hierarchy. 

I have four different roles in a hierarchy with ROLE_USER as the lowest and ROLE_ADMIN as the highest. Lets call them:
* ROLE_ADMIN
* ROLE_2ADMIN
* ROLE_3ADMIN
* ROLE_USER

I want ROLE_ADMIN to be able to impersonate everyone but the next role (lets call it ROLE_2ADMIN) can only impersonate other ROLE_3ADMIN and ROLE_USER. And ROLE_3ADMIN can only impersonate ROLE_USER.

Excuse my ignorance if this is not the place, or if this can be done and I just dont know how. :)

**Comment by GromNaN** [comment]
You can redefine the [`$app['security.authentication_listener.switch_user._proto']`](https://github.com/silexphp/Silex/blob/1.2/src/Silex/Provider/SecurityServiceProvider.php#L476) in your own code after registering the SecurityServiceProvider.

**Comment by feedmeastraycat** [comment]
Ah. Dammit. :) Thanks!
