### ISSUE TITLE
PdoSessionHandler throws transaction lock

### ISSUE THREAD

**Issue by rajibahmed** [silexphp/Silex#1118]
Hi,

We are using doctrine2 with silex. And we have a cluster of apache instances. We need to use PdoSessionHandler to store session in mysql database.

````php
$app['session.db_options'] = array(
    'db_table'      => 'session',
    'db_id_col'     => 'session_id',
    'db_data_col'   => 'session_value',
    'db_time_col'   => 'session_time',
    'lock_mode => 2 // TRANSACTIONAL LOCKING, this needed to be set to 0
);
````
Not Knowing this option needs to be tweaked, I lost many hours. 
Maybe documentation should add block about it.

**Comment by davedevelopment** [comment]
Yep, I got stung with this one! Not sure if Silex is the place for the documentation, maybe the symfony component docs should have it (if not already).

**Comment by rajibahmed** [comment]
But the problem is, components documents it properly. Then again if you are using Silex and Doctrine ORM multi server settings, this will byte you. And configuration must be passed through session provider settings. 
So, I am pretty sure we should add bit of documentation to silex docs.

**Comment by davedevelopment** [comment]
I just looked and I didn't realise we had a cookbook for PDO sessions, so I'd definitely be :+1: for something about this in there.

**Comment by rajibahmed** [comment]
:+1: should I add it then?

**Comment by rajibahmed** [comment]
Or should we change it to NON TRANSACTIONAL by default ?

**Comment by davedevelopment** [comment]
Definitely send a PR, you'll have my vote. I think it would be better as a note/warning, the symfony devs wouldn't have made the transactional locking the default without good reason. I'd also make sure to use the constants that are available, for example I use `PdoSessionHandler::LOCK_ADVISORY`.
