### ISSUE TITLE
Set multiple storage for session

### ISSUE THREAD

**Issue by ahmadina** [silexphp/Silex#1125]
Hi
Can i set multiple storage for session in silex or use different session handler per section of code? 

for example :

~~~php

// for csrf storage 
$app['session.storage.handler'] = $app->share(function ($app) {
    return new \Application\Core\Helpers\Redis\RedisCsrfSessionHandler($app['redis']);
});

// for another session
$app['session.storage.handler'] = $app->share(function ($app) {
    return new \Application\Core\Helpers\Redis\RedisSessionHandler($app['redis']);
});

~~~

Because i use different hash table for csrf or other

**Comment by henrikbjorn** [comment]
If you define two services with the same id, the last one will overwrite the first.

What you can do, is use a different CSRF handler than the session one, or overwrite its definition to use another session handler https://github.com/silexphp/Silex/blob/1.2/src/Silex/Provider/FormServiceProvider.php#L108
