### ISSUE TITLE
ValidatorServiceProvider using deprecated classes

### ISSUE THREAD

**Issue by dwolf555** [silexphp/Silex#1126]
"Deprecated: The Symfony\Component\Validator\Validator class is deprecated since version 2.5 and will be removed in 3.0. Use the Symfony\Component\Validator\Validator\RecursiveValidator class instead. in /.../vendor/symfony/validator/Symfony/Component/Validator/Validator.php on line 14"

**Comment by fabpot** [comment]
Fixed in the 1.3 branch.
