### ISSUE TITLE
Class 'Symfony\Component\Validator\Constraints' not found

### ISSUE THREAD

**Issue by crimson-labs** [silexphp/Silex#1128]
Using Silex - added the following into composer.json

"require": {
    "silex/silex": "~1.2",
    "symfony/security": "~2.6",
    "doctrine/dbal": "~2.2",
    "symfony/validator": "~2.6"
  },

From the documentation: http://silex.sensiolabs.org/doc/providers/validator.html

use Symfony\Component\Validator\Constraints as Assert;

I get Fatal error: Class 'Symfony\Component\Validator\Constraints' not found

The class does not exist in /vendor/symfony/validator/Symfony/Component/Validator.

I did composer update before attempting to use this.

Please assist.

**Comment by henrikbjorn** [comment]
You are not writing all of what you do, and you need to read up on namespacing and how aliasing namespaces works in php.

This is not a Silex issue.

**Comment by crimson-labs** [comment]
Wow. For someone in a support role you really are rude. Do not always assume that just because someone has a problem with something, that they do not understand how PHP works. It is perhaps not a Silex issue, but maybe, just maybe, other Silex users will experience the same problem. When they do, I hope they are treated with a little more respect than this. Thanks for not giving a damn.

**Comment by henrikbjorn** [comment]
http://php.net/manual/en/language.namespaces.importing.php

**Comment by namaless** [comment]
Crimson not escape from your fault... learn from other messages and happy coding ^_^
