### ISSUE TITLE
Can the v2 branch get a alpha release tagged?

### ISSUE THREAD

**Issue by ecaron** [silexphp/Silex#1130]
Because we rely on Pimple v3 elsewhere in our project, we're based on Silex v2 (~2.0@dev) (same reasons as discussed in #1076).I know the roadmap is still in works  for #915, but a tagged alpha release would make it easier to test the waters.

**Comment by Atriedes** [comment]
:+1:  on this issue

**Comment by ragboyjr** [comment]
:+1:

**Comment by mediamonks-robert** [comment]
+1

**Comment by Cangit** [comment]
:+1:

**Comment by dominikzogg** [comment]
+1

**Comment by fabpot** [comment]
Whenever we are confident about the code, yes, but not until then. And not before we tag 1.3 as stable anyway.

**Comment by mediamonks-robert** [comment]
So when do you expect to be confident about it? The 2.0 branch is out there for a long time already and a lot of people are using it already. It would be really helpful if a road map was available so users would have an idea what to expect.
