### ISSUE TITLE
Rewrite Images to a specific Silex Route

### ISSUE THREAD

**Issue by Fruchuxs** [silexphp/Silex#1134]
Hello everyone,

i tried to rewrite all requests for images to a specific silex route, e.g, /image or /images/{path}. 
But i don't know how to call a route over a htaccess file. I know this is possible with symfony (http://symfony.com/doc/current/cookbook/configuration/apache_router.html), so i assume with silex too. But i can't apply the symfony example on silex. :(

My .htaccess file:
```
Options +FollowSymlinks
Options -MultiViews
RewriteEngine On

RewriteCond %{REQUEST_URI} !assets
RewriteRule \.(?:jpe?g|gif|png)$ index.php/image[QSA,L]

RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [QSA,L]
```

Greetings,
Fruchuxs

**Comment by fabpot** [comment]
The Apache router (deprecated and removed in Symfony 3.0) was only a way to speed-up routing (but it did not work well enough).

**Comment by Fruchuxs** [comment]
Hello Fabpot,

thanks for your reply!
Is there (a/nother) way to redirect requests on specific files to a specific route?
It's not very important. At the moment i use another file.


Greetings
