### ISSUE TITLE
Undefined index: Domain (During phpunit test)

### ISSUE THREAD

**Issue by doncredas** [silexphp/Silex#1135]
During the functional test of my Application i have the following exception Symfony\Component\Debug\Exception\ContextErrorException: Notice: Undefined index: Domain.
The stack trace is attached. Please I need help!!
![schermata del 2015-04-06 19 48 46](https://cloud.githubusercontent.com/assets/8933992/7008890/9a978882-dc96-11e4-9ce0-f09d3c7e1ad5.png)

**Comment by doncredas** [comment]
I've tried to add array( 'session.storage.options' => array('domain' => '.domain.com') as parameter while registering the SessionServiceProvider() in the app.php but it does not work either.

**Comment by doncredas** [comment]
neither array( 'session.storage.options' => array('cookie_domain' => '.domain.com') works

**Comment by mTorres** [comment]
@doncredas, if this is still relevant, can you share the code of the testPageIsSuccessful method? If you managed to solve this, can you close this issue?

Thank you.

**Comment by GromNaN** [comment]
It's surprising it looks for `Domain` with a cap `D`. While the code uses `domain`.
https://github.com/silexphp/Silex/blob/1.3/src/Silex/Provider/SessionServiceProvider.php#L111
