### ISSUE TITLE
Silex's website design is open for contributions ?

### ISSUE THREAD

**Issue by nbpalomino** [silexphp/Silex#1147]
Just that question.

I would like to improve Silex's website design.

**Comment by maciekpaprocki** [comment]
I would love to make silex website responsive as it's extremely annoying when watching it on small screen. Website is so simple that giving only few lines of code I might make it happen. Any places where  I can update css + maybe a bit of meta?

**Comment by fabpot** [comment]
The website is currently closed-source and it would need some work to open-source it. I will see how I can make it happen and updated this issue when/if done. Thanks.
