### ISSUE TITLE
Silex 2 and Symfony 2.7+ (with Twig 1.18.0)'s app.user

### ISSUE THREAD

**Issue by J7mbo** [silexphp/Silex#1152]
Trying to use `{{ app.user }}` with the above versions says that it doesn't exist in the application. Is this because `twig-bridge` doesn't yet support it?

I have registered everything as expected, so I can still use `{{ app.security.token.user }}` but then I get some `E_DEPRECATED` notices. Again, switching to `{{ app.user }}` gives me `TWIG_ERROR_RUNTIME` saying that Method "user" for object does not exist.

What am I doing wrong?

**Comment by J7mbo** [comment]
Addition: According to the [docs](http://symfony.com/doc/2.7/reference/twig_reference.html#app), it seems there should be this `GlobalVariables` class. I could create this myself, and I can only find reference to this within [FrameworkBundle](https://github.com/symfony/FrameworkBundle). Something missing in Silex / Twig?

**Comment by J7mbo** [comment]
This was 5 days ago - am I doing something retarded?

**Comment by GromNaN** [comment]
The documentation is related to Symfony fullstack, I agree that it's not obvious.

The `app` variable that is accessible in Twig refers to the Silex Application. So you have access to all the methods of this class and all the services registered. And by default there is no service or method named `user`.

Using the [`SecurityTrait`](http://silex.sensiolabs.org/doc/providers/security.html#traits) you can declare a method [`$app->user()`](https://github.com/silexphp/Silex/blob/master/src/Silex/Application/SecurityTrait.php#L32-L43) that returns the current user.

**Comment by J7mbo** [comment]
As Silex previously had `app.security.token.user` available and it's deprecating accessing `app.security`, which is an instance of the deprecated `SecurityContext`, I'm presuming there needs to be a replacement using the new authorisation checker or token storage mechanisms. Otherwise, how is everyone using Silex going to access the user object, write their own or use the trait?

**Comment by GromNaN** [comment]
It's `{{ security.token_storage.token.user }}`.

**Comment by J7mbo** [comment]
Thanks @GromNaN... What is the security var an instance of?

**Comment by GromNaN** [comment]
It's a `Symfony\Component\Security\Core\SecurityContext`.
https://github.com/silexphp/Silex/blob/master/src/Silex/Provider/SecurityServiceProvider.php#L95-L97

**Comment by stof** [comment]
use ``app.token_storage`` to access the TokenStorage (given that ``app`` is your Silex Application)

**Comment by stof** [comment]
@GromNaN your suggestion does not work. the SecurityContext does not have a getter for the TokenStorage, and it is also precisely the class which should be avoided as it is deprecated

**Comment by GromNaN** [comment]
Damn it. I didn't write what I had in my head.
I fixed the comment.

**Comment by J7mbo** [comment]
> Method "token_storage" for object "Silex\Application" does not exist.

Btw, I have registered everything as expected and all my security works fine. I also have access to the `TokenStorage` and `AuthorizationChecker` objects from my controllers onwards, so it definitely exists.

**Comment by stof** [comment]
@J7mbo sorry, the service is named ``security.token_storage``, not ``token_storage``. So the right code would be ``app.['security.token_storage'].token.user``

**Comment by J7mbo** [comment]
Can we split this out to `app.token_storage` and `app.authorization_checker`?

Using `app['security.token_storage']` seems unclear to me that we're ***not*** using `security.token_storage`, security being an instance of `SecurityContext`.

**Comment by fabpot** [comment]
See #1165 for a possible solution.
