### ISSUE TITLE
Using mysqli without PDO

### ISSUE THREAD

**Issue by vkachov** [silexphp/Silex#1166]
I havent PDO on my server, and i want use just mysqli. But I cant, because PDO classes constant used even in MySqli driver. For example: PDO::PARAM_STR, PDO::FETCH_ASSOC,PDO::FETCH_NUM etc.

**Comment by stof** [comment]
What does this have to do with Silex ?

**Comment by vkachov** [comment]
funny. I use Silex, i have this problem, and you ask me, what does this have to do width Silex...

**Comment by mediamonks-robert** [comment]
Please show the line in code where Silex uses PDO class constants.

**Comment by vkachov** [comment]
class Doctrine\DBAL\Connection line 176.

**Comment by mediamonks-robert** [comment]
Thats Doctrine, not Silex.

**Comment by vkachov** [comment]
understand, thanks
