### ISSUE TITLE
$app['exception_handler']->disable() breaks $app->abort()

### ISSUE THREAD

**Issue by joshribakoff** [silexphp/Silex#1173]
If my application throws exceptions that I do not catch, I do not want Silex to take control & swallow those. I do not want to to setup Monolog. I just want to let my exceptions bubble up & have PHP append a fatal error to my error log about the uncaught exception. I don't want Monolog, because that will not log all PHP errors, and I want everything in one place (The php-fpm error log). Its the reason I chose a microframework, because I specifically don't want it taking over control or changing default PHP behavior.

Currently the implementation of $app->abort() to trigger a 401 response code for example relies on throwing an exception. It appears that I cannot disable Silex from swallowing exceptions without also breaking the functionality of $app->abort(). Instead of $app->abort() returning the proper response codes, the requests are responded to with a 500 response code & the message is logged. 

Basically as a user, I would not expect `$app['exception_handler']->disable();` to break `$app->abort()` because the fact that the latter function is internally implemented using PHP exceptions as a sort of "go to" mechanism is not something I consider an exceptional code path in my controller. I consider $app->abort() to be part of my regular code path. A true exception would be a network or database failure. The fact my user has submitted incorrect credentials is NOT an "exception", at least to me.

I'm not sure if this can be easily fixed without breaking code, because some people might do `$app->abort()` instead of `return $app->abort()` & therefore rely on the exception. How about a way to configure Silex to catch that particular exception but disable it from catching all others? One possible fix is to allow whitelisting/blacklisting particular exceptions. I know I can write a custom exception_handler service & replace the default one, I just feel that Silex should not swallow exceptions by default, and it would be nice to not have to write custom exception_handlers to do so.

At the very least, maybe the default exception_handler could use trigger_error to write to the PHP error log when it does swallow an exception. That would be nice to have out of the box in Silex projects.

## Edit
Possible duplicate of - https://github.com/silexphp/Silex/issues/951 I will simply change my code to use `return new Response()`. My failure to read the documentation thoroughly had me confused - I mistakenly assumed `return $app->abort()` was shorthand for `return new Response`, since return `$app->json()` is shorthand for `return new JsonResponse`. This would be more intuitive, to me.

**Comment by stof** [comment]
@joshribakoff the other drawback of your approach is that in case of errors, your user will just see a blank page instead of having a nice page saying there was an error and you are aware of it, though.

**Comment by joshribakoff** [comment]
Silex is being used in my project to implement a REST API. In Angular app that consumes the API, I handle 500 response codes appropriately. In fact, sending Silex's HTML error pages to Angular crashes the browser.

**Comment by GromNaN** [comment]
I don't get why you don't want to use Monolog. It can write to [`error_log`](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/ErrorLogHandler.php).

Also, instead of using the method `$app->abort()` (which is a shortcut for general use-cases), you can return a `Response` object.

**Comment by GromNaN** [comment]
You can also use (`$app->error()`](http://silex.sensiolabs.org/doc/usage.html#error-handlers)

**Comment by joshribakoff** [comment]
> I don't get why you don't want to use Monolog. It can write to error_log.
Because PHP already does it out of the box & my programming style is to not complicate things if not needed. I'm closing this issue as I think the only "issue" is either with the documentation or my own understanding thereof.
