### ISSUE TITLE
SwiftmailerServiceProvider overwrites default $app['swiftmailer.options'] on instantiation

### ISSUE THREAD

**Issue by cgsmith** [silexphp/Silex#1176]
Swiftmailer's register() does not allow it to set the options.  It just overrides the app's options that may have been set previously.  You can see this on line 26 of the SwiftmailerServiceProvider.php file

**Comment by GromNaN** [comment]
I don't have any issue with swiftmailer options. Can you paste a code sample ?

**Comment by cgsmith** [comment]
I am using @igorw config provider.  I have examples but am headed out of the country shortly.  I can provide an example when back.

But if you extend the slim application and overload the constructor you might be able to replicate (i call the parent right after that).

I overload the constructor to have my class register the providers i need.  First Igor's config, then swiftmailer.

I found that $app['swiftmailer.options'] = array (); was causing the assignment issues.

Sorry for any readability issues here.  I am on the phone.

**Comment by cgsmith** [comment]
Sorry.  Apparently an rtfm moment

Sorry to waste time!


https://github.com/silexphp/Silex/blob/1.3/doc/providers.rst

**Comment by kamilsk** [comment]
please show code examples

**Comment by cgsmith** [comment]
I will by the end of today.  Found out where the inconsistency was.

**Comment by cgsmith** [comment]
Hey @kamilsk - I found out this issue a bit later playing around with Igor's config service provider.  If you already have `$app['swiftmailer.options']`, like you would using the Doctrine service provider, it will ignore them.

With [this commit](https://github.com/cgsmith/Silex/commit/70c056f5d1b998d76d10b5833c38562377df21ab) it will be able to allow it.

Test the issue with the following code:

```php
// The issue lies here

$app['swiftmailer.options'] = array('host'=>'your-host-name-here');
$app->register(new Silex\Provider\SwiftmailerServiceProvider());
var_dump($app['swiftmailer.options']); // This will have 'host' as 'localhost' as that is the default
```

Looking at the [Doctrine service provider](https://github.com/silexphp/Silex/blob/1.3/src/Silex/Provider/DoctrineServiceProvider.php#L48), you can see that they allow defaults to be set before the provider is instantiated.

**Note**: I don't think there would be any BC breaks due to the fact that most people would of had to configure the provider after loading it.

If all looks good I will submit the PR.

**Comment by kamilsk** [comment]
Your example is not a "true way", IMO. If you use that provider as specified in the documentation, then everything is working fine.

See
https://github.com/silexphp/Silex/blob/1.3/src/Silex/Provider/SwiftmailerServiceProvider.php#L53-L60
https://github.com/silexphp/Silex/blob/1.3/src/Silex/Application.php#L169-L180
http://silex.sensiolabs.org/doc/providers/swiftmailer.html

And example below
```php
$app->register(new Silex\Provider\SwiftmailerServiceProvider(), [
    'swiftmailer.options' => [
        'host' => 'host',
        'port' => '25',
        'username' => 'username',
        'password' => 'password',
        'encryption' => null,
        'auth_mode' => null
    ]
]);
```
What do you think?

**Comment by stof** [comment]
@cgsmith your issue is that you are supposed to customize parameters **after** registering the provider. Otherwise the parameter defined in the provider will win

**Comment by fabpot** [comment]
Closing this one for the reasons explained by @stof. By the way, all providers work this way.

**Comment by cgsmith** [comment]
@fabpot @stof I do not understand a couple of things then.

For example: why does the doctrine provider do the opposite of how the providers are said work? Is this a bug in the doctrine provider? 

I am just trying to understand Silex a bit better and contribute in anyway.  Thank you!

Doctrine Provider and SwiftMailer example:
```php
$app['db.options'] = [
    "driver" => "pdo_mysql",
    "host" => "my.local",
    "dbname" => "vse",
    "user" => "some-user",
    "password"=> "12345"
];
$app['swiftmailer.options'] = [
    'host'=>'your-host-name-here'
];
$app->register(new Silex\Provider\DoctrineServiceProvider());
$app->register(new Silex\Provider\SwiftmailerServiceProvider());
var_dump($app['swiftmailer.options']); // properties set to defaults, would expect to be similar to doctrine
var_dump($app['db.options']); // shows properties unmodified, this is how I would expect it to work
```

**Comment by kamilsk** [comment]
@cgsmith, good point

**Comment by stof** [comment]
@cgsmith this is because the DoctrineServiceProvider does not define this parameter at all. It defines ``db.default_options``

**Comment by mediamonks-robert** [comment]
@stof obvously but that proves that "By the way, all providers work this way." isn't actually true and it is inconsistent right now.

**Comment by cgsmith** [comment]
Hi all, please provide feedback regarding the PR.  I feel it is important to provide a consistent experience for the developer and this provider was a "gotcha" for me when I started learning Silex.  Other providers allowed the application's options to be set before hand while SwiftMailer didn't.  

It led me down a chase to see that the provider was overriding the values.  The PR is backwards compatible and will provide this unified experience and allow the developer to institute there own paradigm while programming.

**Comment by mediamonks-robert** [comment]
+1 on this from me.
