### ISSUE TITLE
No upgrade instructions provided

### ISSUE THREAD

**Issue by desarrolla2** [silexphp/Silex#1187]
I want to upgrade my project from silex 1.2 to 1.3 and i cant found the upgrade file that it was so useful in when i upgrade my symfony projects.

**Comment by stof** [comment]
@desarrolla2 the changelog for 1.3 (available in the source code at https://github.com/silexphp/Silex/blob/1.3/doc/changelog.rst#130-2015-06-05 or online at http://silex.sensiolabs.org/doc/changelog.html) lists the changes done in 1.3.
the only BC break in 1.3 is the removal of the TwigCoreExtension which was already deprecated in 1.2 in favor of the HttpFragmentServiceProvider. And there is only 1 deprecation in silex 1.3

**Comment by desarrolla2** [comment]
Thanks. Maybe this document would be linked on Readme to found it

**Comment by desarrolla2** [comment]
I send this PR https://github.com/silexphp/Silex/pull/1188 merge if it would be interesting

**Comment by desarrolla2** [comment]
@fabpot just merge the PR
