### ISSUE TITLE
Silex Validator ConstraintValidatorFactory missing Expression

### ISSUE THREAD

**Issue by MatthewReed** [silexphp/Silex#1191]
Silex\ConstraintValidatorFactory is missing code to address Expression constraint creation.
Comparing it to Symfony\Validator\ConstraintValidatorFactory, I think that changing createValidator method as follows:

    private function createValidator($name)
    {
        if (isset($this->serviceNames[$name])) {
            return $this->container[$this->serviceNames[$name]];
        }

        if('validator.expression' === $name) {
             return new \Symfony\Component\Validator\Constraints\ExpressionValidator();
        }

        return new $name();
    }

should be sufficient.

**Comment by fabpot** [comment]
Can you create a pull request and add some tests for this?

**Comment by MatthewReed** [comment]
I'll start it ASAP.





----Messaggio originale----

Da: notifications@github.com

Data: 14/07/2015 8.49

A: "silexphp/Silex"<Silex@noreply.github.com>

Cc: "MatthewReed"<orionerossi@libero.it>

Ogg: Re: [Silex] Silex Validator ConstraintValidatorFactory missing Expression (#1191)




Can you create a pull request and add some tests for this?
