### ISSUE TITLE
Weird exception when updating to Silex 1.3 from 1.2

### ISSUE THREAD

**Issue by jcampbe** [silexphp/Silex#1197]
My route is "http://localhost/{slug}.{type}", where "slug" is a dynamic page identifier and "type" is one of {html,ics,json}. Type defaults to "html".

In Silex 1.2, passing a url like "http://localhost/testing" brings up a page without issue.

In Silex 1.3, it sometimes returns "Parameter "slug" for route "my_route" must match "[^/\.]++" ("" given) to generate corresponding URL."

I've tried modifying the assertion on {slug} and {type} to no avail.

**Comment by fabpot** [comment]
I don't see which change would lead to this. Can you give us a small Silex app that demonstrates the issue?

**Comment by fabpot** [comment]
Closing as there is no feedback. Feel free to reopen with more details.
