### ISSUE TITLE
Variables in mount path

### ISSUE THREAD

**Issue by md2perpe** [silexphp/Silex#1199]
I'd like to be able to be able to use variables in mount paths:
```php
$app->mount('/{year}/{month}/', function ($year, $month) {
	return new YearMonthController($year, $month);
})
->assert('year', '\d\d\d\d')
->convert('year', function ($year) { return (int)$year; })
->assert('month', '\d\d|\d')
->convert('month', function ($month) { return (int)ltrim($month, '0'); })
;
```

For a specific year and month, say 2015 and 07 respectively, this should work the same way as
```php
$app->mount('/2015/07/', new YearMonthController(2015, 7));
```

See also http://stackoverflow.com/questions/18987808/silex-variable-mount-point for someone having the same kind of wish.

**Comment by SanderKnape** [comment]
This is actually already possible. The following works perfectly fine;

```php
$collection = $app["controllers_factory"];
$collection->get("/{month}", function($year, $month) {
    return new Response("{$year} -- {$month}");
});

$app->mount("/{year}", $collection);
```

**Comment by md2perpe** [comment]
Then perhaps also this works:

```php
$collection = $app['controllers_factory'];
$collection->get('/', function ($year, $month) {
    return ...;
});

$app->mount('/{year}/{month}', $collection);
```

But still, every handler in `$collection` then has to take `$year` and `$month` as arguments, while in my suggestion handling of these arguments are concentrated to one place.

**Comment by henrikbjorn** [comment]
seems like you are looking for something similiar to the way states works in ui-router for angular. Dont think this is possible, having "two" controllers for a single uri.

**Comment by SanderKnape** [comment]
In that case what you can do is use [Middleware](http://silex.sensiolabs.org/doc/middlewares.html). The logic you want to execute before every mounted routed can be done like this;

```php
$collection = $app["controllers_factory"];

// this is the middleware that is executed before every route in the $collection
$collection->before(function(Request $request) use ($app) {
  $year = $request->attributes->year;
  if($year < 2000) {
   // "short-circuit" the request-handling (see documentation)
   return new Response("", 404);
 }
});

$collection->get("/{month}", function($month) {
    return new Response("{$month}");
});

// some other random route that also isn't executed when the middleware returns a response
$collection->get("/{month}/{day}", function($month, $day) {
    return new Response("{$month} -- {$day}");
});

$app->mount("/{year}", $collection);
```

As you can see, in a controller you can "request" only those variables you need. Both example controllers don't "request" the $year variable.

**Comment by md2perpe** [comment]
How does that concentrate the handling of `$year` and `$month` to one place?

**Comment by Shaked** [comment]
Hey

@md2perpe would you say that basically you would like `$app->mount($prefix, $collection)` to accept a closure and to return the `Route` instead of the `Application` (so `->assert` and `->convert` will work) ?

**Comment by ragboyjr** [comment]
@md2perpe, can we close this feature request?

**Comment by md2perpe** [comment]
Well, I don't think that this feature-request has been implemented, and as such it shouldn't be closed. But maybe it's difficult to implement, and there are workarounds, so if you really think that it should be closed, you're allowed to do so.

My workaround in one controller (`Period.php` catching `/period`):
```php
$controller->mount('/{year}/{month}', (new PeriodYearMonth())->connect($app));
```
Then, in `PeriodYearMonth.php`:
```php
$controller->get('/', [ $this, 'getYearMonth' ]);
...
public function getYearMonth($year, $month) {
    ...
}
```

**Comment by md2perpe** [comment]
Why wouldn't my example work? Is it because something like that would impossibly work in any model, or that it wouldn't work in Silex as it is modelled today?

Regarding your last question: It's not being able to assert and convert on a ControllerCollection that is my primary wish. What I want is to be able to have a generic controller that explicitely gets variables from the path.

**Comment by ragboyjr** [comment]
@md2perpe, the first example doesn't work because you can't mount a controller. You can only mount a controller provider interface or a ControllerCollection itself

**Comment by ragboyjr** [comment]
Hmm, ok, I'm not fully understanding your use case. To me

```php
$app->match('/{year}/{month}/', $some_controller);
```

Would do exactly that. It would accept the year and month and handle them.

**Comment by md2perpe** [comment]
@ragboyjr 
Thus you say that the first example doesn't work because you interpret "controller" literally. I was new to Silex and rather meant a ControllerCollection.

Your example code is a workaround, but it isn't explicit how to get the values of the parameters. Compare this to the following where it's obvious:
```php
$app->get('/{year}/{month}/', function ($year, $month) { ... });
```

**Comment by ragboyjr** [comment]
@md2perpe, understood about the first part.

```
$app->match('/{year}/{month}/', function ($year, $month) { ... });
```

also works, and is explicit. So what more did you need with this?

**Comment by md2perpe** [comment]
@ragboyjr 
I want subpaths like `/2016/05/sales`. I could of course do
```php
$app->match('/{year}/{month}/', function ($year, $month) { ... });
$app->match('/{year}/{month}/sales', function ($year, $month) { ... });
...
```
but prefer to have one handler for `/{year}/{month}`, and then subhandlers for the subpaths (just like how a ControllerCollection is used).

**Comment by ragboyjr** [comment]
Ok, so your in your sales route, would you still want the $year, $month to be arguments to the controller?

**Comment by md2perpe** [comment]
I'll give a step-by-step explanation for the route `/2016/05/sales`:

* Match `/2016/05`,
* Create some kind of handler (say YearMonthHandler), passing 2016 and 05 to the handler that will store those numbers inside itself,
* Match `/sales`,
* Call the subhandler (probably a method in YearMonthHandler).

In the last step, the numbers 2016 and 05 need not be passed to the subhandler, since those can be taken from YearMonthHandler, especially if the subhandler is a method in the handler.

**Comment by ragboyjr** [comment]
Understood

**Comment by ragboyjr** [comment]
Well, your specific implementation doesn't sound like something should be integrated into the core of Silex (but that's just my opinion). However, there are other ways you can do what you are requesting.

```php
$sale = $app['controllers_factory'];
$sale->get('/sale', function($year, $month) {
    return sprintf('%d-%d', $year, $month);
});
$sale->get('/report/{id}', function($year, $month, $id) {
    return sprintf('%d-%d-%s', $year, $month, $id);
})->assert('id', '[a-z]+'); // this only applies to the report route

// these assertions and conversions apply to all of the routes in the collection.
// must be done after the routes are defined
$to_int = function($val) { return intval($val); };
$sale->assert('year', '\d{4}')->convert('year', $to_int);
$sale->assert('month', '\d{2}')->convert('month', $to_int);

$app->mount('/{year}/{month}', $sale);
```

This doesn't have an intermediate controller, however all of the processing/converting of the routes is done by the `$sale` controller collection. This is possible because the ControllerCollection overloads the `__call` method and delegates any unknown methods to each of it's controllers. Then each controller does the same thing and delegates to their `SilexRoute` variable.

**Comment by ragboyjr** [comment]
@md2perpe, let me know if this works for you

**Comment by md2perpe** [comment]
I described my workaround in a post:
https://github.com/silexphp/Silex/issues/1199#issuecomment-216570019
It's the same solution as you propose.

**Comment by ragboyjr** [comment]
Your implementation looks a little bit different because I'm using converters/asserts on a route collection in order to do the processing of variables instead of setting up delegating handlers.

Regardless, I'm trying to either close this ticket, or figure out a manageable scope of work that a PR can be made from. I feel as if the converters/asserts on the controller collection (like I showed in ) provide the (more or less) the functionality that you described with a clean/simple syntax. However, if you can maybe come up with a clear description of another feature that is separate from what is already handled by silex, we can look into that

**Comment by ragboyjr** [comment]
@md2perpe, any word?

**Comment by md2perpe** [comment]
It's okay to close it.

**Comment by ragboyjr** [comment]
@md2perpe or @fabpot, can you close this?

**Comment by md2perpe** [comment]
Issue needs a big change of how routing and controllers work in Silex, and there is a good workaround.

Closing issue.
