### ISSUE TITLE
Silex\ControllerProviderInterface::connect does not accept subclass of Silex\Application

### ISSUE THREAD

**Issue by cossay** [silexphp/Silex#1201]
Silex\ControllerProviderInterface::connect does not accept a subclass of Silex\Application. I'd like to know if this is a bug or a design decision. I'm using Silex 1.3.

**Comment by fabpot** [comment]
What do you mean by "not accept"? The interface uses a typehint of `Silex\Application`, so you should be able pass any implementation of such a class including a subclass.

**Comment by cossay** [comment]
I'd to add some functionalities to the application class so I extended the base class this way:
```
<?php
namespace BridgewayGhana\Payment;

use Silex\Application as SilexApplication;
use Silex\Application\UrlGeneratorTrait;

class Application extends SilexApplication {

	use UrlGeneratorTrait;

	public function __construct(array $values = []) {
		parent::__construct($values);
	}
}

```
I can use this class anywhere the base class is expected but when it comes to controller providers, it doesn't  work. Here is one example:

```
<?php
namespace BridgewayGhana\Payment\Provider\ControllerProvider;

use BridgewayGhana\Payment\Application;
use Silex\ControllerProviderInterface;

class AuthApiControllerProvider implements ControllerProviderInterface {

	public function connect(Application $app) {

		$mount_point = $app['controllers_factory'];

		$mount_point->post('/login', 'BridgewayGhana\\Payment\\Http\\Controller\\Api\\Local\\AuthController::postLogin');

		return $mount_point;
	}
}
```
I get the following error whenever I try to mount this provider
```

Fatal error: Declaration of BridgewayGhana\Payment\Provider\ControllerProvider\AuthApiControllerProvider::connect() must be compatible with Silex\ControllerProviderInterface::connect(Silex\Application $app) in /var/www/html/bridgeway/payment/vendor/bridgeway/BridgewayGhana/Payment/Provider/ControllerProvider/AuthApiControllerProvider.php on line 7
```

**Comment by stof** [comment]
Well, changing an interface typehint is forbidden in PHP. But the subclass will satisfy the ``Silex\Application`` typehint

**Comment by cossay** [comment]
Then, shouldn't  Silex\ControllerProviderInterface::connect() take an interface instead?

**Comment by cossay** [comment]
Current implementation is:
```
<?php

/*
 * This file is part of the Silex framework.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Silex;

/**
 * Interface for controller providers.
 *
 * @author Fabien Potencier <fabien@symfony.com>
 */
interface ControllerProviderInterface
{
    /**
     * Returns routes to connect to the given application.
     *
     * @param Application $app An Application instance
     *
     * @return ControllerCollection A ControllerCollection instance
     */
    public function connect(Application $app);
}

```
and what I mean is:

```
<?php

/*
 * This file is part of the Silex framework.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Silex;

/**
 * Interface for controller providers.
 *
 * @author Fabien Potencier <fabien@symfony.com>
 */
interface ControllerProviderInterface
{
    /**
     * Returns routes to connect to the given application.
     *
     * @param Application $app An instance of ApplicationInterface
     *
     * @return ControllerCollection A ControllerCollection instance
     */
    public function connect(ApplicationInterface $app);
}

```

**Comment by stof** [comment]
There is no ApplicationInterface in Silex, and there is no real value about adding one. Adding an interface would mean that creating implementations which don't extend from ``Silex\Application`` is supported (and it will be the **only** difference with the current way). But then you would have to reimplement all methods of ``Silex\Application`` to implement the interface.

**Comment by cossay** [comment]
Should I modify Silex\Application directly?

**Comment by stof** [comment]
No. But your child class will pass typehints on ``Silex\Application`` in the connect method:

```php
$app = new BridgewayGhana\Payment\Application();

var_dump($app instanceof Silex\Application); // will display "true"
```

It looks to me you don't really understand how inheritance works

**Comment by mathroc** [comment]
@cossay 

your exemple should be:

```php
namespace BridgewayGhana\Payment\Provider\ControllerProvider;

use Silex\Application;
use Silex\ControllerProviderInterface;

class AuthApiControllerProvider implements ControllerProviderInterface {

    public function connect(Application $app) {

        $mount_point = $app['controllers_factory'];

        $mount_point->post('/login', 'BridgewayGhana\\Payment\\Http\\Controller\\Api\\Local\\AuthController::postLogin');

        return $mount_point;
    }
}
```

**Comment by cossay** [comment]
@mathroc, that's how I'm currently doing.

**Comment by mathroc** [comment]
@cossay In your version you have : `use BridgewayGhana\Payment\Application;` instead of `use Silex\Application;`

**Comment by cossay** [comment]
I switched the application class before posting those codes.

**Comment by cossay** [comment]
@mathroc, thank you.
@stof, I wouldn't have passed my application classs ( BridgewayGhana\Payment\Application) to Silex\ControllerProviderInterface::connect() if I didn't know an instance of BridgewayGhana\Payment\Application is also an instance of Silex\Application.

**Comment by mathroc** [comment]
@cossay so it's working with `use Silex\Application;` ? if your problem is that you can't change the typehint, that's not even Silex choice; as @stof said, it's forbidden in PHP

if you want to use methods only defined in your `BridgewayGhana\Payment\Application` you should proceed like that:


```php
namespace BridgewayGhana\Payment\Provider\ControllerProvider;

use Silex\Application as SilexApplication;
use Silex\ControllerProviderInterface;
use BridgewayGhana\Payment\Application;

class AuthApiControllerProvider implements ControllerProviderInterface {

    public function connect(SilexApplication $app) {

        $mount_point = $app['controllers_factory'];

        $mount_point->post('/login', 'BridgewayGhana\\Payment\\Http\\Controller\\Api\\Local\\AuthController::postLogin');

        if ($app implements Application) {
                $app->mymethod();
        }

        return $mount_point;
    }
}
```

**Comment by cossay** [comment]
Yeah, it works with
```
use Silex\Application
```
It's all my fault. I should have taken a look at the signature for Silex\ControllerProviderInterface::connect() before posting this issue.

**Comment by davedevelopment** [comment]
> It's all my fault.

These things happen, hope you're not feeling down about it!

**Comment by cossay** [comment]
@davedevelopment 
No.
