### ISSUE TITLE
Silex service locator, name clashing and DI

### ISSUE THREAD

**Issue by mivanov93** [silexphp/Silex#1202]
Currently Silex is using the service locator pattern by attaching everything to $app,
but this seems a bit clunky, since we can't easily address name clashes. Autocomplete is also missing.

And the problem comes with controllers as well, since when using them as services - we just get $app injected in them.

Shouldn't it be made possible to use pure DI? 

Or at the very least some namespacing mechanism, instead of just doing $app['stuff1.stuff2.stuff3'] which seems rather ugly and hard to debug.

**Comment by davedevelopment** [comment]
> Yeah, well, you know, that's just, like, your opinion, man.

I don't think the way the container is used in silex is going to change any time soon, if you really don't like it I'd suggest looking elsewhere :)

**Comment by fabpot** [comment]
Indeed, that's not going to change. I don't necessarily disagree with your point of view, but each framework has its own purpose, goals, and usages. Symfony is in fact much more in line with what you are looking for. Silex is not.

**Comment by mivanov93** [comment]
I see what you mean, but sometimes you can have your cake and eat it too. Of course it is unthinkable to break compatibility, but introducing features is not necessarily about that. Then again, perhaps the goals of Silex are to be simple as possible which is a self implied limitation.

**Comment by stof** [comment]
@mivanov93 when using controllers as services, you can inject what you want in the controller. And you should probably not be injecting the app itself

**Comment by mivanov93** [comment]
That maybe so, but by doing things in this way, we have to separate the routing from the controller. Basically having a controller, separate routing and separate mapping for the controller. Plus we can't have autoresolve or anything, just doing a
```
$app['posts.controller'] = $app->share(function() use ($app) {
    return new PostController($app['posts.repository']);
});
```
While it seems more intuitive to define routes inside the controller class itself, so we can just map the Controller later.
Ex.
PostController - /getPost /newPost /deletePost
Then we map(mount) PostController to /stuff
So we get /stuff/getPost,..

But to do that, we need to use the ctrl.factory to create a new object per Controller, later mounting said objects. But we don't want to create a controller if it's not needed for a certain route, so that mounting function becomes static or we have to make two classes per ctrl, one for it's function, the other for routing it. Doesn't it sound more intuitive to have the inside routes inside the controllers, since they are connected to their internal implementations anyway?
