### ISSUE TITLE
Silex Truck Factor

### ISSUE THREAD

**Issue by gavelino** [silexphp/Silex#1212]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Silex** and obtained a value of **1**.

The developer responsible for this TF is:

Fabien Potencier - author of 75% of the files 

To validate our results, we would like to ask **Silex** developers the following three brief questions:

(a) Do you agree that the listed developer is the main developer of **Silex**?

(b) Do you agree that **Silex** will be in trouble if the listed developer leave the project (e.g., if he wins in the lottery, to be less morbid)?

(c) Does **Silex** have some characteristics that would attenuate the loss of the listed developer (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by fabpot** [comment]
No, I don't think that there are any problems. As for many other Open-Source project, there is one leader and many contributors. And silex is no different.

**Comment by SpacePossum** [comment]
> (a) Do you agree that the listed developer is the main developer of Silex?

Yes.

> (b) Do you agree that Silex will be in trouble if the listed developer leave the project

No, I think others could take over (for example Stof and Igor, maybe others) 

>  (e.g., if he wins in the lottery, to be less morbid)?

I think if he wins, he would probably invest it into his company so we would be even better of ;) (but I get the point).

>(c) Does Silex have some characteristics that would attenuate the loss of the listed developer (e.g., detailed documentation)?

No, I think fabpot is very open about the project and the ideas about it are well documented.

About the paper, interesting read :)
I wonder however how the calculation is done for some projects (Silex and PHP-CS-Fixer for example);
that score pretty low numbers (1 and 2). Are you sure this not the result of how the project owners merge the PR's or weight the initial commit pretty heavy?
(out of curiosity, why isn't Symfony in there? :) )

**Comment by stof** [comment]
> No, I think others could take over (for example Stof and Igor, maybe others)

The main issue would be to take ownership on the github organization if he gets hit by a truck (if he wins lottery, he can take the time to transfer ownership of the org before leaving)

**Comment by SpacePossum** [comment]
@stof fair point. I only replied on the scoped down question about Silex itself. But yes, of course we would have way bigger problems then Silex being without a owner alone.

**Comment by gavelino** [comment]
Thank you for the comments.
