### ISSUE TITLE
SecurityServiceProvider use CallbackResolver

### ISSUE THREAD

**Issue by henrikbjorn** [silexphp/Silex#1216]
Currently when using the SecurityServiceProvider and defined the `users` options it can be a closure, but because i dump my config and would like to have all that in a seperate json file. I propose we use the CallbackResolver and checks if it is a Closure when building the service for the firewall.

ref: https://github.com/flint/tacker/issues/8

**Comment by ragboyjr** [comment]
@henrikbjorn do you want to close this or submit something another PR for this?

**Comment by hkdobrev** [comment]
I've cherry-picked @henrikbjorn commits from #1217 and revived his implementation on top of latest master in #1611.
