### ISSUE TITLE
Upgrade pimple dependency

### ISSUE THREAD

**Issue by dipthegeezer** [silexphp/Silex#1218]
Is it possible to use a latter or at least newer version of pimple? Currently silex is fixed to ~1.0 releases.

I'm getting conflicts with composer when trying to insatll packages that use newer versions of pimple.

Thanks

**Comment by henrikbjorn** [comment]
In the 1.x branch it is not possible because of the rename of the Pimple container class.
When Silex 2.x is released it will be possible.

**Comment by fabpot** [comment]
Moreover, Pimple 2 and 3 are not BC.

**Comment by patrick-fls** [comment]
Is there a rough ETA for a 2.x tag?
