### ISSUE TITLE
PSR-7

### ISSUE THREAD

**Issue by server-may-cry** [silexphp/Silex#1228]
How about add psr-7 compatibility?
https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-7-http-message.md

**Comment by Kilte** [comment]
You can use [psr-http-message-bridge](https://github.com/symfony/psr-http-message-bridge).

**Comment by Kilte** [comment]
But for PSR-7 responses it's necessary to add an [event listener](https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/master/EventListener/PsrResponseListener.php) for example.

**Comment by fabpot** [comment]
This is not related to Silex, but Symfony as Silex is just a layer on top of the Symfony components.
