### ISSUE TITLE
Exception not handled for EventListener on boot.

### ISSUE THREAD

**Issue by henrikbjorn** [silexphp/Silex#1229]
In 1.x it is very common to extend the dispatcher and add our own listeners, but if a Listener requires a dependency and that dependency throws an exception, it will not be handled.

An example.

We add a `HostToDaoListener`, this listener requires `db` in it constructor, except the `db` service cannot connect to the database and so it throws an exception.

This exceptions is just dumped to the screen, would have assumed the exception_handler would have intercepted it, and shown the pretty screen.

Should we wrap the boot process in a try/catch block? And call the exception handler?

**Comment by henrikbjorn** [comment]
The same issue is present if i use SecurityServiceProvider and a custom `users` provider that requires a database connection, and that database is down, then ill get a whitepage (on prod because of php settings) and the ugly uncaught exception directly from php.

I cant see a way to fix this easily, as that would require using `finishRequest` and `handleException` on `HttpKernel` which is private.

**Comment by henrikbjorn** [comment]
Currently i am doing this in my Application

``` php
<?php

class Application extends \Flint\Application {
    public function handle(Request $request, $type = HttpKernelInterface::MASTER_REQUEST, $catch = true)
    {
        if (!$catch) {
            return parent::handle($request, $type, $catch);
        }

        // We are starting the request, but boot might fail, so we have to do something
        // similiar to `HttpKernel::handleException` in order to provide a good user
        // experience. More information at:
        //
        //     https://github.com/silexphp/Silex/issues/1229
        try {
            parent::handle($request, $type, $catch);
        } catch (\Exception $e) {
            $method = new \ReflectionMethod($this['kernel'], 'handleException');
            $method->setAccessible(true);

            return $method->invoke($this['kernel'], $e, $request, $type);
        }
    }
}
```

**Comment by fabpot** [comment]
I don't think this can be included in Silex. For the `handleException` to work correctly, the exception listeners must be registered, but wrapping the `boot()` method with it means that we don't know where the exception is thrown.

The best thing to do is to register an error/exception handler early on (as done in Symfony).

**Comment by henrikbjorn** [comment]
Thats okay, just think we need to think about this.

Actually i would assume the core services is wired correctly, and therefor the handler/listener is setup correctly to handle an exception happening in the boot method.

**Comment by fabpot** [comment]
Closing as assuming that everything is correct is probably not good enough.
