### ISSUE TITLE
Validator translations are no longer loaded correctly

### ISSUE THREAD

**Issue by vilius-g** [silexphp/Silex#1241]

**Comment by stof** [comment]
which version of silex and of Symfony Validator are you using ?

**Comment by vilius-g** [comment]
I'm using v1.3.2 with this Provider initialization:

```
$app->register(new Provider\ValidatorServiceProvider());
$app->register(new Provider\FormServiceProvider());
$app->register(new Provider\TranslationServiceProvider(), ['locale' => 'lt']);
```

And it worked fine until v1.3.1. After upgrading, it displays all validation messages in English.

I think the error was introduced in dd270386ff9e9ed4d76efae3413d2f63af5d27e5 because it changed the translation loading order. The problem is that `$app['translator']` is usually loaded before `$app['validator']`, therefore modyfing `$app['translator.resources']` does nothing because they were already used.

If I change this to old code, everything works as before:
```
$app['translator']->addResource('xliff', $file, $app['locale'], 'validators');
```

**Comment by stof** [comment]
hmm, extending the translator.resources might indeed happen too late

**Comment by fabpot** [comment]
#1254 should fix this issue.
