### ISSUE TITLE
New version of silex

### ISSUE THREAD

**Issue by silverpark** [silexphp/Silex#1246]
Hi,

It is possible to create an LTS branch of "dev-master" for exemple 1.4.0 or 2.0.0 ?

I need a stable branch from dev-master.

Regards,

**Comment by GromNaN** [comment]
Using composer, you can specify `"silex/silex": "2.0.*@dev"`. This is an [alias form `dev-master`](https://github.com/silexphp/Silex/blob/master/composer.json#L68-L70).

**Comment by silverpark** [comment]
Yes but it is not a stable branch about dev-master for a production, if I am not mistaken.

**Comment by fabpot** [comment]
Master is not stable yet, that's correct and there is no notion of a LTS for Silex either.

I've done a lot of work on Silex 2.0 in the last past weeks, but I will only release it when it's finished, not before.

**Comment by silverpark** [comment]
Thank you fabpot
