### ISSUE TITLE
SwiftmailerServiceProvider disable delivery for dev env

### ISSUE THREAD

**Issue by pedrofs** [silexphp/Silex#1258]
Hi,

I couldn't find a way to do that. Have you ever thought about this option?

It should be simple to implement using the Swift_Transport_NullTransport for the transport object.

Best.

**Comment by henrikbjorn** [comment]
Hey @pedrofs 

In your application you can overwrote the `swiftmailer.transport` service when debug is on.

https://github.com/silexphp/Silex/blob/1.3/src/Silex/Provider/SwiftmailerServiceProvider.php#L46

**Comment by hkdobrev** [comment]
If you want to completely disable it on dev, use the null transport, but you could also use this filtering plugin to whitelist/blacklist certain domains and base the options the environment - https://github.com/OpenBuildings/swiftmailer-filter

**Comment by pedrofs** [comment]
I will go on using the null transport.

Thank you!
