### ISSUE TITLE
Support the new Symfony Guard component

### ISSUE THREAD

**Issue by fabpot** [silexphp/Silex#1260]

**Comment by henrikbjorn** [comment]
Is there any reference docs for Symfony on this?

**Comment by andytruong** [comment]
I think it's https://github.com/symfony/symfony/pull/14673

**Comment by ChrisRiddell** [comment]
Will this be part of Silex 2?

**Comment by fabpot** [comment]
If someone wants to work on it. I won't have time in the next few weeks.

**Comment by mathroc** [comment]
Could it come in Silex 2.1 instead of waiting for it for 2.0?
