### ISSUE TITLE
2.0-dev I $app["variable"] not accesible in twig

### ISSUE THREAD

**Issue by misilot** [silexphp/Silex#1261]
Hi,

I am using the 2.0-dev branch right now and when I try and assign $app["user"] = array(...) the variable is not accessible in twig?

I am defing this as a route middleware in controllers.php and when trying to access the variable app.user I get the following error

```
Twig_Error_Runtime in Template.php line 182: 
An exception has been thrown during the rendering of a template ("The "app.user" variable is not available.") in "staff/officesupply/home.html.twig" at line 15.
```

line 15 has: {{ dump(app.user) }}

Thank you

**Comment by misilot** [comment]
I updated to latest commit it it seems to be working now.

**Comment by henrikbjorn** [comment]
You shouldnt use `app` in twig templates, do an extension instead or add it globally yourself :)

**Comment by misilot** [comment]
@henrikbjorn how would I add it globally myself?

**Comment by henrikbjorn** [comment]
Read the twig documentation.
