### ISSUE TITLE
Deny access for the same URI

### ISSUE THREAD

**Issue by silverpark** [silexphp/Silex#1264]
Hi,

I've a problem about an exemple of authentication, it's not possible to reject a user for a specific route without stop my application. I detail :

In the route I do :
```
$app->mount('/', new \Api\Toto\Provider\TotoControllerProvider());
$app->mount('/', new \Api\Tata\Provider\TataControllerProvider());
```

TotoControllerProvider I do :
```
class TotoControllerProvider extends AuthControllerProvider {
    $oController->post('/test', 'Api\Toto\Controller\TotoController::postAction');
}
```

TataControllerProvider I do :
```
class TataControllerProvider extends AuthControllerProvider {
    $oController->post('/test', 'Api\Tata\Controller\TataController::postAction');
}
```

AuthControllerProvider I do :
```
public function connect(Application $oApp)
{
        $oControllers = $oApp['controllers_factory'];
        
        $oControllers->before(function (Request $oRequest, Application $oApp) {
            $oHeaderIdentifier = $oRequest->headers->get('auth-identity', null);
            if (!$this->isAllowed($oHeaderIdentifier)) {
                return Response('failed');
            }
            
            return null;
        });

        return $oControllers;
}
```

If a user ``Tata`` is allowed to access in ``TataController`` he is rejected by ``TotoController`` cause of ``return Response('failed');``

And if user ``Toto`` is allowed to access in ``TotoController`` he is reject by ``TataController`` cause of ``return Response('failed');``

Is it possible to deny access to the controller without stopping API ?

Thank you in advance.

**Comment by mTorres** [comment]
Can you elaborate on *```Is it possible to deny access to the controller without stopping API ?```*?

**Comment by silverpark** [comment]
Yes of course.

I would like ``unmount`` a group of controller when a ``before`` return ``Response('failed')`` for exemple because return a response freeze my application.

Do you understand ?

**Comment by mTorres** [comment]
I think I understand but I fail to see your use case, sorry. Can you explain what is what you are trying to achieve without explaining how are you trying to do it? It seems to me that you are overcomplicating things...

**Comment by nbpalomino** [comment]
@silverpark Maybe a more deep read about Middlewares can help you.

http://silex.sensiolabs.org/doc/middlewares.html#finish-middleware

**Comment by silverpark** [comment]
Great ! 

I did not think about that.

Thanks
