### ISSUE TITLE
Message exception error visible in production environment

### ISSUE THREAD

**Issue by silverpark** [silexphp/Silex#1270]
Hi,

With an environment production, I have a message by default however I have debug at false :
```
Sorry, the page you are looking for could not be found.
```

This message is show uniquely when no routing are defined.

How to override this handle exception of silex ?

**Comment by stof** [comment]
Well, just register an error handler displaying the page you want: http://silex.sensiolabs.org/doc/usage.html#error-handlers

**Comment by silverpark** [comment]
Yes I have use that but it doesn't work.

**Comment by mTorres** [comment]
Are you using 1.3 or 2.0 (master)? This should work in 1.3 as stated in docs, but for 2.0 the signature of the error function changed. See [how the Silex Skeleton defines it](https://github.com/silexphp/Silex-Skeleton/blob/master/src/controllers.php#L17)

**Comment by SpacePossum** [comment]
>But it doesn't work with error internal 500

Make sure the error/exception is not raised/thrown before the error handler is registered and is not within the error handler itself.

**Comment by ragboyjr** [comment]
@silverpark, are you still experiencing this issue? Can we close this?

**Comment by ragboyjr** [comment]
@silverpark, where are you at with this?
