### ISSUE TITLE
security.access_rules not taken into account through service provider registration

### ISSUE THREAD

**Issue by davidloubere** [silexphp/Silex#1273]
If you set access rules using the SecurityServiceProvider registration, none of them is taken into account:
```php
$app->register(new Silex\Provider\SecurityServiceProvider(), array(
            'security.firewalls' => array(
                // ...
            ),
            'security.access_rules' => array(
                array('/list', 'ROLE_USER'), // will not be registered
            )
        ));
```
The `foreach` loop on line 325 of the provider seems useless since `$app['security.access_rules']` is initialized as an empty array on line 75.
Did I miss something?

**Comment by davidloubere** [comment]
Using the service provider registration works as expected actually. I can't figure out why it wasn't when I did my test. Perhaps something to do with the configuration service provider `Igorw\Silex\ConfigServiceProvider`.

Anyway. I close the issue.
Sorry for inconvenience.

**Comment by martiis** [comment]
I've found out that `$app['security.access_rules']` is being initialised again in [SecurityServiceProvder](https://github.com/silexphp/Silex/blob/c5fabd1217d6492a3783e134b6857c41e8374666/src/Silex/Provider/SecurityServiceProvider.php#L75) and later when access map is being built it sees an empty array... Should that line be there??

**Comment by stof** [comment]
it is not initialized *again*. This is the default value, and your own config is expected to be defined after registering the SecurityServiceProvider, like for any silex provider (which is the case when passing the config inside ``->register()``.

I'm quite sure your issue is that you haven't read the ConfigServiceProvider readme until the end: https://github.com/igorw/ConfigServiceProvider#register-order

> Make sure you register ConfigServiceProvider last with your application. If you do not do this, the default values of other Providers will override your configuration.

**Comment by martiis** [comment]
Yeah, my bad.. thanks.
