### ISSUE TITLE
How to solve circular deps with event subscriber/dispatcher

### ISSUE THREAD

**Issue by EdwardIII** [silexphp/Silex#1274]
This is probably more me being daft rather than a bug, but if I try to:

1. Inject a subscriber
2. That depends on a service
2. That itself depends on the dispatcher

I end up with what I think is a circular ref issue:

https://gist.github.com/EdwardIII/9ecc9fdb00f0822349ad

I don't *think* this happens in Symfony so is there a way I can make ->extend play nice?

**Comment by henrikbjorn** [comment]
Maybe in silex 2.0 you can do it in the dedicated `subscribe()` method on a service provider. But currently you have to do it in a `boot()` method or similiar.

**Comment by EdwardIII** [comment]
@henrikbjorn That's great, ```subscribe()``` on 2.0 works perfectly. 

I've updated the README in my test project, I'll try to pop a blog post up somewhere:

https://gist.github.com/EdwardIII/9ecc9fdb00f0822349ad#solution

Thanks!
