### ISSUE TITLE
Pimple 1.0 Requirement

### ISSUE THREAD

**Issue by realtruckjoshdeltener** [silexphp/Silex#1275]
Currently, this requires a Pimple 1.*, thus blocking many other up-to-date packages from being installed that rely on Pimple 2 or 3.  If no code changes are needed, please update the packagist, otherwise I would really appreciate the tweak!

**Comment by henrikbjorn** [comment]
It will change in Silex 2.0 where Pimple 3 is required.

Pimple changed it way of registering services eg. `share` is implicit and therefor you cannot just use a newer Pimple version with Silex 1.x
