### ISSUE TITLE
SecurityServiceProvider login and check paths don't work with locales

### ISSUE THREAD

**Issue by enyosolutions** [silexphp/Silex#1276]
Hello,

i'm trying to set up a silex authentication routes. However it seems like it doesn't work with locales var included in the url as such : 
```
        'form' => array(
            'login_path' => '/{_locale}/user/login',
            'check_path' =>'/{_locale}/user/login_check',
            'always_use_default_target_path' => true,
            'default_target_path' => '/{_locale}'
        ),
````

Is it by design or it's a bug ?

**Comment by guigzz** [comment]
Hello,

Still searching a way to mix Silex login page with locales too...

**Comment by enyosolutions** [comment]
hello @guigzz 

So after searching for a while, it looks like the only way you can have a locale in your login routes is by saving the locale in session. 
In your initialisation file 
```
if ($app['session']->has('locale')) {
    $app['locale'] = $app['session']->get('locale');
}
else{
$app['session']->set('locale', $app['locale']);
}
```

Then you can do this :+1: 

```
'login_path' => '/' . ($app['session']->has("locale")  ? $app['session']->get("locale") : 'en') . '/user/login',
```


 if your locale is detected from the route eg. `/fr/somepage`
You also need to set the locale in the session, using a before middle ware, because the routing is the last action that happens in the initialization, and it changes the value stored in $app['locale'].
```
$app->before(function () use ($app) {
$app['session']->set('locale', $app['locale']);
}

```

**Comment by guigzz** [comment]
Hello @enyosolutions,

Thanks for this pretty good workaround, not a hundred percent what I was looking for but still the better solution I've seen so far!

I'll use this until I find some time to think about another solution, thank you again!

**Comment by enyosolutions** [comment]
U welcome, let me know if you find a better way.

**Comment by stof** [comment]
The Symfony system accepts paths and route names (assuming that the route does not have mandatory placeholders except the magical ones like ``_locale``). It does not support ``/{_locale}/user/login``.

Note that using route names requires to register the UrlGeneratorServiceProvider (otherwise Silex is not able to generate urls for a route).

**Comment by ragboyjr** [comment]
@enyosolutions So can we close this?

**Comment by enyosolutions** [comment]
imho yes !.
