### ISSUE TITLE
Support for Pimple 2+

### ISSUE THREAD

**Issue by aik099** [silexphp/Silex#1281]
I'm trying to use Silex with another library, that needs Pimple 2 or 3. Since Silex needs Pimple 1 I can't install Silex at all.

Any idea on fixing this?

**Comment by jdreesen** [comment]
Use `v2.0.x-dev` (the `master` branch), it uses Pimple 3. 
Silex 1 won't be compatible with Pimple 2+ because of the API changes.

**Comment by aik099** [comment]
That is impossible as well, because the `master` branch requires PHP 5.5+ and I have PHP 5.4. Not sure which PHP version the users of app I'm trying to create will have.

For now I try to remove dependency from Pimple on the other library I'm trying to use to make Silex happy.

**Comment by jdreesen** [comment]
Well, you should update your PHP because PHP 5.4 reached end of life 2 month ago.

**Comment by aik099** [comment]
Yeah, I know. Unfortunately I have no idea what PHP versions people use on their development machines and that's why I keep PHP version requirements to the minimum to reach broader developer audience.

**Comment by futurevision** [comment]
Any serious developer should not use an EOL version of PHP so simply ignore the audience that is not updating and require 5.5+. Lots of libraries require it too and relying on outdated packages is a huge security risk.

**Comment by henrikbjorn** [comment]
@aik099 we cannot support Pimple 2/3 in Silex 1.x because of changes in how shared services are defined. Shared services is the new default. Also ServiceProvider interface is different and requires Pimple\ServiceProviderInterface.

**Comment by fabpot** [comment]
Closing as the whole point of Silex 2 is to support Pimple 2/3. And as said by @henrikbjorn, there is no way to support both Pimple 1 and Pimple 2/3 in the same code base.

**Comment by caseycs** [comment]
I have a hack for this. Try specific commit, and exactly #bce2a5dc5931411ce319ebb470b1f4132cfddf08.

So it will be
```
  "silex/silex": "dev-master#bce2a5dc5931411ce319ebb470b1f4132cfddf08",
```

in your `composer.lock`. Probably does not work completely correct, but for the basic usage - it's perfect.

**Comment by silverpark** [comment]
@fabpot Silex3 qui utilisera Pimple3 est prévu pour quand ?

**Comment by mathroc** [comment]
@silverpark Silex 2 already supports Pimple 3 and is not out yet. I'm not sure there is any plan for Silex 3 yet (Silex 2 has yet to be released)

**Comment by silverpark** [comment]
Yes but silex don't use pimple3, exemple : 
```
class Application extends \Pimple
```

The best way I think is use pimple3 for exemple : 
```
public function register(Application $app)
```
to
```
use Pimple\ServiceProviderInterface;

public function register(ServiceProviderInterface $app)
```

And we can use ``ServiceProviderInterface`` of Pimple3 and not Silex.

More, the service provider can be use for other framework who implements register idea from silex.

**Comment by silverpark** [comment]
A concrete example, I have create a project with component symfony console, but I would like use the dependency injection with pimple3 in the case of implements silex in the futur in my project.

I have create a project wrapper symfony console for set the container pimple in all command, look this : https://github.com/silverpark/WrapperPimpleSymfony2Console

**Comment by henrikbjorn** [comment]
@silverpark you have to wait for Silex 2.0

**Comment by silverpark** [comment]
Ok, when ?

**Comment by henrikbjorn** [comment]
Only Fabien knows.
