### ISSUE TITLE
Routing, trailing slashes and optional parameters

### ISSUE THREAD

**Issue by Jeto143** [silexphp/Silex#1287]
So, this:

```
$app->get('/foo', function() {
	return 'hello';
});
```
matches */foo* but not */foo/*. Alright.

Now this:
```
$app->get('/foo/', function() {
	return 'hello';
});
```
matches both */foo* and */foo/*. OK.

So why would this:
```
$app->get('/foo/{bar}/', function() {
	return 'hello';
});
```
match */foo* but not */foo/*?

There's a way to make the latter match with ->value('bar', '')->assert('bar', '.*') but that seems pretty ugly. And if {bar} uses a converter, it doesn't work either anyway.

This doesn't make much sense to me.

**Comment by SpacePossum** [comment]
Hi,
You might want to check out this issue https://github.com/silexphp/Silex/issues/149 for some more information/background/discussion.

**Comment by sonkengmaldini15** [comment]
Yes of course look at the preview issue mentionned by @spacePssumm

**Comment by jtouati-keyyo** [comment]
Yeah I read most of #149, however I wanted to focus on the specific issue of the optional parameters and their implications.

Feel free to close this if you feel like it's a duplicate. I'll post in the other one then.

**Comment by Jeto143** [comment]
Yeah I read most of #149, however I wanted to focus on the specific issue of the optional parameters and their implications.

Feel free to close this if you feel like it's a duplicate. I'll post in the other one then.

**Comment by ragboyjr** [comment]
It looks like we can close this issue considering the changes that will hopefully/possibly be made in #149

**Comment by ragboyjr** [comment]
@Jeto143 can you close this?

**Comment by Jeto143** [comment]
Sure.

**Comment by ragboyjr** [comment]
awesome, thanks man!
