### ISSUE TITLE
BrowserKit not available on clean Silex installation

### ISSUE THREAD

**Issue by jnardiello** [silexphp/Silex#1293]
Hi all,
this afternoon while bootstrapping a new project I've started writing acceptace/functional test cases and got this error: `PHP Fatal error:  Class 'Symfony\Component\BrowserKit\Client' not found in /root/projects/opengrid/vendor/symfony/http-kernel/Client.php on line 30`

I've started to dive deep into the issue and the only way I managed to get it sorted is by manually requiring `"symfony/browser-kit": "~2.7|3.0.*"` as a `require` dependency in my `compose.json`. 

It seems that out of the box it's impossible to write functional test cases (and use `WebTestCase`) for Silex. `browser-kit` is listed as a dev dependency for Silex, could this be the issue? If that's the case, isn't more appropriate to list it in `require` rather than `require-dev` as it is required to write production test cases for anyone using Silex?

**Comment by stof** [comment]
Well, you can use other tools than BrowserKit to write your tests depending on your preference (even if the example shown in the doc describe the BrowserKit usage). This is why it is not set as a required dependency. This is the same reason that twig is not a required dependency: even though there is a builtin integration for Twig, you are free not to use it and use a different tool instead.

Btw, the documentation page about the WebTestCase mentions this need: http://silex.sensiolabs.org/doc/testing.html#webtestcase

**Comment by jnardiello** [comment]
My bad for missing the highlight from the docs. That would have saved me some time :)

Other than that, it's true that you might want to use something different from BrowserKit but I still think that it should be part of silex given how tight `WebTestCase` is with it. If I decide to use `PHPSpec` for example, I do expect to include whatever additional package to make my test run. On contrary, I would not expect to include something to use the base test class shipped with the project.

Clearly, this is just my take on it and I hope it helps.
