### ISSUE TITLE
view handler does not trigger for scalar values

### ISSUE THREAD

**Issue by ghost8472** [silexphp/Silex#1297]
When my controller returns a scalar value (such as a boolean, number, or string), the view controller is not getting triggered.  This seems wrong to me, as the usage page says:

http://silex.sensiolabs.org/doc/usage.html#view-handlers
>View Handlers allow you to intercept a controller result that is *not a Response* and transform it before it gets returned to the kernel.

It's working fine for associative arrays, which is what I do tend to use most often.  80% of my controllers were working fine, so I hadn't noticed that my newly added view logic wasn't running on the other controllers until just now.  For now, I converted those to return associative arrays too, which does read better anyway.  So, if this isn't a bug, or doesn't get fixed, then I'm fine anyway.

If it isn't a bug, please change the wording on the usage page though.

**Comment by stof** [comment]
there is a listener converting scalars to a Response with this scalar as body already. This might be the reason why view handlers are not running, depending on the priorities.

**Comment by ghost8472** [comment]
@stof where can I find this listener and silence it?

The only $app->view in our code is the one I wrote, so if there is another view running, it must be part of the framework.  I have the "vendor" folder hidden from my usual greps, but even searching it now I didn't find any other $app->view calls (other than in the usage doc, and in the tests directory, which I assume I can ignore).

**Comment by ragboyjr** [comment]
The issue might this https://github.com/silexphp/Silex/blob/1.3/src/Silex/ViewListenerWrapper.php#L68. It checks if the view wrapper expects an object, array, or callable.

The easiest solution would be to not use the `$app->view` method, and instead use `$app->on(KernelEvents::VIEW, function($ev) {});`

And then follow the documentation here: http://symfony.com/doc/current/reference/events.html#kernel-view.

Here is also an example of a custom view handler that I wrote for my own applications: https://gitlab.bighead.net/krak/api/blob/master/src/EventListener/ApiResponseListener.php

**Comment by ragboyjr** [comment]
@ghost8472, does that sufficiently answer your question? can we close this?

**Comment by ghost8472** [comment]
We did implement a workaround quite a while ago, so I am no longer affected
by this flaw in the base code.  Whether you want to address it better for
other users is up to you.  We've had to rebuild this view handling, error
handling, and basic auth.  I feel your framework isn't providing any
functionality of its own, as we have to rebuild so much to get around your
bugs.

William Baker
Ether Tear LLC
1 (855) 790-8472
cell (575) 640-5861

**Comment by ragboyjr** [comment]
@ghost8472 

Actually, I just tested on silex 1.3

```php
$app->view(function($res) {
    if (is_bool($res)) {
        return 'converted: ' . strval($res);
    }

    return $res;
}, 0);

$app->get('/test', function() {
    return true;
});
```
And this actually worked fine.

**Comment by ragboyjr** [comment]
I don't think there is a bug, so we can close this.
