### ISSUE TITLE
Web-profiler 

### ISSUE THREAD

**Issue by sonkengmaldini15** [silexphp/Silex#1298]
Hi,
Not understanding where the error is coming when tring to embed web-profiler. 
Here is the error message :
```InvalidArgumentException in Pimple.php line 78: Identifier "security.authentication_providers" is not defined.````

And here is my code : 
`````php 
$app->register(new Silex\Provider\ServiceControllerServiceProvider());
if (isset($app['debug']) && $app['debug']) {
    $app->register(new Silex\Provider\HttpFragmentServiceProvider());
    $app->register(new Silex\Provider\WebProfilerServiceProvider(), array(
        'profiler.cache_dir' => __DIR__.'/../var/cache/profiler'
    ));

**Comment by stof** [comment]
issues with the WebProfiler integration should be reported to the repo containing the webprofiler integration: https://github.com/silexphp/Silex-WebProfiler

**Comment by sonkengmaldini15** [comment]
Ha ok !
