### ISSUE TITLE
Logic for flushing/freezing routes can't be extended

### ISSUE THREAD

**Issue by aeoris** [silexphp/Silex#1301]
As stated on b510e5a0, on 1.2.x it used to be possible to customize the logic behind freezing and flushing routes overriding the `flush` method from `ControllerCollection`. My (maybe rather specific?) use case for this was to prepend a fixed prefix to routes contained on a controller collection.

For instance, I would have a `VersionedServicesControllerCollection` that prepends all its routes with `/v{_version}/`.

ControllerProvider:

```php
class MyExampleController implements ControllerProviderInterface
{
    public function connect(Application $app)
    {
        $routes = $app['versioned_service_controller_factory'];

        $routes->match('bar', '...');

        return $routes;
    }
}
```

index.php:

```php
$app = new Application;

$app->mount('/foo/', new MyExampleController);
```

That would create (and indeed in 1.2 did) a route accessible with the path `/v1/foo/bar`. Is this behaviour achievable in some way with the current implementation? If not, changing `doFlush` visibility to `protected` would be enough for that.

**Comment by stof** [comment]
Well, why not passing this prefix when mounting ?

**Comment by aeoris** [comment]
@stof I want to keep it relative to the collection, not the mount point, to avoid people adding mounts to forget the prefix (which is configurable for the controller collection type).

**Comment by stof** [comment]
But you are still putting the version prefix before the mount prefix, which looks weird then (because the mounting code would expect to find the provided routes mounted under ``/foo/``, not under ``/v1/foo/``). you are breaking the semantic of the mount prefix here.

**Comment by aeoris** [comment]
@stof I don't quite get you. It does not look weird for my business requirements at least. Which mounting code would expect to find the routes where? I want to be able to combine mounting "standard" controller collections (ie: no auto-prefixer) and custom ones that prepend a string automatically. I can't extend Application for that, as this behaviour would be applied globally.

**Comment by stof** [comment]
If the v1 prefix is meant to be added after the mounting prefix, this can be achieved using the public API only:

```
class MyExampleController implements ControllerProviderInterface
{
    public function connect(Application $app)
    {
        $routes = $app['controller_factory'];

        $routes->match('bar', '...');

        $versionedRoutes =  $app['controller_factory'];

        $versionedRoutes->mount('/v1', $routes);

        return $versionedRoutes;
    }
}
```

@aeoris the issue is that your own expectation breaks the behavior of ``mount``, where mounting a collection prefixes it with the given prefix. You are expecting to put the prefix in the middle of the path (which is not a prefix anymore).
Providing an extension point in Silex which would allow to break the expected behavior of a method is a bad idea (your class implemented for Silex 1.2 breaks the rules of OOP inheritance as your class changes the meaning of the argument, which is not a prefix anymore)

**Comment by aeoris** [comment]
@stof thanks for the example, I didn't thought about that way. To be honest I do know that I'm breaking some principles there, but I wanted to avoid possible mistakes and the 1.2 solution did wonders for our specific requirements.

I'll close this issue then, thanks again!

**Comment by aeoris** [comment]
Just a clarify though: what I want to achieve is not a route like `foo/v1/bar` as your example suggests, but a route like `v1/foo/bar`.
