### ISSUE TITLE
Silex FormServiceProvider could not load type “form” when using Symfony 3 components

### ISSUE THREAD

**Issue by bestattendance** [silexphp/Silex#1302]
When trying to build a form I receive this error:

    InvalidArgumentException in FormRegistry.php line 87: Could not load type "form"

I've registered the FormServiceProvider, TranslationServicerProvider, and ValidatorServiceProvider.

Here is the relevant part of my code:

        $this->_form = $this->_app['form.factory']->createBuilder('form', $this->_map())
        ->add('firstName', 'text', [
            'constraints' => [new Assert\NotBlank()]
        ])
        ->add('lastName', 'text', [
            'constraints' => [new Assert\NotBlank()]
        ])
        ->add('email', 'text', [
            'constraints' => [new Assert\Email()]
        ])
        ->getForm();

Here are version numbers of the related components that I'm using:

silex/silex v1.3.5
symfony/security-core    v3.0.1
symfony/security-csrf v3.0.1
symfony/translation v3.0.1
symfong/twig-bridge v3.0.1
symfony/validator v3.0.1
symfony/form v3.0.1

Downgrading all symfony components to 2.8.1 solved the problem.

**Comment by bestattendance** [comment]
Ref: http://stackoverflow.com/questions/34663227/silex-formserviceprovider-could-not-load-type-form

**Comment by hellboy1975** [comment]
I can confirm this problem.  Downgrading the Symfony components was the only option I could find that worked.

**Comment by HeahDude** [comment]
This is not a `FormServiceProvider` issue.
It's about one of the few bc break introduced in version 3 of symfony components. You can get this working by changing the deprecated alias `text` by `TextType::class` :

```php
use Symfony\Component\Form\Extension\Core\Type\TextType;

$this->_form = $this->_app['form.factory']->createBuilder('form', $this->_map())
    ->add('firstName', 'TextType::class', [
        'constraints' => [new Assert\NotBlank()]
    ])
    ->add('lastName', 'TextType::class', [
        'constraints' => [new Assert\NotBlank()]
    ])
    ->add('email', 'TextType::class', [
        'constraints' => [new Assert\Email()]
    ])
    ->getForm();
```

**Comment by JonathanRamier** [comment]
Hello @HeahDude
 
You forgot to remove quote in your example 

```php
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

$this->_form = $this->_app['form.factory']
    ->createBuilder('FormType::class', $this->_map())
    ->add(
        'firstName', 
        TextType::class, [
            'constraints' => [new Assert\NotBlank()]
        ]
    )
    ->add(
        'lastName', 
        TextType::class, [
             'constraints' => [new Assert\NotBlank()]
        ]
     )
    ->add(
         'email', 
         EmailType::class, [
              'constraints' => [new Assert\Email()]
         ]
    )
    ->getForm();
```

see [doc](http://symfony.com/doc/current/book/forms.html#index-2)

**Comment by HeahDude** [comment]
You're right @JonathanRamier, I've mistaken after copy-pasting, thank you !
