### ISSUE TITLE
Attempting to route to /rmm gives "Sorry, the page you are looking for could not be found."

### ISSUE THREAD

**Issue by ABPTech** [silexphp/Silex#1303]
New to Silex, but able to get 1.3 up and running (Centos 6.5, Apache 2.2.15) and handling basic routing using the documentation's usage examples. I need to use a get route for the keyword "rmm". However, each time this is attempted, I get the "Sorry, the page you are looking for could not be found." error. I can change this from /rmm to basically anything else and it works just fine, but using the following simple example breaks:

<?php
require_once __DIR__.'/silex/vendor/autoload.php';

$app = new Silex\Application();

$app->get('/rmm', function () {
    return 'RMM Application Test';
});

$app->run();

**Comment by ABPTech** [comment]
Here is the debug info

[debug.txt](https://github.com/silexphp/Silex/files/86323/debug.txt)

**Comment by SpacePossum** [comment]
Hi,
Did you try the request with and without the trailing '/'? The debug info suggest it is looking for '/rmm/' and not '/rmm'

**Comment by ABPTech** [comment]
I was accessing it via /rmm and it would send to /rmm/. It made me think that maybe it thought it was an actual directory on the server. So I cleared my cache and it actually started behaving as expected. 

No idea why it thought it was an actual directory (nothing referring to rmm in .htaccess, no non-default directories in root). Guess I'll close this now though, the problem seems to have resolved itself :)
