### ISSUE TITLE
validateValue seems not be a valid method for ValidatorServiceProvider

### ISSUE THREAD

**Issue by cocodrino** [silexphp/Silex#1304]
Hi, I'm following the documentation but I'm getting an error with the validateValue method, seems not exist, this issue seems to be [related](https://github.com/silexphp/Silex/pull/1299) but it's not clear why it was closed when the error persist, I'm using the latest silex version and following this [code](http://silex.sensiolabs.org/doc/providers/validator.html)

**Comment by tburschka** [comment]
What you try to validate, a single value, an array or an object.... had the same problem today... Since i tried to validate an array i had to use the method "validate" instead of validateValue

**Comment by stof** [comment]
validateValue does not exist anymore if you use the Symfony 3 component, as it was deprecated since Symfony 2.5.
