### ISSUE TITLE
[Suggestion] use bcrypt by default as encoder

### ISSUE THREAD

**Issue by stof** [silexphp/Silex#1312]
Currently, the MessageDigestEncoder is used by default (with its default config). I suggest switching to Bcrypt in Silex 2 (This cannot be done in 1.3 as it would break existing apps relying on the default config)

**Comment by SpacePossum** [comment]
:+1:

**Comment by lschricke** [comment]
:+1:

**Comment by mvanbaak** [comment]
:+1:

**Comment by fabpot** [comment]
Anyone willing to work on that one? Should be easy enough.

**Comment by alcalyn** [comment]
`password_hash(): Use of the 'salt' option to password_hash is deprecated`

Yep, that break existing apps, but not only because the hash algorithm changes.
Providing a salt to `password_hash` is now deprecated since early released version 7.0.4 of PHP.

**Comment by stof** [comment]
@alcalyn just return ``null`` as salt for your user, instead of forcing the Symfony class to use your own salt.
and for an existing app, you can still configure the encoder explicitly to keep the old one
