### ISSUE TITLE
Pimple 3

### ISSUE THREAD

**Issue by lukaszwit** [silexphp/Silex#1313]
Hi,
I'm wondering if there is possibility to use Pimple 3 with Silex ~1.3 app? So far I didn't find anything that wouldn't be a hack

**Comment by mediamonks-robert** [comment]
No, this is not possible, please also look at these issues:

https://github.com/silexphp/Silex/issues/1281
https://github.com/silexphp/Silex/issues/1275

**Comment by lukaszwit** [comment]
Tx
