### ISSUE TITLE
How about to tag silex 2.0 without dev?

### ISSUE THREAD

**Issue by server-may-cry** [silexphp/Silex#1314]
Symfony 3.0 released. What are waiting for?

**Comment by ragboyjr** [comment]
:+1:

**Comment by Atriedes** [comment]
I think maintainer will wait until silex stable enough for 3.0. Some feature still waiting to be merged such as #1296

**Comment by ragboyjr** [comment]
Is there any way we can do a feature freeze to figure out what needs to be in 2.0 and what can come after? I'd love to see Silex 2.0 released and am willing to help out on any issues or PR's on getting it there.

**Comment by ragboyjr** [comment]
well, #1296 is closed now. I just went through most of the remaining issues querying statuses of the issues. A lot of the issues are old and seem like they can be closed, but we can wait until someone responds to those issues. Anyways, @fabpot or someone else who has authority in this matter, when exactly do you think we could see a silex 2.0 come out?

I have a project coming up soon, and I'd love to be able to use a stable 2.0 branch.

**Comment by mediamonks-robert** [comment]
Just use 2.0, I'm using it for tons of projects on production since it came out and never ran into issues that can not easily be resolved.

**Comment by ragboyjr** [comment]
@mediamonks-robert, 

@fabpot does a good job with making sure 2.0-dev stays more or less stable; however, there are plenty of legitimate reasons why you (I) shouldn't be using a non-stable branch of this framework for the project I'll be heading. Using a dev branch just wouldn't feasible for me. Also, considering that there aren't many open tickets or PR's, we should be getting close to a stable 2.0, so it doesn't hurt to try and wrap up what's needed to make it official.

**Comment by mediamonks-robert** [comment]
It can depend on the kind of project of course. I put my comment there to assure others Silex 2.0 is great for usage in production but feel free to choose the 1.3 stable branch if you feel better about it.

**Comment by ragboyjr** [comment]
@mediamonks-robert, ya no worries. I'd definitely prefer 2.0 for sure, especially since Pimple 3 is so much nicer than 1.0. @fabpot seems like he's on a silex marathon right now, so we'll see how close we are when he's done.

**Comment by fabpot** [comment]
Closing this now. The only remaining task is for me to figure out how to host both docs for 1.3 and 2.0 on the website. When it's done, I will release 2.0 stable. Thanks for your patience.

**Comment by ragboyjr** [comment]
yes! oh my goodness thank you!

**Comment by fabpot** [comment]
Website is updated now. If nobody finds anything to change in the docs or code in the next couple of days, I will tag 2.0.

**Comment by xmarcos** [comment]
@fabpot on http://silex.sensiolabs.org/doc/master/, the "API link" is broken http://silex.sensiolabs.org/api/index.html. 

It doesn't seem to be built from this file https://github.com/silexphp/Silex/blob/master/doc%2Findex.rst either.

**Comment by fabpot** [comment]
2.0 is out now (https://twitter.com/fabpot/status/732848312819318784). Thanks everyone for your patience and enjoy!
