### ISSUE TITLE
Problems using controllers with ServiceControllerServiceProvider

### ISSUE THREAD

**Issue by brsoftware** [silexphp/Silex#1319]
Hi,
I'm trying to use controllers, then I set the controller as a service:

`$app['test.controller'] = $app->share(function () {`
`            return new TestController;`
`        });`

Then, define the route:

`$api = $app["controllers_factory"];`
`$api->get('/test', "test.controller:test");`
`$app->mount($app["api.endpoint"].'/'.$app["api.version"], $api);`

When I try to access / test, I get the following error:

Catchable fatal error: Argument 2 passed to Symfony\Component\HttpKernel\Event\FilterControllerEvent::__construct() must be callable, array given, called in F:\fatarco-html5\server\vendor\symfony\http-kernel\HttpKernel.php on line 131 and defined in F:\fatarco-html5\server\vendor\symfony\http-kernel\Event\FilterControllerEvent.php on line 35

What am I doing wrong?

Thanks.

**Comment by RafalNiewinski** [comment]
I think you need change:
```php
$api->get('/test', "test.controller:test");
```
to
```php
$api->get('/test', "YourNamespacePath\TestController::test");
```

I am using this syntax but I do not know if it meets your expectations.

**Comment by mathroc** [comment]
@brsoftware does `TestController` have a `public test()` method ?

**Comment by johndodev** [comment]
Have you registered the service which allow to use controllers as service in route definition ? 

    $app->register(new Silex\Provider\ServiceControllerServiceProvider());

**Comment by ragboyjr** [comment]
@brsoftware are you still having an issue?

**Comment by ragboyjr** [comment]
@brsoftware any word on this?
