### ISSUE TITLE
Inject Application into param converter

### ISSUE THREAD

**Issue by felixfbecker** [silexphp/Silex#1321]
I need to inject the application object into a param converter because I need access to my database connection. However, currently only the param and the Request objects are passed, even when type-hinting:
```php
$router->convert('project', function ($id, Application $app) {
    return Project::findById($id, $app['db']);
});
```

**Comment by glaubinix** [comment]
You can pass the application via use to the converter function.

````php
$router->convert('project', function ($id) use ($app) {
    return Project::findById($id, $app['db']);
});
````

**Comment by felixfbecker** [comment]
@glaubinix Not if $app is not in the scope. I mean, you could make that argument for every occasion where it _is_ possible to inject `Application`. I am structuring my routes across multiple files by returning a `ControllerCollection` in each file. If it is the recommended way to depend on global variables like `$app`, then what is the point of having a DI container? I could just aswell use global `$db`, `$config` or singletons.

**Comment by felixfbecker** [comment]
I found this workaround, but it feels like a hack:
```php
$router->before(function (Request $request, Application $app) {
    if ($request->attributes->has('project')) {
        $request->attributes->set('project', Project::findById($request->attributes->get('project'), $app['db']));
    }
});
```

**Comment by felixfbecker** [comment]
Wouldn't injecting be much better for testing than globals? ;)

**Comment by glaubinix** [comment]
I don't think this is the recommended way. It's just the closest one to your sample code.

The recommended way to setup routes is to use the [ControllerProviderInterface](https://github.com/silexphp/Silex/blob/1.3/src/Silex/ControllerProviderInterface.php) and define your routes and converters in connect methods and mount your ControllerProviders.

Classes implementing the ControllerProviderInterface or ServiceProviderInterface should probably be the only places where you access ```$app```.

If you are not happy with the function, you could also create a converter class and use it like this.
$router->convert('project', $app['projectconverter']);

**Comment by felixfbecker** [comment]
@glaubinix But with `ControllerProviderInterface`, the nice express-like syntax gets exchanged for so much bloat. Suddenly I have a class for every single route with just a single method on it, `connect()`. Which in turn connects routes to closures or other controller classes. Why do I need a class for something that would only take one closure in theory?

**Comment by HeahDude** [comment]
@felixfbecker then in your case you should rely on `$app` being in the scope as the needed container.
The `use` is the way to go.

It's even recommended to create your controller collection from the `$app` :

```php
// controllers/blog.php
$blog = $app['controllers_factory'];

$blog->get('/', function ($param) {
    // ...
})
    ->convert('param', function ( ... ) use ($app) {
    //...
});

$app->mount('/blog', $blog);
```

see http://silex.sensiolabs.org/doc/organizing_controllers.html

**Comment by ragboyjr** [comment]
@felixfbecker, do you need anything else with this?

**Comment by felixfbecker** [comment]
@ragboyjr Shortly after this I discovered [PHP-DI](http://php-di.org/), which I find much nicer than Pimple. They provide a Silex Bridge that allows arbitrary injection into controllers and I implemented injection into middleware and param converters in https://github.com/PHP-DI/Silex-Bridge/pull/16. I have this in production now and am very satisfied with the solution :)

**Comment by fabpot** [comment]
Thanks for the feedback @felixfbecker
