### ISSUE TITLE
Form exception - Extension\Core\View\ChoiceView required, ChoiceList\View\ChoiceView given

### ISSUE THREAD

**Issue by WojciechJasinski** [silexphp/Silex#1323]
When using select (choice) field type I get the following error:

> Twig_Error_Runtime in Template.php line 182:
> An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Argument 1 passed to Symfony\Bridge\Twig\Extension\FormExtension::isSelectedChoice() must be an instance of Symfony\Component\Form\Extension\Core\View\ChoiceView, instance of Symfony\Component\Form\ChoiceList\View\ChoiceView given, called in C:\...\cache\twig\46\46819619523d60664cf2bfb5773ad26c7087ff603504dc928c29dfd18c8cb99c.php on line 355 and defined") in "form_div_layout.html.twig" at line 83.

Composer show -i:

> doctrine/annotations               v1.2.7             Docblock Annotations Parser
> doctrine/cache                     v1.6.0             Caching library offering an object-oriented API for many cache backends
> doctrine/collections               v1.3.0             Collections Abstraction library
> doctrine/common                    v2.6.1             Common Library for Doctrine projects
> doctrine/dbal                      v2.5.4             Database Abstraction Layer
> doctrine/inflector                 v1.1.0             Common String Manipulations with regard to casing and singular/plural rules.
> doctrine/instantiator              1.0.5              A small, lightweight utility to instantiate objects in PHP without invoking their constructors
> doctrine/lexer                     v1.0.1             Base library for a lexer that c
> silex/silex                        v1.3.5             The PHP micro-framework based on the Symfony Components
> symfony/browser-kit                v3.0.3             Symfony BrowserKit Component
> symfony/config                     v3.0.3             Symfony Config Component
> symfony/css-selector               v3.0.3             Symfony CssSelector Component
> symfony/debug                      v3.0.3             Symfony Debug Component
> symfony/dom-crawler                v3.0.3             Symfony DomCrawler Component
> symfony/event-dispatcher           v3.0.3             Symfony EventDispatcher Component
> symfony/filesystem                 v3.0.3             Symfony Filesystem Component
> symfony/form                       v3.0.3             Symfony Form Component
> symfony/http-foundation            v3.0.3             Symfony HttpFoundation Component
> symfony/http-kernel                v3.0.3             Symfony HttpKernel Component
> symfony/intl                       v3.0.3             A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
> symfony/options-resolver           v3.0.3             Symfony OptionsResolver Component
> symfony/polyfill-intl-icu          v1.1.1             Symfony polyfill for intl's ICU-related data and classes
> symfony/polyfill-mbstring          v1.1.1             Symfony polyfill for the Mbstring extension
> symfony/polyfill-php56             v1.1.1             Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
> symfony/polyfill-php70             v1.1.1             Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
> symfony/polyfill-util              v1.1.1             Symfony utilities for portability of PHP codes
> symfony/property-access            v3.0.3             Symfony PropertyAccess Component
> symfony/routing                    v3.0.3             Symfony Routing Component
> symfony/security-core              v3.0.3             Symfony Security Component - Core Library
> symfony/security-csrf              v3.0.3             Symfony Security Component - CSRF Library
> symfony/translation                v2.8.3             Symfony Translation Component
> symfony/twig-bridge                v2.8.3             Symfony Twig Bridge
> symfony/validator                  v3.0.3             Symfony Validator Component
> symfony/yaml                       v3.0.3             Symfony Yaml Component
> twig/twig                          v1.24.0            Twig, the flexible, fast, and secure template language for PHP

**Comment by HeahDude** [comment]
Hi, @WojciechJasinski, could you please try to upgrade your `symfony/twig-bridge` dependency to `v3.0.3` ?

**Comment by WojciechJasinski** [comment]
Works, great.
