### ISSUE TITLE
Can I use the controller type hinting for inject  custom types (classes)?

### ISSUE THREAD

**Issue by cocodrino** [silexphp/Silex#1325]
Hi, I know than I can inject Request, Application and many others  classes in my controller, but currently I wish make something like this

```php

function (Request $request, Silex\Application $app, Helpers $hlp, DB $db) 

```

where DB is a dummy class with static methods right now, but in the future would be something more complex and the DI would be a nice solution, hope you can understand my point, please let me know if you need some clarification, thank you!!.....

**Comment by mTorres** [comment]
In order to do that you should create your own ControllerResolver and the ```doGetArguments``` method which can detect [other parameter types](https://github.com/silexphp/Silex/blob/1.3/src/Silex/ControllerResolver.php#L40). Currently only *Request* and *Application* are detected.

Then you just need to overwrite the [resolver service in the container](https://github.com/silexphp/Silex/blob/1.3/src/Silex/Application.php#L122).

This issue should be closed as it's not related to Silex developement. Please, do not use the issue tracker to ask questions, the support forum is the [Silex Tag on Stackoverflow](http://stackoverflow.com/questions/tagged/silex).

**Comment by lukaszwit** [comment]
@mTorres you're right that this is not Stackoverflow but... let change this issue into feature request for some simple mechanism linke ParamConverters from symfony that allows things requested by cocodrino.

**Comment by stof** [comment]
@lukaszwit there is a feature in development in Symfony (see https://github.com/symfony/symfony/pull/18308) to allow hooking into the argument resolving in 3.1 (or 3.2 if it is not ready in time for 3.1, as the feature freeze is in a few days, but it should be OK), which will allow a better implementation than what SensioFrameworkExtraBundle does today for ParamConverter.
Once shipped in Symfony, the feature will be available in Silex (with some changes to allow configuring it of course)

**Comment by ragboyjr** [comment]
@cocodrino, also using controller's as services can help with this as well because you can setup the Controller via pimple with the needed dependencies.

What more do you want to do with this?

**Comment by cocodrino** [comment]
@ragboyjr thanks for the reply...can you provide me some example about that?..thank you!

**Comment by ragboyjr** [comment]
Ya for sure! I do it all the time. It really helps. Currently, you can only use this feature with classes, but if #1341 gets accepted you can do any callable.

```php
<?php

// register the service controller service provider
$app->register(new Silex\Provider\ServiceControllerServiceProvider());

// in src/Controller/SomeController.php
class SomeController 
{
    private $hlp;
    private $db;
    
    public function __construct(Helpers $hlp, DB $db) {
        $this->hlp = $hlp;
        $this->db = $db;
    }
    
    public function getIndexAction(Request $req, Application $app) {
        /* use $this->db or $this->hlp to access those objects */
        return 'index';
    }
}

// defining a service in silex 1.3

// in a service provider for your app somewhere
$app['app.controller.some'] = $app->share(function() use ($app) {
    return new SomeController($app['app.helpers'], $app['app.db']);
});

// or defining a service in silex 2.0

$app['app.controller.some'] = function($app) {
    return new SomeController($app['app.helpers'], $app['app.db']);
};

// in the place where you define routes
$app->get('/', 'app.controller.some:getIndexAction');
```

If you like to use functions instead of classes, then in 2.0 if #1341 gets accepted, you could potentially do this.

```php
<?php

// silex 2.0 (maybe)

// register the service controller service provider
$app->register(new Silex\Provider\ServiceControllerServiceProvider());

// in src/controllers.php
function controllerSomeGetIndex(Helpers $hlp, DB $db) {
    return function(Request $req, Application $app) use ($hlp, $db) {
        /* use $hlp or $db */
        return 'index';
    };
}

// in a service provider for your app somewhere
$app['app.controller.some'] = function($app) {
    return controllerSomeGetIndex($app['app.helpers'], $app['app.db']);
};

// in the place where you define routes
$app->get('/', 'app.controller.some');
```

**Comment by cocodrino** [comment]
thanks for the reply @ragboyjr , Yes I think than I'm searching for a solution similar to your 2nd example, using functions, hope than your propose will be accepted!!...

**Comment by ragboyjr** [comment]
Awesome, thanks man!
