### ISSUE TITLE
Setting the Security Service Provider Access Manager Strategy

### ISSUE THREAD

**Issue by patrickw276** [silexphp/Silex#1326]
It looks like the only way to set the SecurityServiceProvider AccessManager's strategy is though overriding the default AccessManager after loading the provider. I'd like the be able to set this option though a variable (e.g `$app['security.access_manager.strategy']`) without needing to redeclare the `$app['security.access_manager']` service. 

Is there any issue with me submitting a pull request to update the provider to check for this variable?

**Comment by mTorres** [comment]
I don't think that overwriting the *security.access_manager* is shuch a big deal. The code is clean:

    <?php

    $app->register(new SecurityServiceProvider(), array(
      'security.access_manager' => function ($c) {
        return new AccessDecisionManager($c['security.voters'], AccessDecisionManager::STRATEGY_CONSENSUS);
    }));

More opinions?

**Comment by patrickw276** [comment]
My thought is that the access manager is already declared and could easily be made more configurable without any issue (as far as I can tell). There is already a lot of configuration required when setting up the security component, at least in my use cases, and this could reduce the amount of boilerplate/redundant code.

**Comment by ragboyjr** [comment]
@patrickw276, I think I'd agree with @mTorres. There is already a ton of service configuration parameters for the Security component. 

Sometimes when you have enough custom configuration, it's easier to just make your own objects in your own service provider specifically for your application.

**Comment by fabpot** [comment]
Changing the strategy is very rare and that's why there is no easy way to change it. As already mentioned, changing it is not that complex, so closing this one.
