### ISSUE TITLE
allow "callable" classes & closure as controller services

### ISSUE THREAD

**Issue by mathroc** [silexphp/Silex#1327]
what do you think about allowing any [callable](http://php.net/manual/en/language.types.callable.php) as controller services? (or anywhere a callback is expected)

at the moment closure cannot be used as controllers because callback should be objects on which a method is called. but in php there are 2 other kind of callable:

 * objects with an `__invoke` method (can be used like that: 'callable:__invoke')
 * closure

I guess something along those lines could work:

```php
class CallbackResolver
{
    public function isValid($name)
    {
        return is_string($name);
    }

    public function convertCallback($name)
    {
        if (preg_match(static::SERVICE_PATTERN, $name)) {
            list($service, $method) = explode(':', $name, 2);
            if (!isset($this->app[$service])) {
                throw new \InvalidArgumentException(sprintf('Service "%s" does not exist.', $service));
            }
        
            $callback = array($this->app[$service], $method);
        } else {
            $callback = $this->app[$service];
        }
        if (!is_callable($callback)) {
            throw new \InvalidArgumentException(sprintf('Service "%s" is not callable.', $name));
        }
        return $callback;
    }
```

**Comment by ragboyjr** [comment]
Ya, that seems good to me, you should make a PR into master.
