### ISSUE TITLE
ServiceProvider : subscribe before boot ?

### ISSUE THREAD

**Issue by johndodev** [silexphp/Silex#1329]
Hi,

I may miss something. I would like to use the ```boot()``` method of a ```BootableProviderInterface``` provider to extend a service. Isn't a use case ? Since the service I want to extend may be defined later, using the boot method seems appropriate.

Problem is that when we use a ```subscribe()``` in an ```EventListenerProviderInterface``` provider, injected services are instanciated, but ```subscribe()``` is called before ```boot()```, so I can't extend a service used in a subscribe method :(.

The solution is to register servicesProviders in a good ordering and put the extend in the ```register()``` function, but we can't always control that. Example, I can't extend twig in a boot() method if I use the WebProfilerServiceProvider.

Isn't more apporpriate to call all subscribe() after all boot() of providers ?

**Comment by ragboyjr** [comment]
Can you give a specific use case of this?

**Comment by fabpot** [comment]
You should never change the service definitions in the `boot()` method. Booting where some services can be instantiated, so it's too late.
