### ISSUE TITLE
Event listeners added after EventDispatcher creation are "lost"

### ISSUE THREAD

**Issue by spantaleev** [silexphp/Silex#1335]
Due to the way event listeners are added in `\Silex\Application::on()` after 237ed42dbe38, event listeners could get lost in certain cases.

# Problem

1. During a `boot()` (that is, `Application::$booted = false`, for the time being), something accesses the `$app['dispatcher']` service and causes it to get created and initialized.

2. Since the application is still in the boot phase (`Application::$booted = false`), the code in `\Silex\Application::on()` decides to add a listener by extending the `$app['dispatcher']` service.

Like this:

    $this['dispatcher'] = $this->share($this->extend('dispatcher', function (EventDispatcherInterface $dispatcher, $app) use ($callback, $priority, $eventName) { ... }));

Result: this does nothing to the existing (already created `$app['dispatcher']` object).

------

# Workaround:

Just fetching the dispatcher service from the container again causes all those "extend" closures to run and properly register the listeners.

    //Workaround
    $app['dispatcher'];

------

Perhaps this is an underlying problem of Pimple and its inability to tell if a service has already been created or not.

Still, it appears that Silex's `Application::on()` code may be operating under an unsafe assumption since 237ed42dbe38.
It has 2 separate code paths for booted and not-booted.

It assumes that when booted, `$app['dispatcher']` can be directly communicated with. That's good.
It also assumes that when **not booted**, it can just extend the service definition.

The thing is, there seems to be an intermediate ***booting*** phase, during which the `$app['dispatcher']` service may get created and passed around. During that ***booting*** phase, `Application:$booted` is still `false` and Silex keeps extending the `$app['dispatcher']` service definition.

Thus, an already created `EventDispatcher` object would be incomplete until `$app['dispatcher']` is accessed again.
I believe this currently doesn't cause a problem for other people, because `$app['kernel']`'s creation later in time, would reference `$app['dispatcher']` again and resolve that broken/incomplete state.

-------------

For me the issue was triggered by:

- having some ServiceProviders which carelessly do `$app['twig']->addExtension()`, instead of delaying this with the share/extend flow. While not ideal (from a performance standpoint), I believe that `boot()` is the proper place to be accessing services (like Twig) and modifying their state, should one wish to do it.

- using the `HttpCacheServiceProvider` and `HttpFragmentServiceProvider`. Because of that, `TwigServiceProvider` and because `$app['twig']` is created and initialized somewhere in `boot()`, `$app['fragment.handler']` is referenced and created (from `TwigServiceProvider`). The chain continues some more, but ultimately ends up creating `$app['kernel']` and its dependency `$app['dispatcher']`.

Basically, an `$app['twig']` reference inside some ServiceProvider's `boot()` causes the kernel and dispatcher to be created somewhat early.

In any case, the same thing would happen if any of the ServiceProviders somehow references `$app['kernel']` for its own other reason. That would cause its dependency `$app['dispatcher']` to be created during the ***booting*** (but not yet fully **booted**) phase, and all future `before()` / `after()` / `on()` calls would be lost until `$app['dispatcher']` gets accessed again. And since the kernel has already been created, `$app['dispatcher']` may never get accessed by anything else and would ultimately **lose** the listeners.

If 237ed42dbe38 were to be reverted, the problem would go away.
Since that carries its own performance regressions, some other solution may be necessary.

-----------------

# Example code illustrating the `extend()` problem

	class MyService {

		public $messages = array();

		public function add($msg) {
			$this->messages[] = $msg;
		}

	}

	$app = new \Pimple();

	$app['svc'] = $app->share(function () {
		return new MyService();
	});

	//Create our service early
	$svc = $app['svc'];

	//Empty array, as expected
	var_dump($svc->messages);

	$app['svc'] = $app->share($app->extend('svc', function (MyService $svc) {
		$svc->add('hello');
		return $svc;
	}));

	//Empty array. Extending did not do anything for the already-created service.
	var_dump($svc->messages);

	//Just fetch the service from the container again.
	$app['svc'];

	//Only after we have reinitialized the service, do we have 1 item there.
	var_dump($svc->messages);

**Comment by GromNaN** [comment]
The issue seems to be fixed in Silex 2, the app is marked as booted before listener subscription: https://github.com/silexphp/Silex/blob/master/src/Silex/Application.php#L109-L112

**Comment by stof** [comment]
creating the service early is precisely your mistake.

Extending the definition of a service after it was instantiated won't have any effect, as the definition won't be called again (Pimple 1.x will execute the extended definition on the next service access due to the way services are shared in Pimple 1, but this is not the case anymore in Pimple 2+ and should be considered as an architectural bug in Pimple 1).

Even though Pimple rebuilds the container for each request instead of dumping it in the cache like the Symfony DI component, it is still important to consider the 2 phases of the container lifecycle:
- the container building phase where the service definitions are registered (and can be extended or replaced). Any service access is strictly forbidden in this phase
- the container usage phase where services are used. Any service definition should be considered forbidden here (technically, Pimple will let you define new services there, but not change existing ones in Pimple 3+. And Pimple technically move services individually to the usage phase on first access)

**Comment by spantaleev** [comment]
@stof, by early, you also consider the booting phase early?

Isn't that the moment that services should be created, passed around and used?

**Comment by stof** [comment]
@spantaleev in Silex 1.x, the boot method is still part of the building phase, yes (this changed in Silex 2)

**Comment by ragboyjr** [comment]
So, can we close this then considering that this issue is a non-issue on 2.0-dev?

**Comment by ragboyjr** [comment]
@spantaleev thanks man!
