### ISSUE TITLE
require pimple/pimple

### ISSUE THREAD

**Issue by javiertrejo** [silexphp/Silex#1336]
Hello, is possible the update the requirements from pimple ~1.0 to ~3.0 without broken the framework functionality?

**Comment by stof** [comment]
no it is not, as Pimple 1 does not work the same than Pimple 2+ (which is why it is a different major version).

The 2.x version of Silex (not yet stable) is based on Pimple 3+

**Comment by GromNaN** [comment]
No, pimple 1 and 3 and not compatibles.

**Comment by javiertrejo** [comment]
Thanks, i wait to the new stable version.
