### ISSUE TITLE
The Phar file...

### ISSUE THREAD

**Issue by feamsr00** [silexphp/Silex#1337]
Hi,

So, the Phar on the download page. The page does say its deprecated but is it updated at all? Moreover the phar is not readily usable as its missing a required part of composer. This alone seems like an easy fix to get the file usable again.

Additionally I know you went through the trouble of listing phar's indictments, but that was... many moons ago. The current situation on the ground certainly seems to have changed. Presuming the phar is not updated, perhaps its a good time to try to start distributing the phar again?

**Comment by ragboyjr** [comment]
What exactly are you trying to use the phar for?

**Comment by fabpot** [comment]
I would err on the side of removing everything related to the phar altogether. With Composer, I don't think there is still

**Comment by fabpot** [comment]
I've just removed the phar mention from the website (will be deployed later today).

**Comment by feamsr00** [comment]
For what it's worth, I (we) use the phar to enable rapid development and deployment of tools. With *only* the PHAR file and *not* the slew of things brought in by composer, we can give a small tool/app a full web stack. It's far easier to deploy and adds no net burden to development. 

Phar's are great for those reasons (at least!), and is a fine choice for distribution of *toolkits* (and not mere libraries). The crux here, I suppose, is that silex is a toolkit (not a library, and dare I say not even a framework) because it is fairly self-contained and has low to no integration requirements. I contest that such a situation is a _excelent_ case for distribution of a PHAR. This reasoning can't be far off the mark considering there was an initial decision to do this!

Thoughts @fabpot ?

**Comment by feamsr00** [comment]
ftfy
[silex-2.0.4.phar.zip](https://github.com/silexphp/Silex/files/720876/silex-2.0.4.phar.zip)

**Comment by feamsr00** [comment]
ftfy
download [silex-2.1.0.phar.zip](https://github.com/silexphp/Silex/files/1000630/silex-2.1.0.phar.zip)

**Comment by feamsr00** [comment]
ftfy
download phar [silex-2.2.4.zip](https://github.com/silexphp/Silex/files/1854529/silex-2.2.4.zip)
