### ISSUE TITLE
Something seams wrong in SessionServiceProvider

### ISSUE THREAD

**Issue by quazardous** [silexphp/Silex#1342]
Hi,

it's not a bug since nothing is broken (yet), but there is something odd on lines 41 and 64 of the SessionServiceProvider (master)

line 41:

    return new Session($app['session.storage']);

the Session `__constructor()` signature is:

    public function __construct(SessionStorageInterface $storage = null, AttributeBagInterface $attributes = null, FlashBagInterface $flashes = null)

line 64:

    return new SessionListener($app, $app['session.attribute_bag'], $app['session.flash_bag']);

the SessionListener `__constructor()` signature is:

    public function __construct(Container $app)

To me it seams like some kind of inversion mistake.

**Comment by ragboyjr** [comment]
Yup, looks like a bug to me.
