### ISSUE TITLE
Why require from 5.3.9?

### ISSUE THREAD

**Issue by ReenExe** [silexphp/Silex#1351]
Silex use trait that starts from 5.4 - http://php.net/manual/en/language.oop5.traits.php
Also your Travis build from PHP 5.5 - https://travis-ci.org/silexphp/Silex
So should change in require to PHP 5.4?

**Comment by ReenExe** [comment]
After version change - we can use short array - `[]`

**Comment by ragboyjr** [comment]
@ReenExe silex 2.0-dev requires php 5.5.
