### ISSUE TITLE
How to append data to views?

### ISSUE THREAD

**Issue by DaveSanchez** [silexphp/Silex#1352]
Is there any way to add a variable to the view that is about to be rendered? I want to do something like AppendData function in [slim](http://docs.slimframework.com/view/data/)

**Comment by ragboyjr** [comment]
Well, silex doesn't actually have any view rendering component. You *can* use any view library that you want. However, out of the box, it supports twig. So you'll want to look at the twig documentation.

In twig you can set global variables that are shown in all templates, but it looks like you can't set data for a template, then add more data. There are examples of how to do what you want to do in the [docs](http://silex.sensiolabs.org/doc/providers/twig.html#customization).

You could also just create an array, then set more values on the array, then pass the modified array into the render method.

```php
<?php

$data = [
    'var1' => 1,
];

// do stuff

// add in more data
$data['var2'] = 2;

return $app['twig']->render('template', $data);
```
