### ISSUE TITLE
Documentation warning message is wrong on 1.3

### ISSUE THREAD

**Issue by Soullivaneuh** [silexphp/Silex#1356]
On http://silex.sensiolabs.org/doc/1.3/:

![image](https://cloud.githubusercontent.com/assets/1698357/15305308/94c2545c-1bc2-11e6-90c5-c8d3013d53ac.png)

It should be:

> This is documentation is for Silex 1.3

**Comment by fabpot** [comment]
Indeed, will be fixed in the next deploy. Thanks for the report.
