### ISSUE TITLE
Website issues with version 2.0

### ISSUE THREAD

**Issue by hkdobrev** [silexphp/Silex#1357]
Apart from the API url issue mentioned here: https://github.com/silexphp/Silex/issues/1314#issuecomment-219817325

I've spotted a few things:
1. The homepage does not mention this is the documentation for 2.0 and there's no link for documentation of 1.3 like http://pimple.sensiolabs.org/ (there's one here: http://silex.sensiolabs.org/doc/master/, but not on the homepage which is a problem considering 2.)
2. The homepage links to the download page - http://silex.sensiolabs.org/download This page mentions version 1.3 in the Composer instructions. We should probably recommend `composer require` once `2.0` is tagged.

**Comment by fabpot** [comment]
API URL fixed
About the homepage, there is no need to mention a version as the code snippet works for both Silex 1.3 and 2.0 :)
Download page updated

Everything is going to be deployed when 2.0 is tagged.

Thanks for your review.

**Comment by hkdobrev** [comment]
@fabpot Congrats on the release! I still see 1.3 on the download page http://silex.sensiolabs.org/download
