### ISSUE TITLE
API Link broken

### ISSUE THREAD

**Issue by luislonardi** [silexphp/Silex#1359]
what happend with the API page that is missing since the last weekend 20160514
regards

**Comment by ragboyjr** [comment]
Ya, I can confirm the it's a missing link

**Comment by fabpot** [comment]
Not sure to understand this issue. What is missing?

**Comment by fabpot** [comment]
ok, I see.

http://silex.sensiolabs.org/api/master/index.html

**Comment by fabpot** [comment]
fixed
