### ISSUE TITLE
Swiftmailer configuration reset after registration of SwiftmailerServiceProvider

### ISSUE THREAD

**Issue by bjornpost** [silexphp/Silex#1363]
Given: 

    $config = [
        'swiftmailer.options' = [ 'host' => 'smtp.example.com', ... ],
    ];
    $app = new Application($config);

Inside my `Application` class:

    public function __construct(array $values = array())
    {
        parent::__construct($values);
        $this->register(new \Silex\Provider\SwiftmailerServiceProvider());
    }

So far so good for configuring most providers. But my `swiftmailer.options` settings are overwritten by the `SwiftmailerServiceProvider` constructor, [see the source here](https://github.com/silexphp/Silex/blob/master/src/Silex/Provider/SwiftmailerServiceProvider.php#L31).

I'm trying to split the registration of providers and configuration of providers, so that I can create a configuration file on a per environment basis.

I would expect that an already defined configuration should not be overridden. What Silex concept am I missing here?

**Comment by kamilsk** [comment]
- 1. Change the sequence
```php
public function __construct(array $values = array())
{
    // register before set values
    $this->register(new \Silex\Provider\SwiftmailerServiceProvider());
    parent::__construct($values);
}
```
- 2. Extend SwiftmailerServiceProvider
```php
public function register(Container $app)
{
    parent::register($app);
    // configuring
}
```

I usually choose the second option.

> I'm trying to split the registration of providers and configuration of providers, so that I can create a configuration file on a per environment basis.

configuration: https://github.com/kamilsk/TinkoffCurrencyAnalyst/blob/master/web/index.php#L9-L12
registration: https://github.com/kamilsk/TinkoffCurrencyAnalyst/blob/master/web/index.php#L18-L20

**Comment by kamilsk** [comment]
Silex app has second argument, and as you can see here https://github.com/silexphp/Silex/blob/master/src/Silex/Application.php#L86-L93, https://github.com/silexphp/Pimple/blob/master/src/Pimple/Container.php#L272-L281 it register ServiceProvider first and after that setup values/config for ServiceProvider

**Comment by bjornpost** [comment]
> 1. Change the sequence

That works for the `SwiftmailerServiceProvider`, but the `TwigServiceProvider` (for example) can only be registered after calling `parent::__construct()`. Isn't a really sustainable solution.

> 2. Extending SwiftmailerServiceProvider

Is an option, but requires a lot of extra code. Plus the configuration of the application is scattered over a lot of files. I'd like to have them bundled together on a per-environment basis.

> Silex app has second argument

Seems like a good approach. Will try.

Thanks for thinking along :-)
