### ISSUE TITLE
Form name

### ISSUE THREAD

**Issue by flip111** [silexphp/Silex#1365]
At `Usage` of the `FormProvider` http://silex.sensiolabs.org/doc/providers/form.html#usage the name of the form is `form`. However when i use that i get this error: `Could not load type "form"`. I'm on silex-master. This is possibly because something in the symfony form has been changed recently.

Also it would be nice to have a builder method that doesn't require the default form name. This is useful if you just want to pass some default data.

Using `'Symfony\Component\Form\Extension\Core\Type\FormType'` fixes the issue, but it's not really nice boilerplate :(

**Comment by kabudu** [comment]
@flip111 I had a similar issue when I upgraded from Silex ```2.0.x-dev#c207787``` to ```v2.0.0```. After the upgrade, my custom form types could no longer be found and I got the same error you did, ```Could not load type "my_form_name"```. I tried your solution, but it didn't work for me. I also tried registering my form types as services, but that didn't work either.

I've defined my custom form types like the below as per the Silex documentation:

```
$app['form.types'] = $app->extend('form.types', function ($types) use ($app) {
    $types[] = new YourFormType();

    return $types;
}));
```

It did work on the previous pegged commit version I was using, but broke on the ```v2.0.0``` tag. I think I'll just stick to the version I'm using until the BC bug has been fixed or the documentation is updated to show how it needs to be done on the released v2.0.* tag versions.

**Comment by HeahDude** [comment]
Silex 2.0 use the form component >= 2.8 so you should load types by their FQCN only (e.g `FormType::class` as shown in the link to the doc provided by @flip111) not their names (essentially used in templates and html attributes).

Hence, one don't need to use the code in @kabudu's example unless it got dependencies:
```php
$app['form.types'] = $app->extend('form.types', function ($types) use ($app) {
    $types[] = new YourFormType(); // useless
    $types[] = new SomeType($app['some.service']); // needed

    return $types;
}));
```

@flip111 On what line do you see `form` as name? This issue may be closed if you can confirm the link point to the updated doc. Thanks.

**Comment by kabudu** [comment]
@HeahDude My form types have dependencies so I do need to use the $app->extend functionality. However, I did try using the FQCN for initialising my form type with Silex ```v2.0.0```, but it didn't work and resulted in a similar error as above.

**Comment by flip111** [comment]
@kabudu 

> my custom form types could no longer be

i'm not sure if this is directly related .. it could be though

@HeahDude 

The documentation seems to have changed since i opened this issue.

---

By the way ... in my own code i prefer to do this now
```php
use use Symfony\Component\Form\Extension\Core\Type as F;

// usage:
F\ChoiceType();
```
So then i don't have to import all types one by one

@kabudu keep discussing here, or open a new issue if you have a problem still. But since i'm the owner of this issue and the comment was about the documentation (which seems fine atm) i'm going to close this.
