### ISSUE TITLE
PHP7 Error handling

### ISSUE THREAD

**Issue by countless-integers** [silexphp/Silex#1367]
Does anyone have a way to deal with [`Error`](http://php.net/manual/en/language.errors.php7.php) exceptions triggered in PHP7 apps? I think so far only regular `Exception` exceptions are caught (e.g. https://github.com/silexphp/Silex/blob/master/src/Silex/ExceptionListenerWrapper.php#L58). I guess switching to typing for `Throwable` might be an option, but would need some work for backwards compatibility.

 Some of the errors would be useful to catch e.g. `TypeError` or do you consider that a bad practice? 

Using Silex 1.3.*

**Comment by bobalazek** [comment]
http://silex.sensiolabs.org/doc/master/cookbook/error_handler.html ?

**Comment by countless-integers** [comment]
Ha, I was thinking about some sort of middleware, but I might make that work as well. Thanks.
