### ISSUE TITLE
Tag Silex-Api version 2.0

### ISSUE THREAD

**Issue by tpetry** [silexphp/Silex#1371]
The new package `silex/api` is meant to develop service providers which do not directly depend on the `silex/silex` package. But as the `silex/api` has not published a stable `2.0` version to packagist, it's not usable to use it as a dependency.

**Comment by stof** [comment]
@fabpot can you check that the webhook is configured properly ?

**Comment by stof** [comment]
hmm, actually, the issue is the subtree split. The https://github.com/silexphp/Silex-Api does not contain the tag

**Comment by fabpot** [comment]
fixed

**Comment by hkdobrev** [comment]
I'm sorry for the off-topic question, but I'm trying to understand how one would use `silex/api` and `silex/providers` without using `silex/silex`.

> The new package `silex/api` is meant to develop service providers which do not directly depend on the `silex/silex` package.

However `silex/api` and `silex/providers` use the `Silex\Application` class which is defined only in `silex/silex`.
