### ISSUE TITLE
Silex 1.3: Twig debug extension should be loaded always, or add an option to provide an alternative dump function

### ISSUE THREAD

**Issue by rubenvincenten** [silexphp/Silex#1373]
Right now when putting silex in production mode (without debug), the dump() function is unavailable due to Twig_Extension_Debug not being registered. So when one of your template designers is uploading a twig file with the dump function in it, silex tries getting the error page because a Twig_Error_Syntax exception is thrown.

RIght now I'm solving this with the following code:

``` php
<?php

$app = new Silex\Application;

$app->register(new Silex\Provider\TwigServiceProvider(), array(
    'twig.options' => array(
        'cache' => $cache_dir,
        'auto_reload' => true,
    ),
    'twig.path' => __DIR__ . '/../views',
));

$app['twig'] = $app->extend('twig', function (Twig_Environment $twig, Application $app) {
        // triggers E_USER_DEPRECATED in debug mode only
        $twig->addExtension(new \Twig_Extension_Debug());
});
```

However this feels hacky and should be a default option, the dump function already has code to do nothing if the Twig_Environment debug mode is off:

``` php
<?php

function twig_var_dump(Twig_Environment $env, $context)
{
    if (!$env->isDebug()) {
        return;
    }

    // more code, stripped
}
```

**Comment by GromNaN** [comment]
This is consistent with [Symfony's TwigBundle](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/TwigBundle/DependencyInjection/Compiler/ExtensionPass.php#L66-L69).

The only argument I see against having this extension always registered, is the performance impact. But is it worst the bad DX ?

**Comment by mathroc** [comment]
@rubenvincenten why would you want a `dump` function in production ? I'd rather have an error I can detect quickly than a `dump()` hidden somewhere

**Comment by rubenvincenten** [comment]
@mathroc Because it would make sense in production mode that pages actually keep working even when your dumb colleagues forget to comment out or remove dump statements.

This can be closed, but I would recommend adding a section to the docs with code to circumvent this problem. Or maybe the extension can use the code below:

```php
$app['twig'] = $app->extend('twig', function (Twig_Environment $twig) {
        // the buttons, they do nothing!!
        $twig->registerUndefinedFunctionCallback(function ($name) {
            if ($name == 'dump') {
                return new Twig_SimpleFunction('dump', function () {
                });
            }

            return null;
        });
});
```
