### ISSUE TITLE
Redirect Loop

### ISSUE THREAD

**Issue by wfabian** [silexphp/Silex#1378]
Hi,
following problem:
My htaccess generates a redirect-loop.
On my local system there is no problem, but on a web-server (1und.de) i get the redirect loop.

I have the typical structure:
public-directory with .htaccess and index.php.
index.php includes the silex-application (../src/app.php)

This is my .htaccess:
```
<IfModule mod_rewrite.c>
    Options -MultiViews

    RewriteEngine On
    RewriteBase /
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [QSA,L]
</IfModule>
```

I have to define the RewriteBase, otherwise it will not work.
Can anyone help?

**Comment by ragboyjr** [comment]
1. what is the redirect loop you are getting?
2. Have you checked the web server to make sure there isn't any other configurations that could be affecting your site?

I've been running silex on apache and nginx and have never experienced a redirect loop.

**Comment by aymone** [comment]
In my case, if i do this:
src/controller.php
```php
$app->mount("/v1/tests", new Test/TestProviderController());
```

then call src/Test/TestProviderController, 
```php
$controllers = $app['controllers_factory'];
$controllers->get("/", "Bundle\\Test\\TestController::get");
```
and call src/Test/TestController.php
```php
class TestController
{
    public function get(Request $request, Application $app)
    {
        return new JsonResponse(['test' => 'OK']);
    }
}
```

and make a curl request:
```console
$ curl -v http://host:port/tests
```

I receive this response:
```console
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="1;url=/tests/" />

        <title>Redirecting to /tests/</title>
    </head>
    <body>
        Redirecting to <a href="/tests/">/tests/</a>.
    </body>
```

but with extra bar at the end of url and request again:
```console
$ curl -v http://host:port/tests/
```

I receive correct response:
```
*   Trying 127.0.1.1...
* Connected to php-docker.local (127.0.1.1) port 8080 (#0)
> GET /v1/stocks/ HTTP/1.1
> Host: php-docker.local:8080
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx/1.11.1
< Content-Type: application/json
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Powered-By: PHP/7.0.8
< Cache-Control: no-cache
< Date: Sat, 16 Jul 2016 19:15:30 GMT
< 


```

**Comment by SpacePossum** [comment]
Is this on request the root of domain only? Maybe the `RewriteBase /` is in the way, since Silex might redirect to a path not having a trailing '/' when you've mounted a service/controller on it,

**Comment by fabpot** [comment]
Closing as there is no feedback.
