### ISSUE TITLE
Controller "Closure" requires that you provide a value for the "$user" argument (because there is no default value or because there is a non optional argument after this one).

### ISSUE THREAD

**Issue by lcp0578** [silexphp/Silex#1380]
RuntimeException in ControllerResolver.php line 126:
Controller "Closure" requires that you provide a value for the "$user" argument (because there is no default value or because there is a non optional argument after this one).

```
use Lcp\UserControllerProvider;
$userProvider = function($userid){
    return new UserControllerProvider($userid);
};
$app->get('/profile/{userid}', function (UserControllerProvider $user){
    $id = $user->getId();
    return new JsonResponse(array(
        'profile' => $id
    ));
})->convert('userid', $userProvider);
```
UserControllerProvider.php

```
namespace Lcp;


class UserControllerProvider 
{
   private $id;
   
   public function __construct($id)
   {
       $this->id = $id;
   }
   
   public function getId()
   {
       return $this->id;
   }
  
} 
```
Can you tell me something wrong?
Thanks

**Comment by stof** [comment]
the issue is that you are using ``userId`` in the route definition, but ``$user`` as the argument name. The code resolving controller arguments relies on parameter names

**Comment by lcp0578** [comment]
Oh, I got it. Thank you.
