### ISSUE TITLE
I update version and caught error: Warning: class_parents(): Class int does not exist and could not be loaded

### ISSUE THREAD

**Issue by l-vitaly** [silexphp/Silex#1389]
File /var/www/vendor/silex/silex/src/Silex/AppArgumentValueResolver.php line 37

controller method - public function getResource(Request $request, int $id)

**Comment by GromNaN** [comment]
There is an issue with PHP7 type int with controllers. As a quickfix you could remove the `int` hint on `$id`. I'm working on a patch for PHP7.

**Comment by l-vitaly** [comment]
Thanks!

**Comment by SpacePossum** [comment]
@fabpot could we have a 2.0.3 tag for this bug fix?

**Comment by fabpot** [comment]
Done

**Comment by SpacePossum** [comment]
thanks for the tag @fabpot , thanks for the fix @GromNaN !

**Comment by tiemevanveen** [comment]
Thanks!
