### ISSUE TITLE
Make a difference between static route and a parameter one

### ISSUE THREAD

**Issue by moulinux** [silexphp/Silex#1391]
Here is two defined path :

```
$app->get('/hello/{name}', function($name) {
    return "Hello World $name";
});

$app->get('/hello/test', function() {
    return "Hello World -> test";
});
``` 
When I call the URL (/hello/test), I am expecting to have "Hello World -> test", but I have "Hello World test"

**Comment by SpacePossum** [comment]
This is because the routes are matched in a first match order, not a 'best` (or how you want to call it) order. Flip the routes around, i.e. '/hell/test' first and it should work as you want.

**Comment by moulinux** [comment]
correct.

cheers.
