### ISSUE TITLE
TranslationServiceProvider showing some path errors in Silex 2.0

### ISSUE THREAD

**Issue by icemanbsi** [silexphp/Silex#1401]
Hi, I'm new in this micro framework, so I tried to use it by learning the documentation. Lately, I tried the Translation Service. I did what the documentation said at "[http://silex.sensiolabs.org/doc/master/providers/translation.html#yaml-based-language-files](http://silex.sensiolabs.org/doc/master/providers/translation.html#yaml-based-language-files)".

`use Symfony\Component\Translation\Loader\YamlFileLoader;

$app->extend('translator', function($translator, $app) {
    $translator->addLoader('yaml', new YamlFileLoader());

    $translator->addResource('yaml', __DIR__.'/locales/en.yml', 'en');
    $translator->addResource('yaml', __DIR__.'/locales/de.yml', 'de');
    $translator->addResource('yaml', __DIR__.'/locales/fr.yml', 'fr');

    return $translator;
});`

At the first line, it seems the path is no longer exists. I think it should be `use Symfony\Component\Routing\Loader\YamlFileLoader;`.

And then, what surprised me is when I registering the service provider, there're several missing path inside `TranslationServiceProvider`. Below are the missing path : 

1. use Symfony\Component\Translation\Translator;
2. use Symfony\Component\Translation\MessageSelector;
3. use Symfony\Component\Translation\Loader\ArrayLoader;
4. use Symfony\Component\Translation\Loader\XliffFileLoader;

Did I missed something?
Please help me solve this problem.
Thank you

**Comment by SpacePossum** [comment]
It seems you haven't installed the Translation component itself;

```bash
composer require symfony/translation
```

**Comment by icemanbsi** [comment]
Thanks @SpacePossum 
Yeah, in fact I missed the most important line at the top of documentation.. 
sorry for my mistake.. 
Thank you

**Comment by SpacePossum** [comment]
thanks for reporting back, good to hear you solved it! :)
