### ISSUE TITLE
Request->getUri() add ?u=

### ISSUE THREAD

**Issue by seblucas** [silexphp/Silex#1404]
Hi,

I don't know if this issue should be posted here or in https://github.com/symfony/symfony as I'm using Silex I'll post here first.

If I point my browser to my Silex app : `http://localhost/test/opds` and I call `$request->getUri()` in my code I'll have `http://localhost/test/opds?u=`.

I've checked and rechecked there was no redirect involved. So far I've used : 
```
$request->getSchemeAndHttpHost() . $request->getRequestUri()
```

But that still feel strange.

**Comment by bjornpost** [comment]
Please post your webserver configuration, specifically the part where you do your URL rewriting.

**Comment by seblucas** [comment]
Of course you"re right there's no problem in Silex ..... 

the problem was me and an old trick I used in Nginx ....


Sorry for the noise and thanks for the help
