### ISSUE TITLE
symfony/cache provider

### ISSUE THREAD

**Issue by SpacePossum** [silexphp/Silex#1405]
Hi all,

Just wondering, would it be feasible and wanted to have a provider added to the default/core set of Silex which provides away to work with the `symfony/cache`?

**Comment by GromNaN** [comment]
Here it is:
```php
use Silex\Provider\ServiceProviderInterface;
use Symfony\Component\Cache\Adapter\FilesystemAdapter;

class CacheServiceProvider implement ServiceProviderInterface
{
    function register(Application $app)
    {
        $app['cache'] = function ($app) {
            return new FilesystemAdapter();
        };
    }
};
```

But this creates an unique cache service. But usually, you need a distinct cache instance for each use case.

**Comment by SpacePossum** [comment]
Thanks for the sample :)
I was thinking that having a provider the setup for each use case can be done with more ease, i.e. prevent repeating over projects.
For example something like this;

```php
<?php
$app->register(
    new CacheServiceProvider(),
    [
        'adapter' => 'array', // 'filesystem', 'APCu', 'Redis', 'Chain', 'Proxy', 'Doctrine'
        'namespace' => 'my_app',
        'defaultLifetime' => 3600,
        // other params to create the adapter
    ]
);

//  PSR-6 cacheitempoolinterface
$app['cache']->getItem('some_key');
```
