### ISSUE TITLE
How to pass attribute to a controller converter?

### ISSUE THREAD

**Issue by nimasdj** [silexphp/Silex#1409]
As of here: http://silex.sensiolabs.org/doc/master/usage.html#route-variable-converters
I want to define the converter as service to use Doctrine ORM.

If I use:

    $app['converter.user'] = function ($user, Request $request) use ($em){
         print($request->attributes->get('user'));
         return new UserConverter($em);
    };

    $app->get('/user/{user}', function (Silex\Application $app, Request $request, $user) {
          return $app->json($user);
    })
    ->convert('user', 'converter.user:convert');

The 'user' attribute is not available in service and I get the error:

`Fatal error: Call to a member function get() on null`

But if instead of a service I use a variable like below then the attribute 'user' works fine! what wrong I did above? I need to pass the value of 'user' attribute to pass to `convert()` method of `UserConverter()` class, how can I do so from the service above?

    $user = function ($user, Request $request) use ($em){
            print($request->attributes->get('user'));
            return new UserConverter($em);
    };
    $app->get('/user/{user}', function (Silex\Application $app, Request $request, $user) {
          return $app->json($user);
    })
    ->convert('user', $user);

**Comment by nimasdj** [comment]
Is here any support or is this repository still maintained??

**Comment by mathroc** [comment]
Hi @nimasdj, this place is not for support, Github issues are for reporting bug in the software. Someone may answer you here but for support you should try stackoverflow instead

for this question, you could do it like that:

```php
$app['em'] = $em;
$app['converter.user'] = function (Silex\Application $app) {
     return new UserConverter($app['em']);
};
$app->get('/user/{user}', function (Silex\Application $app, $user) {
      return $app->json($user);
})
->convert('user', 'converter.user:convert');
```

**Comment by nimasdj** [comment]
Thanks @mathroc, sorry for confusion. $em was working fine with my code, I meant to ask how to use
```$request->attributes->get('user')``` inside my UserConverter as it has no value there and how can I pass its value from controller to the class?
So should I use:
```$app['user'] = $request->attributes->get('user');``` 
then pass it to the class constructor? Or is there any better way?

**Comment by mathroc** [comment]
you should not use `$request` inside your converter, in fact, you don't need it at all in your exemple.

```php
$app['em'] = $em;
$app['converter.user'] = function (Silex\Application $app) { // this function returns a converter
     return new UserConverter($app['em']);
};
$app->get('/user/{user}', function (Silex\Application $app, User $user) {
      return $app->json($user);
})
->convert('user', 'converter.user:convert');
```

silex will get the `converter.user` service and call the `convert` method on it with the value of `{user}` as its first argument, the value it returns will then be passed as `$user` to the controller

**Comment by nimasdj** [comment]
@mathroc Do you mean the value of {user} attribute is available as $user inside my convert() mthod? What about request (_POST) values? They will be available with the same posted variable name?

**Comment by nimasdj** [comment]
@mathroc Thanks for the advice. It is working fine now, but what if this is a post method? how to pass posted data to convert method()?
```$app->get('/user/{user}', function....` this way {user} attribute is the first argument of method but if we have ```$app->post('/user/add', function...``` with some posted data how to pass them to convert method()?

**Comment by mathroc** [comment]
you might be able to do it with a converter but I wouldn't recommend it, do it inside the controller instead

**Comment by nimasdj** [comment]
@mathroc Thanks for the advice. so something like
```$vars  = $request->request->all();```
inside controller then pass $vars to method the same way like passing $em?
Or even this way is not recommended and better to avoid service and do it with simple function like I described in my first post?

**Comment by fabpot** [comment]
Closing as indeed, stackoverflow should be used for support.
