### ISSUE TITLE
Handling fatal errors, "ExceptionHandler::register()" does not work

### ISSUE THREAD

**Issue by rognoni** [silexphp/Silex#1415]
For my project I need to send all errors in JSONP format:

https://github.com/rognoni/adaptable/blob/master/Backend/PHP-Silex/web/index.php

``` php
$app = new Silex\Application();
ErrorHandler::register();
ExceptionHandler::register();
[...]
//throw new Exception('Division by zero.'); // Works $app->error(...)
$res = $storage->$args['method']($args['params']);
[...]
$app->error(function (\Exception $e, Request $request, $code) {
  $jRes = new JsonResponse(
    array('error'=> array('code'=> 0, 'message'=> 'Server error (see the stacktrace)', 'stacktrace'=> $e->getMessage().PHP_EOL.$e->getTraceAsString()))
    , 404 /* ignored */, array('X-Status-Code' => 200));
  $jRes->setCallback($request->get('callback'));
  return $jRes;
});
```

With the `throw new Exception(...)` works:

```
/**/function({"error":{"code":0,"message":"Server error (see the stacktrace)","stacktrace":"Division by zero...
```

but with the **fatal error** you see the default HTML error page:

```
Whoops, looks like something went wrong.
1/1 UndefinedMethodException in index.php line 30: Attempted to call an undefined method named "delete" of class "adaptable\storage\in_memory\Storage".

    in index.php line 30
```

**Comment by stof** [comment]
this is because ``$app->error`` does not run for fatal errors.

Recent versions of Symfony have a way to make usage of the kernel error rendering even for fatal errors (at least trying it as a first option), but I'm not sure it is possible to use it with Silex.

**Comment by tiemevanveen** [comment]
I'm having the same problem. Thanks for the heads up @stof. 

It seems there are a few issues with the same or related problem #1016, #1012, #1257. Could a best practice for this, (or if there isn't any, maybe some other description) be added to the docs? Because after reading about the [error handlers](http://silex.sensiolabs.org/doc/master/usage.html#error-handlers) and [converting errors](http://silex.sensiolabs.org/doc/master/cookbook/error_handler.html) this comes as a surprise.  

For now I'm using a tweaked version of @Duvo's [snippet](https://github.com/silexphp/Silex/issues/1016#issuecomment-184281542 ).  But I'm probably doing all kinds of things wrong.. 

https://gist.github.com/tiemevanveen/5810b7ed74a0a5ff25cd9918beccf55b

**Comment by lukaszwit** [comment]
I was surprised that 
```php
app->error(function (\Throwable $e, Request $request, $code) {
});
```
did not catch any \Error exceptions (native errors from PHP7). When I looked into source code there were \Exception type hints everywhere so this will not work obviously.
I've tried to handle \Error exception by my own handler that is emitting kernel exception event but somehow kernel.response event is not emitted by the framework for that case.

At least documentation should be clear about this but we should provide some working solution for this.

**Comment by hkdobrev** [comment]
Have you tried something like:

```php
use Symfony\Component\Debug\Exception\FatalThrowableError;

$app->error(function (FatalThrowableError $error, Request $request, $code) {
});
```

`FatalThrowableError` is the exception class which Symfony uses to wrap `Throwables` objects.

**Comment by stefan-endouble** [comment]
@hkdobrev tried it and it does not work, only managed to capture with: 
```
register_shutdown_function(function() {
    http_response_code(500);
});
```

**Comment by hkdobrev** [comment]
Does the error triggering `UndefinedMethodException` happens during the of the request or is it something prior to that? E.g. configuring the container?

**Comment by fabpot** [comment]
Closing as there is no more feedback.
