### ISSUE TITLE
Silex 1.3.5 breaks in php5.3

### ISSUE THREAD

**Issue by jordanlev** [silexphp/Silex#1416]
Since the update from 1.3.4 to 1.3.5, I am unable to run Silex under PHP 5.3 (5.3.29). This very basic example fails:

	<?php
	require_once __DIR__.'/vendor/autoload.php';
	$app = new Silex\Application();
	$app->get('/', function () {
		return 'hello world';
	});
	$app->run();

...this yields the error `Catchable fatal error: Argument 2 passed to Symfony\Component\HttpKernel\Event\FilterControllerEvent::__construct() must be an instance of Symfony\Component\HttpKernel\Event\callable, instance of Closure given`

I have a more complex application that is also failing under PHP 5.3 (but works just fine under PHP 5.5), yielding this error: `Fatal error: Class 'SessionHandler' not found in [...]vendor/symfony/http-foundation/Session/Storage/Handler/NativeSessionHandler.php on line 20`

My understanding is that Silex 1.3 was going to be maintained until 2017, and that PHP 5.3 has always been the minimum version requirement (I don't see anything in the changelog stating that this has changed).

Thanks.

**Comment by fabpot** [comment]
Silex 1.3 should indeed work with PHP 5.3... but it really depends on which versions of the Symfony components are installed. Can you check that you don't have any Symfony 3 components in your project?

**Comment by jordanlev** [comment]
My composer.json file only contains this:

	{
	    "require": {
	        "silex/silex": "~1.0"
	    }
	}

...but looking at the composer.lock file, I do see some version 3's of the symfony components (I won't paste it here because it's very long, but if you want me to I can).

So is this a result of silex v1 not declaring its dependencies correctly, or do I need to add some sort of flag when I run "composer install" (or "composer update") to tell it not to give me symfony v3 components? (I'm not super familiar with the ins and outs of composer, I just paste the commands I see in the installation docs and pray for the best :)

Thank you.

**Comment by GromNaN** [comment]
What version of PHP do you have if you type "php -v" ? You may have a different version in cli and web.
Try to remove the composer.lock and run `composer update`.

You can also declare symfony dependencies explicitely: 
```json
    "require": {
        "silex/silex": "~1.0",
        "symfony/event-dispatcher": "2.8.*",
        "symfony/http-foundation": "2.8.*",
        "symfony/http-kernel": "2.8.*",
        "symfony/routing": "2.8.*"
    }
```

**Comment by jdreesen** [comment]
Or you may specify the PHP version of your production system explicitely in your composer.json file like this:

```json
    "config": {
		"platform": {
			"php": "5.3.29"
		}
	}
```

This will instruct composer to only install libs compatible with this PHP version, even if you run `composer update` on a system with a newer PHP version.

**Comment by jordanlev** [comment]
Ah, yes I see -- my command-line version of PHP is 5.5. Setting the "config" in composer.json did not work for me, but explicitly setting the symfony component version numbers did. Thank you all for the help!
