### ISSUE TITLE
Monolog to the Syslog?

### ISSUE THREAD

**Issue by rayfoss** [silexphp/Silex#1421]
How would I get the Silex version of monolog to log to the System log? I see that the monolog-bridge is installed and not monolog-bundle

In Symfony I could do something like the following:
```
$container->loadFromExtension('monolog', array(
        'syslog_handler' => array(
            'type'  => 'syslog',
            'level' => 'error',
        ),
    ),
));
```

The Skeleton comes with the following config
```
$app->register(new MonologServiceProvider(), array(
    'monolog.logfile' => __DIR__.'/../var/logs/silex_dev.log',
));
```

Logging to a file is very slow on app engine as there is no way to append, only "read and overwrite."

**Comment by SpacePossum** [comment]
you can do this like this for example (Silex 2.0):
```php
$app->register(
    new Silex\Provider\MonologServiceProvider(),
    [
        'monolog.logfile' => $projectRoot.'log/monolog/'.$app['env'].'.log',
        'monolog.name' => $app['name'],
        'monolog.level' => $level,
        'monolog.handler' => new \Monolog\Handler\SyslogHandler($ident, $facility, Logger::ERROR),
    ]
);
```

**Comment by rayfoss** [comment]
I did dig through docs for this, and I was very close to the answer... my next step would have been to step through the source. If monolog.handler had been set to the default handler manually, this would have been a bit more discoverable. If monolog is important enough to be manually spelled out in the configs, perhaps a room for improvement in discoverability could be a bug in this case? depending on how common reconfiguring it is.

**Comment by SpacePossum** [comment]
not sure I understand the possible bug you describe, but upping the docs might be a good a idea :)
