### ISSUE TITLE
Documentation about error handlers is outdated or wrong 

### ISSUE THREAD

**Issue by mindcreations** [silexphp/Silex#1424]
Documentation about setting a custom error handler [here] (http://silex.sensiolabs.org/doc/master/usage.html#error-handlers) states with this example how to set a custom error handler:

```php
$app->error(function (\Exception $e, Request $request, $code) {
    return new Response('We are sorry, but something went terribly wrong.');
});
```

I've tried and returns:

:collision: _Catchable fatal error: Argument 2 passed to {closure}() must be an instance of Symfony\Component\HttpFoundation\Request, integer given in ..._ 

I've fixed the error by coding this way:

```php
$app->error(function (\Exception $e) {
    return new Response('We are sorry, but something went terribly wrong.');
});
```
even the following example in the doc is wrong IMHO:

```php
$app->error(function (\Exception $e, Request $request, $code) {
    switch ($code) {
        case 404:
            $message = 'The requested page could not be found.';
            break;
        default:
            $message = 'We are sorry, but something went terribly wrong.';
    }
    return new Response($message);
});
```

The working code I use is:

```php
$app->error(function (\Exception $e) {
    switch ($e->getStatusCode()) {
        case 404:
            $message = 'The requested page could not be found.';
            break;
        case 400:
            $message = $e->getMessage();
            break;
        default:
            $message = 'We are sorry, but something went terribly wrong.';
    }
    return new Response($message);
});
```

I think documentation should be fixed or... please tell me what I've not understood.

**Comment by SpacePossum** [comment]
I cannot reproduce this error, can you provide `$ php -v` and the version of Silex you are using?

**Comment by mindcreations** [comment]
PHP 5.5.38-3+deb.sury.org~xenial+1 (cli) 
Silex 1.3.5

I've seen docs for 1.3.5 and are correct.

Sorry for opening a misleading issue.
