### ISSUE TITLE
middleware finish is run before the result is send to the client

### ISSUE THREAD

**Issue by marcelloh** [silexphp/Silex#1435]
I'm not sure, but I want to generate the pdf in the finish(), because it takes some time, and don't want the user to wait for it.

As a simple test I have this code:
```
$app->finish(function (Request $request, Response $response)
{
    sleep(5);     // here would be my pdf generation trickery
});
```
and now every screen has to wait 5 extra seconds before they show. My conclusion is, that the finish middleware still stalls the client until finish is finished. 

The manual states:

> A finish application middleware allows you to execute tasks after the Response has been sent to the client (like sending emails or logging):

I think, with this short code, I have a "situation", or do I misinterpret the manual explanation?

**Comment by stof** [comment]
how are you running your application ? Sending the response before executing finish is possible only when using php-fpm (it relies on ``fastcgi_finish_request``). When using other setups (apache+mod_php for instance), there is no way to do it, and so it delays the response.

**Comment by marcelloh** [comment]
If that is the case, why isn't there a mention of this in the documentation?
When I try to find out, if that is true, I found the aswer burried away:
http://symfony.com/doc/current/components/http_kernel.html#component-http-kernel-kernel-terminate

> Internally, the HttpKernel makes use of the fastcgi_finish_request PHP function. This means that at the moment, only the PHP FPM server API is able to send a response to the client while the server's PHP process still performs some tasks. With all other server APIs, listeners to kernel.terminate are still executed, but the response is not sent to the client until they are all completed.

So case closed. I want my program to work always, no matter what platform, or php implementation.
