### ISSUE TITLE
Role different between SF3 and Silex2 in BDD

### ISSUE THREAD

**Issue by corgato** [silexphp/Silex#1436]
Hello,

I have a project under Symfony3 and api under Silex 2.
I have a problem I can not solve. The isGranted() function does not work under the Silex project because the user role is in store serialize form while Silex uses an array and not a serialize.

So Silex always returns false to me when I test the role of a user ...

I can not override the class User because it is final class

Is there a solution ?

Thank you.

**Comment by GromNaN** [comment]
The final class [`User`](https://github.com/symfony/symfony/blob/v3.1.5/src/Symfony/Component/Security/Core/User/User.php) is only defined for the [`InMemoryUserProvider`](https://github.com/symfony/symfony/blob/v3.1.5/src/Symfony/Component/Security/Core/User/InMemoryUserProvider.php).

What are you using to store users in database ?
To read this database from Silex, you have to code your own `UserProvider` and [configure it](http://silex.sensiolabs.org/doc/master/providers/security.html#defining-a-custom-user-provider).

**Comment by GromNaN** [comment]
If you took the documentation example, you should replace this line:
```php
 return new User($user['username'], $user['password'], explode(',', $user['roles']), true, true, true, true);
```
By this:
```php
 return new User($user['username'], $user['password'], unserialize($user['roles']), true, true, true, true);
```

**Comment by corgato** [comment]
oh very good, the second response is perfect !

Thanks !
