### ISSUE TITLE
How apply dry to App DI.

### ISSUE THREAD

**Issue by aymone** [silexphp/Silex#1439]
Hi, 

I have tried many ways to out from this:

`
 $app->register(new DoctrineServiceProvider(), [
  'db.options' => [
          'key' => values
       ]
   ]);
`

to something like this:
 
`    use SomeCallbackReturnsProviderAndConf; //sample`

`    $app->register(SomeCallbackReturnsProviderAndConf());`

When i have many service providers and confs, the app file grows to uggly big file.

Theres any way to separate register methods to segmented files?

**Comment by aymone** [comment]
http://pimple.sensiolabs.org/#extending-a-container

**Comment by namaless** [comment]
@aymone instead of create some services in one file you can create a group of services and loading with a new service provider, example:

```php
class BaseAppProvider implements Pimple\ServiceProviderInterface
{
    public function register(Container $c)
    {
        $this->registerDB();
        $this->registerCache();
        $this->registerMyService($c);
    }

    protected function registerDB()
    {
        parent::register(new DoctrineServiceProvider(), [
            'db.options' => [
                'key' => 'value'
            ]
        ]);
    }

    protected function registerCache()
    {
        parent::register(new CacheServiceProvider(), [
            'path' => __DIR__ . '/cache'
        ]);
    }

    protected function registerMyService(Container $container)
    {
        $container['MyService'] = function ($c) {
            return new MyService([
                'key' => 'value'
            ]);
        };
    }
}
```

In case for few project you can extend this service provider and replace only one method instead rewrite anything all times. I do this in the past when I use Silex instead of Symfony Micro Edition.

**Comment by aymone** [comment]
thanks @namaless
