### ISSUE TITLE
Should the list of contributors be updated?

### ISSUE THREAD

**Issue by javiereguiluz** [silexphp/Silex#1440]
In this page http://silex.sensiolabs.org/contributors:
- It says that 113 developers have contributed code ...
- ... but it lists 156 developers

Besides:
- GitHub says that there are 214 contributors (https://github.com/silexphp/Silex/graphs/contributors)
- And analyzing the Git logs you get +300 contributors

**Comment by fabpot** [comment]
Everything looks good to me. Keep in mind that we have 2 lists: one for code, one for docs.
