### ISSUE TITLE
Conflict between monolog-bridge and web-profiler

### ISSUE THREAD

**Issue by bpesquet** [silexphp/Silex#1443]
Hi,

i'm migrating a Silex app from 1.3 to 2.0. For stability reasons, I target Symfony 2.8 LTS in my `composer.json` file:

```json
{
    "require": {
        "silex/silex": "2.0.*",
        "doctrine/dbal": "2.5.*",
        "twig/twig": "1.26.*",
        "symfony/twig-bridge": "2.8.*",
        "symfony/asset": "2.8.*",
        "symfony/security": "2.8.*",
        "symfony/form": "2.8.*",
        "symfony/translation": "2.8.*",
        "symfony/config": "2.8.*",
        "twig/extensions": "1.4.*",
        "symfony/validator": "2.8.*",
        "symfony/monolog-bridge": "2.8.*",
        "silex/web-profiler": "2.0.*"
    },
    "require-dev": {
        "phpunit/phpunit": "4.8.*",
        "symfony/browser-kit": "2.8.*",
        "symfony/css-selector": "2.8.*"
    }
}
```

Problem is, `monolog-bridge` needs `http-kernel` 2.8 (https://github.com/silexphp/Silex-Skeleton/issues/60) and `web-profiler` needs `http-kernel` 3.1 (https://github.com/silexphp/Silex-WebProfiler/issues/94). 

Am I missing something here? Is there a way to satisfy both requirements?
Thanks in advance.

**Comment by rwitchell** [comment]
this isn't an issue for me - i'm guessing they fixed the requirement bug.

**Comment by bpesquet** [comment]
Probably. I'm closing this.
