### ISSUE TITLE
DoctrineServiceProvider: remove null !== $app['logger]

### ISSUE THREAD

**Issue by dominikzogg** [silexphp/Silex#1446]
https://github.com/silexphp/Silex-Providers/blob/master/DoctrineServiceProvider.php#L88

I would like to create PR , that removes the check if $app['logger] is !== null, in my point of view, $app['logger'] should never be set without a psr3 compatible logger. At the moment, the logger get instantiated for nothing if class Symfony\Bridge\Doctrine\Logger\DbalLogger does not exists.

**Comment by SpacePossum** [comment]
https://github.com/silexphp/Silex/blob/master/src/Silex/Application.php

The thing is that the application always set the logger (to null). So if you remove the check for null and the logger class is loaded the service will log, even if there is no logger set.

**Comment by dominikzogg** [comment]
Then we should fix that my setting NullLogger as a default.

**Comment by dominikzogg** [comment]
@SpacePossum would need to add psr/log and could break something else. @fabpot please do not accept or add defaults with null for services again, this ends in unsolvable task.
