### ISSUE TITLE
How to set global app middleware

### ISSUE THREAD

**Issue by arhatal** [silexphp/Silex#1447]
$app->before(...) running only with if request match routing. 
How to make middleware with access to request vars that works on any request?

**Comment by GromNaN** [comment]
The solution may be [StackPHP](http://stackphp.com/)

**Comment by skalpa** [comment]
There is no Silex-specific method to do this, but you can manually register an event handler that listens to the `KernelEvents::REQUEST` event:

```php
use Symfony\Component\HttpKernel\KernelEvents;

$app->on(KernelEvents::REQUEST, function ($event) {
    $request = $event->getRequest();
    // ...
});
```
