### ISSUE TITLE
Class 'Symfony\Bridge\Twig\Extension\HttpKernelRuntime' not found

### ISSUE THREAD

**Issue by eman1986** [silexphp/Silex#1448]
I recently updated my copy of silex, twig, and twig bridge and looks like silex is now broken with a change to the twig bridge:

> Class 'Symfony\Bridge\Twig\Extension\HttpKernelRuntime' not found

**Comment by eman1986** [comment]
reverting to 2.0.3 resolved the issue for me, so 2.0.4 has an issue

**Comment by f3ath** [comment]
Can confirm this. The class is referred from here https://github.com/silexphp/Silex/blob/v2.0.4/src/Silex/Provider/TwigServiceProvider.php#L28, but it does not present here https://github.com/symfony/twig-bridge/tree/v3.1.6/Extension.

**Comment by SpacePossum** [comment]
possible duplicate of https://github.com/silexphp/Silex/pull/1449 ?

**Comment by danielmartincmp** [comment]
Any fix on this issue?

**Comment by hkdobrev** [comment]
I've tried to fix that in #1612.
