### ISSUE TITLE
Update Silex to replace usage of X-Status-Code header

### ISSUE THREAD

**Issue by jameshalsall** [silexphp/Silex#1450]
When https://github.com/symfony/symfony/pull/19822 gets merged to replace the usage of `X-Status-Code` with a better alternative we will need to update Silex accordingly.

This is just a placeholder to remind me that needs to be done when the HttpKernel PR is merged.

**Comment by fabpot** [comment]
What about creating the PR now? We know that tests won't pass yet, but at least, we would be able to review change beforehand.

**Comment by jameshalsall** [comment]
@fabpot Indeed, that's a good idea. However I'm still not even sure how this will work - we may need to make wider changes to Silex (I haven't used Silex for a couple of years now).

As soon as I've finished on the HttpKernel PR I'll start on the PR for Silex, will be sometime this week.

**Comment by fabpot** [comment]
Sounds great. Thanks a lot for your work on this topic. Much appreciated.

**Comment by fabpot** [comment]
@jameshalsall Still interested in submitting a pull request for this?

**Comment by hkdobrev** [comment]
I've submitted a PR addressing this with doc updates as well.
