### ISSUE TITLE
SecurityProvider: login form: error handling with custom UserProvider

### ISSUE THREAD

**Issue by MacDada** [silexphp/Silex#1458]
Hi,

This is the code I have with Silex 2: https://gist.github.com/MacDada/517e3e63139ac8a74c5246483e24c9b6

The problem is: whatever `ClientId` constructor throws, it's shown to the user.

So, for example, if the user doesn't type a client id starting with `IL`, he/she gets `ClientId value must be prefixed with "IL", "foo" given`.

IMHO it's not a good idea. What if the object would throw some sensitive information? Like database credentials? Neither website documentation nor phpdocs say that the component would behave like that.

So, I guess I should do this in my UserProvider:

```php
public function loadUserByUsername($username)
{
    try {
        $client = $this->clientRepository->findOneByClientId(
            new ClientId((string) $username)
        );
    } catch (\Exception $ex) {
        throw new UsernameNotFoundException('', 0, $ex);
    }

    if (null === $client) {
        throw new UsernameNotFoundException();
    }

    return new User(
        (string) $client->getClientId(),
        $client->getEncodedPassword(),
        ['ROLE_USER']
    );
}
```

Which is to catch any exception that "my" code would throw, so that it doesn't get passed to the user.

Is that a common practice? If so, shouldn't it be recommended in the docs?

---

BTW, if the username (client id) is not passed, I get `ClientId value must be prefixed with "IL", "NONE_PROVIDED" given`. That's an ugly hack :-P I'd expect null or empty string when none value is provided :-P

**Comment by MatTheCat** [comment]
`\InvalidArgumentException` extends `\LogicException`.

> This kind of exception should lead directly to a fix in your code.
> http://php.net/manual/en/class.logicexception.php

You shouldn't create an instance of `ClientId` if you know the "username" is invalid. Checking the username let you create a valid `ClientId` or throw a `CustomUserMessageAuthenticationException`.

**Comment by fabpot** [comment]
Closing this issue as there is no more activity.
