### ISSUE TITLE
SecurityProvider: i18n translation

### ISSUE THREAD

**Issue by MacDada** [silexphp/Silex#1459]
My `UserProvider` looks like this:

```php
public function loadUserByUsername($username)
{
    // https://github.com/silexphp/Silex/issues/1458
    try {
        $client = $this->clientRepository->findOneByClientId(
            new ClientId((string) $username)
        );
    } catch (\Exception $ex) {
        throw new UsernameNotFoundException('', 0, $ex);
    }

    if (null === $client) {
        throw new UsernameNotFoundException();
    }

    return new User(
        (string) $client->getClientId(),
        $client->getEncodedPassword(),
        ['ROLE_USER']
    );
}
```

The error messages are printed with Twig by `{{ error }}` and the variable is is in the controller with `'error' => $this['security.last_error']($request),`

Now, if something goes wrong, i.e. username (client id) was not given, the user gets `Bad credentials.` error. 

How do I translate this error or create custom errors to be translated?

**Comment by MatTheCat** [comment]
`AuthenticationException` defines `getMessageKey` and `getMessageData`.

Translations are defined in the Symfony Security component under the `security` domain.

```twig
{{ error.messageKey|trans(error.messageData, 'security') }}
```

**Comment by HeahDude** [comment]
Can be closed since the good answer was given.

**Comment by Simperfit** [comment]
ping @javiereguiluz

**Comment by javiereguiluz** [comment]
@Simperfit I don't have enough permissions to close issues on the Silex org.
