### ISSUE TITLE
set default redirect to 307

### ISSUE THREAD

**Issue by abkarino** [silexphp/Silex#1460]
Is there a way to make all redirects including `/foo` to `/foo/` using 307 redirect instead of 301 ?
Just need a good solution to handle trailing slashes.

**Comment by vetali** [comment]
I think you want to do that in your htaccess file, like this:
`    RewriteCond %{REQUEST_FILENAME} !-f`
`     RewriteRule ^(.*[^/])$ /$1/ [L,R=301]`

**Comment by abkarino** [comment]
So you mean like this to have the browser to retain POST data?
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^(.*[^/])$ /$1/ [L,R=307]

**Comment by vetali** [comment]
Yes, redirect 307 guarantees that the redirect will not change the method and the body of the request.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307

**Comment by abkarino** [comment]
So there is no

**Comment by abkarino** [comment]
But there is no way of doing that through the script ?
