### ISSUE TITLE
Silex 1.3.3+ doesn't work on PHP 5.4 anymore without noticing

### ISSUE THREAD

**Issue by kgkg** [silexphp/Silex#1462]
The last working version is 1.3.2, probably because of dispather. No notice because of that in changelog.

What I get is:
Your requirements could not be resolved to an installable set of packages.

Problem 1
- Installation request for symfony/debug v3.2.0 -> satisfiable by symfony/debug[v3.2.0].
- symfony/debug v3.2.0 requires php >=5.5.9 -> your PHP version (5.4.45) does not satisfy that requirement.
Problem 2
- Installation request for symfony/event-dispatcher v3.0.9 -> satisfiable by symfony/event-dispatcher[v3.0.9].
- symfony/event-dispatcher v3.0.9 requires php >=5.5.9 -> your PHP version (5.4.45) does not satisfy that requirement.
Problem 3
- Installation request for symfony/http-foundation v3.0.9 -> satisfiable by symfony/http-foundation[v3.0.9].
- symfony/http-foundation v3.0.9 requires php >=5.5.9 -> your PHP version (5.4.45) does not satisfy that requirement.
Problem 4
- Installation request for symfony/http-kernel v3.0.9 -> satisfiable by symfony/http-kernel[v3.0.9].
- symfony/http-kernel v3.0.9 requires php >=5.5.9 -> your PHP version (5.4.45) does not satisfy that requirement.
Problem 5
- Installation request for symfony/routing v3.0.9 -> satisfiable by symfony/routing[v3.0.9].
- symfony/routing v3.0.9 requires php >=5.5.9 -> your PHP version (5.4.45) does not satisfy that requirement.
Problem 6
- symfony/event-dispatcher v3.0.9 requires php >=5.5.9 -> your PHP version (5.4.45) does not satisfy that requirement.
- silex/silex v1.3.3 requires symfony/event-dispatcher ~2.3|3.0.* -> satisfiable by symfony/event-dispatcher[v3.0.9].
- Installation request for silex/silex v1.3.3 -> satisfiable by silex/silex[v1.3.3].

**Comment by kgkg** [comment]
Current workaround: 
`  "require": {
    "symfony/event-dispatcher": "~2.3",
    "symfony/http-foundation": "~2.3",
    "symfony/routing": "~2.3",
    "symfony/http-kernel": "~2.3",
    "symfony/debug": "~2.3",

    "silex/silex": "~1.3"
  },
`

**Comment by derrabus** [comment]
This is odd. Composer should not try to install Symfony 3 packages if you're on php 5.4. Are you using the latest version of composer? Maybe you want to report this problem to the composer project instead.

**Comment by xabbuh** [comment]
Can you show your `composer.json` as it was when you got this error?

**Comment by rubenvincenten** [comment]
Not a silex issue, but a composer issue.

It depends on the CLI PHP version. If you want to force libraries for a different PHP version, use the platform configuration option (I have PHP 5.6 to test locally, but I need to write for 5.3 environments)

```json
{
  "config": {
    "platform": {
      "php":"5.3.10"
    }
  },
  "require":{
  }
}
```

**Comment by kgkg** [comment]
@rubenvincenten thank you, manually setting platform version solved my problem.
