### ISSUE TITLE
Session Lifetime Isn't Working

### ISSUE THREAD

**Issue by moisespio** [silexphp/Silex#1464]
For some reason the session lifetime is not working for me. 
What I did:

```
$app->register(new Silex\Provider\SessionServiceProvider());

$app['session.storage.options'] = [
    'cookie_lifetime' => 1
];

$app['session']->set('user', 'my_user');
```

The session keeps alive forever and I don't know why.
Something changed? I'm doing something wrong?

Thanks.

**Comment by sangio90** [comment]
can you be more precise?
I cannot replicate the issue.
Have you tried to go to the output of **sys_get_temp_dir**() (session default path) and check that every second or two (i used 2 secs for my tests) if you make a new request Silex generates a new session file? In my case it works as expected, Chrome loses the Cookie and a new sess_ file is created and added as a new Cookie.
I'm using Silex 2.1.

**Comment by fabpot** [comment]
Closing as there is no feedback from the reporter.
