### ISSUE TITLE
Response.php in function sendHeaders() setDate() requires instance variable

### ISSUE THREAD

**Issue by jystraya** [silexphp/Silex#1469]
Apache Warning: PHP Warning:  DateTime::createFromFormat(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in ---\\vendor\\symfony\\http-foundation\\Response.php on line 374

Suggested quick fix:

if (!$this->headers->has('Date')) {
    $this->setDate(new \DateTime());
}

**Comment by jystraya** [comment]
Actually, sorry, this was another thing I had tinkering with the code. 

setDate() sets it to UTC of course.  But still, this gets rid of the warning, and setDate() runs and does its thing without generating this warning, giving 500 Internal Server Error responses in development.

**Comment by ragboyjr** [comment]
You need to set your timezone in the INI file or at the beginning of the request. This isn't a silex related bug.
