### ISSUE TITLE
htaccess docu not working

### ISSUE THREAD

**Issue by rogoit** [silexphp/Silex#1474]
Hi Silex,

in the docu on http://silex.sensiolabs.org/doc/2.0/web_servers.html is

`<IfModule mod_rewrite.c>
    Options -MultiViews

    RewriteEngine On
    #RewriteBase /path/to/app
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [QSA,L]
</IfModule>`

Please remove the -d line. Otherwise routes are not working for me.

See you
Roland

**Comment by tarrsalah** [comment]
I came across the same issue, when I add the `RewriteCond %{REQUEST_FILENAME} !-d` condition, I can't reach the `/` path.

**Comment by rogoit** [comment]
When you run local put this to index_dev.php and index.php

`$filename = __DIR__.preg_replace('#(\?.*)$#', '', $_SERVER['REQUEST_URI']);
if (php_sapi_name() === 'cli-server' && is_file($filename)) {
    return false;
}`

**Comment by fabpot** [comment]
Closing as support should probably be done on StackOverflow.
