### ISSUE TITLE
using predis as a service

### ISSUE THREAD

**Issue by luchianenco** [silexphp/Silex#1475]
I want to use predis in my app based on Silex 1.3
so I installed https://github.com/nrk/PredisServiceProvider/tree/v1.0
and added in index.php

`
    $app->register(new Predis\Silex\ClientServiceProvider(), [ 
        'predis.parameters' => $container->getParameter('redis_config.host'), 
        'predis.options'    => [ 
            'prefix'  => $container->getParameter('redis_config.prefix'), 
            'profile' => $container->getParameter('redis_config.profile'), 
        ], 
    ]);
`

how can access the predis in service.yml?
I tried to do it like this:

`quotaValidator:
    class: Api\Quota\Validator
    arguments: [@userRepository, @predis]`

but predis is not found. How can I manage this? thank you

**Comment by stof** [comment]
There is no services.yml in Silex

**Comment by luchianenco** [comment]
ah.. :) thanks for the hint, I understood how to manage this =)
