### ISSUE TITLE
Silex and doctrine

### ISSUE THREAD

**Issue by yuioppooh** [silexphp/Silex#1476]
Hello,

Is it possible to integrate doctrine in the same way as under Symfony?
For example, using "annotations", "persist", "flush", etc ...

As the project is still fairly recent I have found only obsolete solutions ...

Thank you.

**Comment by mathroc** [comment]
you probably want https://github.com/dflydev/dflydev-doctrine-orm-service-provider maybe with https://github.com/saxulum/saxulum-doctrine-orm-manager-registry-provider

**Comment by GromNaN** [comment]
If you need to use Doctrine ORM, Silex may not be best available choice: you will end up rewriting a lot of things that are native in Symfony Framework.

If you want something Silex-like with a lightweight configuration, you should have a look to the [`MicroKernel`](http://symfony.com/blog/new-in-symfony-2-8-symfony-as-a-microframework).
