### ISSUE TITLE
ParameterBag issues with type return

### ISSUE THREAD

**Issue by tolbon** [silexphp/Silex#1479]
Hi All,

I have got an issue with ParameterBag of HttpFoundation

I use this method
```php
    /**
     * Returns the alphabetic characters and digits of the parameter value.
     *
     * @param string $key     The parameter key
     * @param string $default The default value if the parameter key does not exist
     *
     * @return string The filtered value
     */
    public function getAlnum($key, $default = '')
    {
        return preg_replace('/[^[:alnum:]]/', '', $this->get($key, $default));
    }
```

and other methods like `getInt()`, `getAlpha()`

If my URL is http://my/url?param=stuff
it works great 
but for testing purpose I tried to pass an array like this http://my/url?param[]=stuff&param[]=stuff2
`getAlnum` return an array
and `getInt` return (int) 1

Is a bug or do I something wrong ?

**Comment by alborq** [comment]
This issue must be reported in symfony/symfony repository, behavior is good but PhpDoc is wrong, must change to @return mixed,

**Comment by tolbon** [comment]
I report this than an issue in symfony repo 
https://github.com/symfony/symfony/issues/21386
