### ISSUE TITLE
Can't set the security default encoder to PlaintextPassword

### ISSUE THREAD

**Issue by tarrsalah** [silexphp/Silex#1480]
After var_dumping inside my `vendor` directory, I can see clearly that `Silex ` is still using `BCryptPasswordEncoder` to encode passwords after setting `security.default_encoder` to `PlaintextPasswordEncoder`,
```
$app['security.default_encoder'] = function ($app) {
    return new \Symfony\Component\Security\Core\Encoder\PlaintextPasswordEncoder();
};
```

Anyone have an idea? a **bug** or am I missing something?

**Comment by stof** [comment]
are you sure that your assignment is executed ? And is it executed soon enough (i.e. before starting to use Silex services) ?

**Comment by tarrsalah** [comment]
Here is my configurations:

```
// security
$app['security.default_encoder'] = function ($app) {
    return new \Symfony\Component\Security\Core\Encoder\PlaintextPasswordEncoder();
};

$userProvider = function () {
    return new InMemoryUserProvider([
        'admin' => ['password' => 'admin']
    ]);
};


$app['security.firewalls'] = [
    'admin' => [
        'pattern' => '^/admin',
        'form' => array(
            'login_path' => '/login', 
            'check_path' => '/admin/login_check',
        ),
        'logout' => array('logout_path' => '/admin/logout', 'invalidate_session' => true),
        'users' => $userProvider,
    ],
];

// var_dump($app['security.default_encoder']);
$app->register(new Silex\Provider\SessionServiceProvider());
$app->register(new Silex\Provider\SecurityServiceProvider());

```

**Comment by stof** [comment]
you must overwrite the ``$app['security.default_encoder']`` service *after* registering the SecurityServiceProvider. The last definition of a service wins, and the last one is the Silex one (i.e. bcrypt) in your code above.

Btw, this is true also for ``$app['security.firewalls']``

**Comment by tarrsalah** [comment]
I can't thank you enough @stof , saving me hours!
Sorry if it's not the appropriate place to post such questions.
