### ISSUE TITLE
Incompatible with PHPUnit 6.*

### ISSUE THREAD

**Issue by sneps85** [silexphp/Silex#1483]
Actual version is not compatible with PHPUnit 6.* as \PHPUnit_Framework_TestCase now uses namespaces. Also, PHPUnit 6.* requires PHP 7

**Comment by ry167** [comment]
This actually was a huge pain. I was getting `PHP Fatal error:  Class 'PHPUnit_Framework_TestCase' not found in {PROJECT_DIR}/vendor/silex/silex/src/Silex/WebTestCase.php on line 22` as the error from this.

Change your `composer.json` lien for PHPUnit to `"phpunit/phpunit": "~5.7"`

Silex has `WebTestCase` which depends on PHPUnit, so it probably should be in `require-dev` for Silex...

**Comment by araneta** [comment]
i tried to use phpunit 5.7 with php7 and i got this message when running phpunit . : No tests executed!
tests are not working. what should i do?

**Comment by ry167** [comment]
@araneta Was `No tests executed` the only error message you received?

**Comment by jeanpralo** [comment]
Definitely a big of a headache.

Related problem on symfony:
https://github.com/symfony/symfony/issues/21534

**Comment by adamcameron** [comment]
I think short-term Silex ought to be patched to restrict the PHPUnit version to 5.x (ie: via its composer.json). That said, using 5.x is no use to me... I need to be using 6.x as the rest of my tests are 6.x.

No worries, I can work around it. Just thought it worthwhile adding a "me too" here. Sorry :-S

**Comment by curry684** [comment]
@adamcameron my workaround at https://github.com/symfony/symfony/issues/21534#issuecomment-278278352 is cleaner and more resilient. You can just put it in phpunit's bootstrap file in your own project.

**Comment by adamcameron** [comment]
@curry684 cool: nice one!

**Comment by fabpot** [comment]
Closing this one as PHPUnit won't be added to the `require` section of Silex as it's a soft dependency. The workaround mentioned by @curry684 looks the way to go.

**Comment by adamcameron** [comment]
Yeah entirely fair enough. Cheers!

**Comment by sinasalek** [comment]
There is also another workaround using composer directly. there is a plugin for class aliasing. This way there no need to change anything else. it can also be added to silex composer till it is fixed properly
https://github.com/TYPO3/class-alias-loader
