### ISSUE TITLE
SwiftmailerServiceProvider configuration

### ISSUE THREAD

**Issue by ramadom** [silexphp/Silex#1486]
Silex\Provider\SwiftmailerServiceProvider resets configuration parameters that were set before register. $app['swiftmailer.options'] becomes empty after SwiftmailerProvider is registered.

```
class SwiftmailerServiceProvider implements ServiceProviderInterface, EventListenerProviderInterface
{
    public function register(Container $app)
    {
        $app['swiftmailer.options'] = array();  // Works correctly if this line is removed

```

**Comment by mathroc** [comment]
this is the expected behavior for all silex providers. you should override providers configurations *after* registering them (or with the second argument of `$app->register()`)

**Comment by stof** [comment]
and this is the behavior of **all** Silex providers

**Comment by ramadom** [comment]
Yes, all providers reset options..  To use existing options would seem like a nicer behavior, but if it is expected it means it is correct.
