### ISSUE TITLE
No log about fatal error php

### ISSUE THREAD

**Issue by silverpark** [silexphp/Silex#1488]
Hi,

I have a problem about log of fatal error php, i have an app in silex 1.3 and was migrate to silex 2. From migration to silex 2 there are no log when there are fatal errors php.

Silex2 catch probably fatal errors php, but i am not in debug mode.

After reading the documentation i have added this code `ExceptionHandler::register($app['debug']);`
But there are an error php :
```
[error] 10#10: *11 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Symfony\Component\Debug\ExceptionHandler::handle() must be an instance of Exception, instance of Error given in /var/www/morpheus-api/vendor/symfony/debug/ExceptionHandler.php:106
Stack trace:
#0 [internal function]: Symfony\Component\Debug\ExceptionHandler->handle(Object(Error))
#1 /var/www/morpheus-api/vendor/monolog/monolog/src/Monolog/ErrorHandler.php(137): call_user_func(Array, Object(Error))
#2 [internal function]: Monolog\ErrorHandler->handleException(Object(Error))
```

What is the solution ?

Regards,

**Comment by frostieDE** [comment]
Have you tried registering the `ErrorHandler`? See http://silex.sensiolabs.org/doc/2.0/cookbook/error_handler.html

**Comment by SpacePossum** [comment]
you might want to check out https://github.com/silexphp/Silex/issues/1016 it has some good pointers about fatal errors and the error handler, in short the handler won't catch them (https://github.com/silexphp/Silex/issues/1016#issuecomment-55883583)

**Comment by silverpark** [comment]
@frostieDE Yes i have tried registering the ErrorHandler, but an error about ErrorHandler function is throw like describe above.

@SpacePossum I look, I come back to you.

**Comment by fabpot** [comment]
Closing as there is no more activity here.
