### ISSUE TITLE
Is there a doctrine command line tool for silex like symfony to generate entity? 

### ISSUE THREAD

**Issue by zjsxwc** [silexphp/Silex#1492]
Is there a doctrine command line tool for silex like symfony to help generate entity?

**Comment by SpacePossum** [comment]
There is not one in this repository.
You either have to look for 3rd party providers or write one yourself (there are some ok blogs on this).

**Comment by crowincage** [comment]
If you're using doctrine ORM the console commands for generating entities are part of the doctrine package (see https://github.com/doctrine/doctrine2/tree/master/lib/Doctrine/ORM/Tools/Console/Command).

If you're using the symfony console component in your silex project you just can add the doctrine commands.
