### ISSUE TITLE
RememberMe service incompatible with memcached stored sessions

### ISSUE THREAD

**Issue by vamenard** [silexphp/Silex#1493]
We came accross an issue with the RememberMe service used with memcached stored sessions.

It does not take this into account regarding memcached :
http://php.net/manual/en/memcached.sessions.php#115306

"If you are setting data to the session and it immediately disappears and you aren't getting any warnings in your PHP error log, it's probably because your sessions expired sometime in the 1970s.

Somewhere between memcached 1.0.2 and 2.1.0, the memcached session handler became sensitive to the 30-day TTL gotcha (aka "transparent failover").  If your session.gc_maxlifetime is greater than 2592000 (30 days), the value is treated as a unix timestamp instead of a relative seconds count."

I think the lifetime option in the RememberMeServiceProvider could be adjusted according to the session storage handler.

**Comment by GromNaN** [comment]
This is weird. Does it solve your issue if you specify the token lifetime like this:
```php
$app['security.firewalls'] = array(
    'my-firewall' => array(
        'remember_me' => array(
            'lifetime' => 60*60*24*30, // 30 days
        ),
    ),
);
```

Otherwise, can you paste a sample of the code you are using ?

**Comment by vamenard** [comment]
Our failed autologin was triggered by an Authentification exception thrown by mistake. The autologin seems to fail whenever an Authentification exception is thrown, which I'm guessing is normal. Memcached stored session works fine, this issue can be close.
