### ISSUE TITLE
Convert require-dev to suggest

### ISSUE THREAD

**Issue by alehaa** [silexphp/Silex#1495]
While packing Silex for debian, I noticed that the suggested extensions are listed as `requrie-dev` in `composer.json`. I wonder if there is a reason for this, because the composer docs say:

> require-dev (root-only)
>
> Lists packages required for developing this package, or running tests, etc. The dev requirements of the root package are installed by default. Both `install` or `update` support the `--no-dev` option that prevents dev dependencies from being installed.

But IMHO these packages enhance the functionality of Silex, so the `suggest` keyword might be a better choice, wouldn't it?

> suggest
>
> Suggested packages that can enhance or work well with this package. These are just informational and are displayed after the package is installed, to give your users a hint that they could add more packages, even though they are not strictly required.
> ...

**Comment by hkdobrev** [comment]
They are needed to test the service providers for these libraries.

**Comment by alehaa** [comment]
Okay that sounds reasonable.

Will it be safe to assume, that all dependencies listed in `require-dev` as suggests?

**Comment by fabpot** [comment]
Yes, that sounds reasonable.

**Comment by alehaa** [comment]
Thanks. ;)
