### ISSUE TITLE
Silex

### ISSUE THREAD

**Issue by simplyniceweb** [silexphp/Silex#1498]
@fabpot What will happen to Silex if Symfony Flex is out?

**Comment by GromNaN** [comment]
Silex is a framework, on top of Symfony **Components** and Pimple with ServiceProviders whereas Symfony Flex is a way to use the Symfony **Framework** and Bundles.

Both frameworks have their place in PHP ecosystem.

**Comment by GromNaN** [comment]
And @fabpot has [a big plan for Silex](https://twitter.com/fabpot/status/822145578465251328). He said
> Just sent an email to some #Silex #Pimple potential co-maintainers with the big plan! Very excited that so many people want to help.
> The big plan is what I think needs to be done on Silex. Mostly about adding features from new versions of SF and revamping the docs.

**Comment by olberger** [comment]
@simplyniceweb would you mind editing the issue's title to be more specific like "Silex vs Flex" or whatever ?

**Comment by fabpot** [comment]
As I said in the tweet, the big plan is more about better docs. But if nobody steps up, I think Silex won't have a bright future. Some people told me they would help, so we will see.

**Comment by srsbiz** [comment]
https://twitter.com/Crell/status/931071445488295936

:(
