### ISSUE TITLE
Error on Login

### ISSUE THREAD

**Issue by Falseee** [silexphp/Silex#1500]
Hello,

i registered the SecurityServiceProvider like this :

```php
$app->register(new Silex\Provider\SecurityServiceProvider(), array(
    'security.firewalls' => array(
        'admin' => array(
            'pattern' => '^/',
            'anonymous' => true,
            'form' => [
                'login_path' => '/login',
                'check_path' => '/login_check',
                'failure_path' => '/login/failure'
            ],
            'logout' => [
                'logout_path' => '/logout',
                'invalidate_session' => true
            ],
            'users' => function () use ($app) {
                return new UserRepository($app['orm.em'], $app['security.default_encoder']);
            },
        ),
    ),
    'security.role_hierarchy' => UserRole::getStructure()
));
```

If i try to login i get this error:

Uncaught TypeError: Argument 4 passed to Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken::__construct() must be of the type array, string given, called in /var/www/ts3admin/vendor/symfony/security/Core/Authentication/Provider/UserAuthenticationProvider.php on line 96 and defined in /var/www/ts3admin/vendor/symfony/security/Core/Authentication/Token/UsernamePasswordToken.php:36\nStack trace:\n#0 /var/www/ts3admin/vendor/symfony/security/Core/Authentication/Provider/UserAuthenticationProvider.php(96): Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken->__construct(Object(TS3Admin\\Entity\\User\\User), 'test123', 'admin', 'ROLE_ADMIN')\n#1 /var/www/ts3admin/vendor/symfony/security/Core/Authentication/AuthenticationProviderManager.php(80): Symfony\\Component\\Security\\Core\\Authentication\\Provider\\UserAuthenticationProvider->authenticate(Object(Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken))\n#2 /var/www/ts3admin/vendor/symfony/security/Http/Fi in /var/www/ts3admin/vendor/symfony/security/Core/Authentication/Token/UsernamePasswordToken.php on line 36, referer: https://ts3admin.domain.com/login

Where is the Problem ?

**Comment by xabbuh** [comment]
Does the `getRoles()` method of your `User` class return an array of roles or does it simply return the string `ROLE_ADMIN`?

**Comment by Falseee** [comment]
`abstract class UserRole
{
	const ROLE_ADMIN                = 'ROLE_ADMIN';
	const ROLE_USER                 = 'ROLE_USER';
    const ROLE_AUTHENTICATED_FULLY  = 'IS_AUTHENTICATED_FULLY';

	/**
	 * Return the role structure
	 *
	 * @return array
	 */
	public static function getStructure()
	{
		return array(
			self::ROLE_ADMIN => array(
				self::ROLE_USER
			)
		);

	}

	/**
	 * Returns all roles
	 *
	 * @return array
	 */
	public static function getRoles()
	{
		return array(
			self::ROLE_ADMIN,
			self::ROLE_USER
		);
	}
}
`

**Comment by Falseee** [comment]
@xabbuh can you help me ?

**Comment by xabbuh** [comment]
@Falseee Please show the code of your user class then. The code you showed in your previous comment is not your user class.

**Comment by Falseee** [comment]
@xabbuh i dont use the Userclass for the role management (show post two).
I use "security.role_hierarchy => UserRole::getStructure()".

**Comment by xabbuh** [comment]
That code is only about the configuration of the role hierarchy and is not related to how the token will be populated based on the user object.

**Comment by Falseee** [comment]
@xabbuh ah danke, die getRoles Function hat kein string wiedergegeben..
Ist aber neu in Silex2 oder ? (In Silex (1) gibt es so ohne Probleme :D )
