### ISSUE TITLE
$app['db']->getSchemaManager(); broken?

### ISSUE THREAD

**Issue by Suven** [silexphp/Silex#1504]
Hi,

I am trying to setup my db-schema. For that I am trying to receive my schema like that:

```php
$app['db']->getSchemaManager();
$myFancyTable = new Table('fancyTable');
....
$schema->createTable($myFancyTable);
```

However, this throws a

```php
ClassNotFoundException in DoctrineServiceProvider.php line 90:
Attempted to load class "Configuration" from namespace "Doctrine\DBAL".
Did you forget a "use" statement for another namespace?
```

Your `Provider/DoctrineServiceProvider.php` does however have a `Doctrine\DBAL\Configuration`.

How can I get around this?

I am setting up my db like 

```php
$app->register(new Silex\Provider\DoctrineServiceProvider(), array(
    'db.options' => [
        'dbname' => $_ENV['DB_NAME'],
        'host' => $_ENV['DB_HOST'],
        'user' => $_ENV['DB_USER'],
        'password' => $_ENV['DB_PASS']
    ],
));
```

I'm using silex v2.0.4

**Comment by xabbuh** [comment]
You need to make sure to install the `doctrine/dbal` package if you want to use the `DoctrineServiceProvider`.

**Comment by Suven** [comment]
Ahh thanks a bunch! That was my problem. 

As the docs did not mention it, I was under the impression that the dbal always ships with silex.

**Comment by SpacePossum** [comment]
>As the docs did not mention it

https://silex.sensiolabs.org/doc/1.3/providers/doctrine.html

```
Doctrine DBAL comes with the "fat" Silex archive but not with the regular one. If you are using Composer, add it as a dependency:

composer require "doctrine/dbal:~2.2"
```

or are you maybe referring other docs?

**Comment by Suven** [comment]
No, you are completly right. I don't know how I could have missed that. Thanks for your help
