### ISSUE TITLE
Public website down ?

### ISSUE THREAD

**Issue by olberger** [silexphp/Silex#1507]
There seems to be a lot of 503 errors on https://silex.sensiolabs.org/

Anyone able to do something ?

**Comment by olberger** [comment]
In the meantime, the docs seem to be available from http://silex.readthedocs.io/ (even if not comprehensive, at least for human readble than the RST from docs/)

**Comment by fabpot** [comment]
@olberger Sorry about that, it was probably a small glitch as everything looks good on my side. Is it up for you now?

**Comment by magnetik** [comment]
Still 503 here.

**Comment by magnetik** [comment]
Aaaaaand now it's OK ...

**Comment by olberger** [comment]
@fabpot nope : still  Error 503 Backend error on https://silex.sensiolabs.org/ ... is it round robin ?
(from behind my freebox near Paris ;)

**Comment by fabpot** [comment]
Ok, after some more investigation, it was "only" for some users. We fixed it now, sorry for the inconvenience.

**Comment by Schenn** [comment]
Getting 504s now
