### ISSUE TITLE
phpunit

### ISSUE THREAD

**Issue by lukaszgoworko** [silexphp/Silex#1513]
Just installed skeleton.

Running php 7.1 and added phpunit 6.1

Get this error on starting unittest

```
Fatal error: Class 'PHPUnit_Framework_TestCase' not found in /var/www/html/vendor/silex/silex/src/Silex/WebTestCase.php on line 22
```

**Comment by stof** [comment]
The Silex WebTestCase is not yet compatible with PHPUnit 6

**Comment by lukaszgoworko** [comment]
will it be enough to use new namespaces in WebTestCase, or will it brake backward compatibility?

**Comment by skalpa** [comment]
Silex can't require PHPUnit 6 I'm afraid, however you may be able to solve your problem by using a class alias:

```php
if (!class_exists('PHPUnit_Framework_TestCase') && class_exists('PHPUnit\Framework\TestCase')) {
    class_alias('PHPUnit\Framework\TestCase', 'PHPUnit_Framework_TestCase');
}

class MyTest extends WebTestCase
{
}

```

(Note: I haven't tested, but it's worth a try)

**Comment by stof** [comment]
The new namespaced class is available in PHPUnit 4.3.35 and in PHPunit 5.4+. So using the namespaced class for the TestCase will *not* make it require PHPUnit 6

**Comment by skalpa** [comment]
Yep, I didn't know it had been backported to 4.8 and just learnt that after reading symfony/symfony#21534. 

I'll make a PR that fixes the tests.

**Comment by fabpot** [comment]
fixed
