### ISSUE TITLE
Symfony/cache service provider ?

### ISSUE THREAD

**Issue by skalpa** [silexphp/Silex#1516]
I started playing with a `symfony/cache` service provider and was wondering if that was worth finishing.

My idea is to provide a pre-configured set of caches similar to the ones we have in the framework:

- `cache.system` created with `AbstractAdapter::createSystemCache()`
- `cache.app` using Redis / Memcache / Filesystem (depending on what's available/configured)

Tell me if you thing that would be worth finishing / if you'd prefer something more feature rich / if 
you don't think it would be a good idea to add a cache provider at all, and I'll try and finish
whenever I got time.

**Comment by fabpot** [comment]
That's a great topic. I think it would makes sense to add support for symfony/cache in Silex.

**Comment by fabpot** [comment]
Closing as Silex is not maintained anymore, so we won't add new features to it.
