### ISSUE TITLE
Planned future Symfony version support?

### ISSUE THREAD

**Issue by jordanlev** [silexphp/Silex#1527]
Is there a plan to support the next Symfony LTS release (3.4) when it comes out at the end of the year? Right now it looks like Symfony 2.8 and 3.1 are supported by Sliex, and I'm trying to decide which version of Symfony I should use. If I can count on Symfony 3.4 support close to when it's released, then I'll go with 3.1 in the meantime (since it would be an easier upgrade). Otherwise, I'd stick with Symfony 2.8 since it will be supported longer (so the upgrade might be more difficult but at least I'd be on a supported version for longer).

Thanks!

**Comment by flip111** [comment]
I'm also wondering when symfony 4 comes out that breaks backwards compatibility that it will need a new version of silex (silex 3)

**Comment by skalpa** [comment]
Silex is tested/supported with all the branches of the Symfony components from `2.8` to `3.4.x-dev`. Should you encounter an issue, you are free to report it, ideally with a PR that solves the problem. Just make sure you describe your issue precisely, with an example that allows somebody else to reproduce it as there's little chance somebody will be able to help if you just say "version x.y doesn't work".

As for Symfony 4: Silex 2.x is regularly updated to ensure it doesn't use any of the deprecated features of the Symfony 3.x components (i.e: the ones that will get removed in Symfony 4.0). That means that Silex 2, at least in theory, should be able to work with Symfony 4.0 once it gets released (I haven't actually used this in production but at the time of writing all the tests pass with `4.0.x-dev`).

Now, I personally believe it would make sense to release a next major version of Silex that would require Symfony 4.x around the end of the year as this would provide an opportunity to clean up some service providers, but again that won't probably be _needed_, so it might not happen.

**Comment by fabpot** [comment]
Full support for Symfony 3.4 is done... which means that Symfony 4.0 is also supported for the implemented features by Silex.
