### ISSUE TITLE
Remove isset in SecurityServiceProvider to prevent dependency on ValidatorServiceProvider?

### ISSUE THREAD

**Issue by jnvsor** [silexphp/Silex#1531]
In the [SecurityServiceProvider](https://github.com/silexphp/Silex/blob/6f539e087f1178cfce6579eb7a080c4fa3805f38/src/Silex/Provider/SecurityServiceProvider.php#L661) there's an `if` statement that requires the `validator` to exist.

As long as that if is there registering validator after security will cause a nice fat fatal error when using the `UserPassword` constraint, and I can't imagine it's there for performance reasons.

Is that if even neccesary?

**Comment by MatTheCat** [comment]
`isset` doesn't register anything.

**Comment by jnvsor** [comment]
It registers `security.validator.user_password_validator` and adds to `validator.validator_service_ids` - without those `ValidatorServiceProvider` will fatal out

**Comment by HeahDude** [comment]
Hello @jnvsor,

I think what @MatTheCat means is that calling `isset` at this point prevents returning true without initializing the validator.

>I can't imagine it's there for performance reasons.

Indeed it allows to register the constraint only if the `ValidatorServiceProvider` has registered the `validator` service.

Did you actually encounter any bug? If not I think we can close here.

**Comment by jnvsor** [comment]
If forcing providers to be registered in a certain order isn't considered a bug then feel free to close it, I suppose.

**Comment by MatTheCat** [comment]
It doesn't force anything so you can close your issue.

**Comment by jnvsor** [comment]
@MatTheCat It does if you want to use `UserPassword`, unless you consider a fatal error an option I suppose...

**Comment by hkdobrev** [comment]
> If forcing providers to be registered in a certain order isn't considered a bug then feel free to close it, I suppose.

I'm not saying requiring service providers in a certain order is nice and good, but it is quite common in Silex.

Just take a look at `TwigServiceProvider` code. It requires the form provider, http fragment provider and others to be registered for all features.

**Comment by MatTheCat** [comment]
@jnvsor my mistake indeed `ValidatorServiceProvider` must be registered before `SecurityServiceProvider` in order to use the `UserPassword` constraint.

@hkdobrev order does not matter inside `TwigServiceProvider` because service are checked **when `twig` is requested** so it happens after all services are registered.

@fabpot could `UserPasswordValidator` be added in the `boot` method?

**Comment by jnvsor** [comment]
> could UserPasswordValidator be added in the boot method?

What's the downside of just removing the if? Are `validator.validator_service_ids` or `security.validator.user_password_validator` needed for anything besides `UserPassword`?

**Comment by jnvsor** [comment]
@fabpot Doesn't that fix mean an exception if someone tries to set `security.validator.user_password_validator` before `firewall` is instantiated?

**Comment by fabpot** [comment]
@jnvsor No, that would just do nothing as it will be overridden by the default service (like today).
