### ISSUE TITLE
In development env warnings occur in error logs

### ISSUE THREAD

**Issue by validweb** [silexphp/Silex#1535]
Hi,

I have noticed that when using this code in a dev env I get a warning  in the error log with every call to the middlewarelistener:

** I am not responsible for the silex stuff in my team, but found this quick fix, so thought I'd let you know, I have very little knowledge of this, so please disregard if not appropriate.
 
 PHP Warning:  call_user_func() expects parameter 1 to be a valid callback, no array or string given in /xxxxxx/xxxxx/xxxxx/xxx/common/vendor/silex/silex/src/Silex/EventListener/MiddlewareListener.php on line 54

I have fixed this locally as follows:

/**
     * Runs before filters.
     *
     * @param GetResponseEvent $event The event to handle
     */
    public function onKernelRequest(GetResponseEvent $event)
    {
        $request = $event->getRequest();
        $routeName = $request->attributes->get('_route');
        if (!$route = $this->app['routes']->get($routeName)) {
            return;
        }

        foreach ((array) $route->getOption('_before_middlewares') as $callback) {
            if (function_exists($this->app['callback_resolver']->resolveCallback($callback))) {
                $ret = call_user_func($this->app['callback_resolver']->resolveCallback($callback), $request, $this->app);
                if ($ret instanceof Response) {
                    $event->setResponse($ret);

                    return;
                } elseif (null !== $ret) {
                    throw new \RuntimeException(sprintf('A before middleware for route "%s" returned an invalid response value. Must return null or an instance of Response.', $routeName));
                }
            }
        }
        return;
    }

Hope this helps

**Comment by MatTheCat** [comment]
Please do not "fix" anything by hiding errors resulting from your code.

The error message tells you you called `Route`'s `before` function with something that can't be used by `call_user_func`. Fix *that* instead.

You can close your issue as this has nothing to do with Silex.
