### ISSUE TITLE
Silex and Turkish Lang. support

### ISSUE THREAD

**Issue by BerkhanBerkdemir** [silexphp/Silex#1537]
If I fetch data on MongoDB.
$que is array

> $app->json($que);

\u0130lan No = İlan No
\u0130lan Tarihi = İlan Tarihi
\u0130lan Ad\u0131 = Kullanıcı Adı

Output: 
> [{"_id":{"$oid":"596c12ce734d1d0ff25fdbef"},"\u0130lan No":"456785456","\u0130lan Tarihi":"27 Haziran 2017","\u0130lan Ad\u0131":"Terlik"}]

What should I do?

**Comment by SpacePossum** [comment]
Make sure the data returned by MongoDB can be json encoded in UTF-8.
If it is already encode; do not use `$app->json($que)`.
Return the already encoded data in a response object like 
`return new JsonResponse($que, $statusCode, $headers, true)`  the last one is a flag to not re-encode.

If you need other json encoding options set check the `JsonResponse` object how that can be done.

**Comment by fabpot** [comment]
Be sure to read https://en.wikipedia.org/wiki/Dotted_and_dotless_I as well.
