### ISSUE TITLE
Email Type Field - validation with some flaws

### ISSUE THREAD

**Issue by andreboscatto** [silexphp/Silex#1541]
When using an Email Type Field (`EmailType::class`), the standard REGEX used `preg_match('/^.+\@\S+\.\S+$/', $value)` is accepting some emails that are not valid, like:
- @@gmail.com
- someemail@.com.br

We fixed that on our project creating a callback function to validate the field using the following REGEX:
`'/^[+_a-z0-9-]+(\.[+_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,3})$/'`

Before submitting a patch, I would like to know if there is a reason for that standard REGEX be like this or if we could proceed and submit a patch with the new REGEX to fix this flaw.

Kindly

**Comment by MatTheCat** [comment]
This has nothing to do with Silex, but remember there is no regex which can validate emails since two softwares won't validate emails the same way. As such, Better have false positive than false negative.

**Comment by andreboscatto** [comment]
Thank you for your inputs Mat, I got your point and I really appreciate it.

From a different perspective, if I were relying 100% on this validation and not having a service validation (lucky mine I had one and got the error) with a third party I would totally let it pass through, maybe this is harmless on a first sight, but it is still wrong.

What I mean is, what is the point of including an extra validation all the time if I already have a standard one that is not trustable? Did you get my point?

Kindly

**Comment by MatTheCat** [comment]
I think you didn't understand. Your regex is wrong and the validation used by your third-party service is wrong too. What you want is to match this service validation with yours, which doesn't make it right. Plus your regex produces false negative so I think you'll understand it cannot be used by the `EmailValidator`.

**Comment by andreboscatto** [comment]
Got it, I went to the RFC and understood clearly what you are explaining, thank you.
