### ISSUE TITLE
Twig Provider: suggestion to make strict_variables true by default

### ISSUE THREAD

**Issue by codedokode** [silexphp/Silex#1542]
Currently in the Twig Provider an option `strict_variables` is set to `$app['debug']` by default ( https://github.com/silexphp/Silex-Providers/blob/master/TwigServiceProvider.php#L59 ). I think a better idea would be to set it to `true` by default (or at least leave it with Twig's default value which I hope will be changed to `true` soon).

I have created an issue in a Twig repo to suggest that they change it to `true` too: twigphp/Twig#2537

Motivation:

- make templates behave more like PHP code that reports undefined variables by default
- make it easier to discover errors in templates when a developer mistyped of forgot to specify a variable. The earlier the defect is discovered, the cheaper it is to fix.

I don't think that there should be any difference here (in handling undefined variables) in production and dev environment. It only makes discovering errors more difficult, it can cause user to see some invalid page instead of error page. Or even worse, search engine can index that invalid page (and if an exception were thrown, it would see 503 page instead).

c2 Wiki recommends to discover errors as early as possible: http://wiki.c2.com/?DiscoverDefectsEarly

Therefore I suggest: 

- do not use `debug` option as a default value for `strict_variables`
- change the default value to `true`

If this change is approved I can make a pull request and update the docs if necessary.

**Comment by BenExile** [comment]
By default, undefined variables in PHP will generate a notice, allowing script execution to continue. Similarly Twig allows templates to be rendered even when they reference undefined template variables. I think it's more appropriate to set this value in your config explicitly if you don't want to rely on `$app['debug']`, and write [functional tests](https://silex.symfony.com/doc/2.0/testing.html#webtestcase) that inspect the rendered pages, making sure they contain the content you expect.

**Comment by fabpot** [comment]
I'm closing this issue as Symfony has just adopted the same default value.
