### ISSUE TITLE
Make use of the Symfony microkernel

### ISSUE THREAD

**Issue by Hikariii** [silexphp/Silex#1545]
De http-kernel functionaliteit is wat veranderd.
De huidige implementatie kan simpeler.
https://symfony.com/blog/new-in-symfony-2-8-symfony-as-a-microframework

**Comment by stof** [comment]
@Hikariii next time, please write your comment in English so that maintainers can understand it.

**Comment by Hikariii** [comment]
@stof my mistake, wrong repo
