### ISSUE TITLE
Can't generate URL in Silex 2.2

### ISSUE THREAD

**Issue by tienv2i** [silexphp/Silex#1547]
I am new in Silex. I use twig-brigde in my project but I can not use url('homepage') or path('homepage')  in my twig template and  $app['url_generator']->generate("homepage")  in my code , I got the Exception:
> Unable to generate a URL for the named route "homepage" as such route does not exist.

When I test with $app->path or $app->url I got the Exception:

> Call to undefined method Silex\Application::path() in ......

This is my router file:

```
use Silex\Application;

$app->get('/homepage',function(Application $app){

    return $app['twig']->render('home.twig.php',['name' => 'Testing']);
});

$app->get('/',function(Application $app){
    $app['url_generator']->generate("homepage");
    return $app['twig']->render('home.twig.php',['name' => 'MyName']);
});
```
This is my composer.json
```
{
    "require": {
        "silex/silex": "^2.2",
        "twig/twig": "^1.34",
        "symfony/twig-bridge": "^3.3"
    },
    "autoload":
    {
        "psr-4":{
            "":"src/"
        }
    }
}
```

**Comment by stof** [comment]
well, there is no route named `homepage` in yoru code snippet, as you haven't named your routes.

```php
use Silex\Application;

$app->get('/homepage',function(Application $app){

    return $app['twig']->render('home.twig.php',['name' => 'Testing']);
})->bind('homepage');
```

**Comment by stof** [comment]
`->path()` and `url()` don't exist in the Application class. There is a trait available to allow you to use them in your project by creating a class extending Application and applying the trait in it.
