### ISSUE TITLE
Can't retreive matched context.

### ISSUE THREAD

**Issue by n-for-all** [silexphp/Silex#1553]
i need to be able to retrieve the matched firewall, is it possible you allow overriding FirewallMap? or any other solution to get the matched firewall?

https://github.com/silexphp/Silex/blob/f9eadbcd1836d7c72d30e140459d79f0fa8c7165/src/Silex/Provider/SecurityServiceProvider.php#L305

**Comment by fabpot** [comment]
This is more related to Symfony than Silex. IIRC, it's possible to do so in recent versions of Symfony.

**Comment by n-for-all** [comment]
https://github.com/symfony/security-bundle/blob/8ed71f5152ae5d9816ae75d9bfd301a707dbc6a6/Security/FirewallMap.php

 getFirewallConfig is added only to the symfony security bundle, the firewall component doesn't have such function.

https://github.com/symfony/security/search?utf8=%E2%9C%93&q=getFirewallConfig&type=

Is there a way to get the firewall config?
