### ISSUE TITLE
Predefined namespaces?

### ISSUE THREAD

**Issue by MichalVales91** [silexphp/Silex#1554]
Hello!

I created my own little custom validator and assigned it to its little den at `$app['validator']` where it's being called from many places in my code. Yup, your web claimed I can use any variables/namespaces I want! (And I didn't know about the existence of _Validator_. And even I do now, I'm totally allright with my own!) Why is it problem?

After some time of development, I "composed" _Security Service_. Then the scary hell-oops appeared, just on the line 666 of the _SecurityServiceProvider.php_.

Why is there check `if (isset($app['validator']))` but `if (isset($app['validator.validator_service_ids']))` not? For me - who did not compose validator and only uses this namespace - it's really a hell because _UnknownIdentifierException: Identifier "validator.validator_service_ids" is not defined_ freaks me out.

Well, yeah, I know why and how to solve this, but maybe... Maybe this is much bigger issue: why does some service presume existence of any other just by its most probable location? Going further: why does some service presume existence of any other at all?

IMHO there should be absolute granularity and user should handle all these interoperative thing himself/herself.

If it's higher issue and I should write this to _Symfony_ devels, tell me and I'll do. If you think this is just an offtopic complaining, I'm sorry in advance.

Thank you

MV91

**Comment by stof** [comment]
Well, as Pimple does not have a concept of tags like Symfony DIC does (which is logical, as Pimple does not have a compilation phase), registering an extension of the ValidatorServiceProvider when the SecurityServiceProvider is also registered (to provide the support for the valdiation constraint checking the current password) requires to extend the service from the other provider directly.
Forcing the end-user to register all these inter-provider features manually would mean that things become painful for anyone using the builtin providers together, which is not a good developer experience.

The issue here comes from the fact that you defined  a`validator` service which is not the builtin one, and the detection logic does not work well for this case (as it assumed that this means that the builtin service provider was used).

**Comment by MichalVales91** [comment]
@stof Of course I do understand these arguments, I also know my issue, but that's exactly what I'm saying... Problem is that [official documentation](https://silex.symfony.com/doc/2.0/services.html#parameters) says _the array key can be any value_, which is technically **not true!** You can't tell developers _"do anything you want"_ and after weeks of their work add _"but don't do this, because there is some feature"_.

There should be done one of these:
- mentioned reserved words for namespaces,
- reserve one namespace `system` or `app` and dot-append all builtin services into it,
- check existence of _ValidatorServiceProvider_ by any other method than namespace.

**Comment by stof** [comment]
well, the only thing we can use to detect whether the ValidatorServiceProvider was applied is to check for its effect (i.e. checking for defined services), as this is the only effect of applying it.

Adding a namespace to all builtin services (i.e. naming them as `system.validator`) would make things harder to use for all people using them, as they would have to use a longer name. Thus, it cannot be done easily, as this would be a huge BC break (as all projects would have to change the ids they use).

**Comment by MichalVales91** [comment]
@stof What about some internal property of each internal service? Maybe checking `if (isset($app['validator.service_id']) && $app['validator.service_id'] === "somerandomhashforvalidatorservice")`? There should not only be chech if some service exist, but also if it is **the** prebuilt service you suppose. Do you know what I mean?

I get it, yeah, moving all builtin services would be pain, but in Silex2 maybe? Longer name is not an issue at all.

**Comment by fabpot** [comment]
Indeed, some service names are "reserved". Nothing we can do IMHO. That's a fundamental "limitation" of Silex that cannot be changed.
