### ISSUE TITLE
Translation Provider needs to be made compatible with Symfony 4

### ISSUE THREAD

**Issue by flip111** [silexphp/Silex#1560]
https://github.com/symfony/symfony/pull/24176#issuecomment-338959715

constructor is now type hinted for `$formatter`

**Comment by agilare** [comment]
As announced officially in this [Symfony blog post](http://symfony.com/blog/the-end-of-silex), it will not be done : 

> For all these reasons, I would say that Silex is not needed anymore. So, we've decided to not support Symfony 4 in Silex, or at least not add the new features added in 3.4. The current stable version of Silex is still maintained for bugs and security issues. But its end of life is set to June 2018.

**Comment by flip111** [comment]
This issue should stay open as backlog to upgrading silex to symfony 4 components which is dependent on https://github.com/silexphp/Silex/issues/1593

**Comment by fabpot** [comment]
Closing as the code now takes this into account.
