### ISSUE TITLE
mount

### ISSUE THREAD

**Issue by nimasdj** [silexphp/Silex#1561]
I tried codes here: https://silex.symfony.com/doc/2.0/organizing_controllers.html#organizing-controllers
and I am getting
Error 0: The "mount" method takes either a "ControllerCollection" or a "ControllerProviderInterface" instance.

Please advise.
I tried http://www.mydomain.com/app.php/admin, /blog, /forum etc. the same error. If the parameter must be controller class, the documentation is inaccurate?

**Comment by xabbuh** [comment]
Can you show your actual code?

**Comment by nimasdj** [comment]
I just copy/paste from the doc and got that error, what wrong I did?

```
$app = new Silex\Application();

// define controllers for a blog
$blog = $app['controllers_factory'];
$blog->get('/', function () {
    return 'Blog home page';
});
// ...

// define controllers for a forum
$forum = $app['controllers_factory'];
$forum->get('/', function () {
    return 'Forum home page';
});

// define "global" controllers
$app->get('/', function () {
    return 'Main home page';
});

$app->mount('/blog', $blog);
$app->mount('/forum', $forum);

// define controllers for a admin
$app->mount('/admin', function ($admin) {
    // recursively mount
    $admin->mount('/blog', function ($user) {
        $user->get('/', function () {
            return 'Admin Blog home page';
        });
    });
});

$app->run();

```
