### ISSUE TITLE
Pass class:method to router

### ISSUE THREAD

**Issue by nimasdj** [silexphp/Silex#1563]
Is it possible to have something like:
`$app->get('/', '\HomeController:home');`
instead of closure function? If yes, I have not found such info in documentations, please give link or hint or sample code.

**Comment by srsbiz** [comment]
https://silex.symfony.com/doc/2.0/usage.html#controllers-as-classes

**Comment by nimasdj** [comment]
Thanks. As mentioned on docs, Silex doesn't support ORM. but here https://silex.symfony.com/doc/2.0/usage.html#route-variable-converters it seems orm is available in class. Is there any tricky way to have entity manager in controller classes?
@srsbiz

**Comment by srsbiz** [comment]
Silex does not come with ORM, but you can use one as ServiceProvider https://github.com/silexphp/Silex/wiki/Third-Party-ServiceProviders-for-Silex-2.x#database

Most service providers registers itself inside `$app`, so if you make your controller to accept `Silex\Application`  as one of the arguments, you can access its services:

```
$app->get('/', 'Acme\\Foo::bar');

use Silex\Application;
use Symfony\Component\HttpFoundation\Request;

namespace Acme
{
    class Foo
    {
        public function bar(Request $request, Application $app)
        {
            // for https://github.com/dflydev/dflydev-doctrine-orm-service-provider
            $em = $app['orm.em']; 
        }
    }
}
```

**Comment by nimasdj** [comment]
Thanks for all kind helps. It works now.
May I ask please kindly help for this too? https://github.com/silexphp/Silex/issues/1562#issuecomment-341503361 I see no cookie. What is wrong in my code?

**Comment by nimasdj** [comment]
With your help, I am almost getting it. Any help about this one too please?
https://stackoverflow.com/questions/47127830/how-to-get-redirected-to-correct-page-with-silex

@srsbiz

**Comment by nimasdj** [comment]
When I use bind() like 
`$controllers->get('/', 'Controllers\\Login::index')->bind('login');
`I get "No route found for "GET /login":" but without bind() it works fine. What is wrong?

**Comment by stof** [comment]
well, this route is using `/` as URL, not `/login`

**Comment by nimasdj** [comment]
Thanks, bind() naming must be unique for each post and get? I mean
$controllers->get('/login', 'Controllers\\Login::index')->bind('login');
$controllers->post('/login', 'Controllers\\Login::index')->bind('login');
Is something invalid to use the same name for post and get?
@stof

**Comment by stof** [comment]
Yes it does. The argument given to `bind()` is the route name. Reusing the same name would replace the route definition.

**Comment by nimasdj** [comment]
@stof If I have like /login/{id} then what should be the second parameter of path() as I get 
exception ("Some mandatory parameters are missing ("id") to generate a URL for route "login"."). ?

**Comment by fabpot** [comment]
Closing as support should probably be done in StackOverflow instead of here. Thanks.
