### ISSUE TITLE
A probable doc typo?

### ISSUE THREAD

**Issue by nimasdj** [silexphp/Silex#1564]
I use this code:

```
<?php

namespace Routers;

use Silex\Application;
use Silex\Api\ControllerProviderInterface;
use Silex\Provider\FormServiceProvider;

class Index implements ControllerProviderInterface
{
    public function connect(Application $app)
    {
        // creates a new controller based on the default route
        $controllers = $app['controllers_factory'];

        $controllers->get('/', function (Application $app) {

        $app->register(new FormServiceProvider());

        $task = new Task();
        $task->setTask('Write a blog post');
        $task->setDueDate(new \DateTime('tomorrow'));

        $form = $app['form.factory']->createFormBuilder($task)
            ->add('task', TextType::class)
            // If you use PHP 5.3 or 5.4 you must use
            // ->add('task', 'Symfony\Component\Form\Extension\Core\Type\TextType')
            ->add('dueDate', DateType::class)
            ->add('save', SubmitType::class, array('label' => 'Create Task'))
            ->getForm();

            return $app->render('index.html', array(
                   'form' => $form->createView(),
          ));

        });

        return $controllers;
    }
}
```
and I get error: 
Call to undefined method Symfony\Component\Form\FormFactory::createFormBuilder()

I looked at source code and noticed there is no createFormBuilder() method. Is the doc outdated?
Anyway, how can I fix my code?

**Comment by hkdobrev** [comment]
@nimasdj In your code, you should use `$app['form.factory']->createBuilder()`. However, you should pass a class representing your Form there, not the actual entity. I looked up [the `FormServiceProvider` docs in Silex](https://silex.symfony.com/doc/2.0/providers/form.html) and they are actually correct.

Also, see the [Form component documentation](https://symfony.com/doc/3.4/components/form.html).

Support requests like that should go to StackOverflow. Could you please close this issue? Thanks!

**Comment by fabpot** [comment]
Closing then.
