### ISSUE TITLE
Tes failure with PHP 7.2

### ISSUE THREAD

**Issue by remicollet** [silexphp/Silex#1566]
From Fedora QA
https://apps.fedoraproject.org/koschei/groups/php?order_by=state%2C-started&collection=f28

Reproduced with master
```
There was 1 error:

1) Silex\Tests\Provider\SessionServiceProviderTest::testRegister
ini_set(): Headers already sent. You cannot change the session module's ini settings at this time

/tmp/Silex/vendor/symfony/phpunit-bridge/DeprecationErrorHandler.php:105
/tmp/Silex/vendor/symfony/http-foundation/Session/Storage/Handler/NativeFileSessionHandler.php:52
/tmp/Silex/src/Silex/Provider/SessionServiceProvider.php:49
/tmp/Silex/vendor/pimple/pimple/src/Pimple/Container.php:118
/tmp/Silex/src/Silex/Provider/SessionServiceProvider.php:55
/tmp/Silex/vendor/pimple/pimple/src/Pimple/Container.php:118
/tmp/Silex/tests/Silex/Tests/Provider/SessionServiceProviderTest.php:33
```

**Comment by lracicot** [comment]
I still have the same issue with `http-foundation`
```
name     : symfony/http-foundation
versions : * v3.4.3
``` 

Whenever I run phpunit, I get: 
```
ini_set(): Headers already sent. You cannot change the session module\'s ini settings at this time', '~/project/app/vendor/symfony/http-foundation/Session/Storage/Handler/NativeFileSessionHandler.php (line 52)
```

**Comment by GBeushausen** [comment]
What can we do to make the tests work with 7.2? I'm not quite sure what the status is. The code in #1567 seems to be doing the trick. Why was the PR canceled?

**Comment by SpacePossum** [comment]
IIRC I tried to do to much at the same time in one PR ;)
Dropping the CS, SCA and modernize changes leaves the main issue:
finding a way to run the test suit on PHP5.3 up to and including PHP7.2, given the changes done within PHPUnit there is not always an easy path. TBH I stopped working on the PR as around that time Silex was reported to become EOL. IMHO best/easiest way would be start again with a clean up to date PR.

**Comment by GBeushausen** [comment]
@SpacePossum thanks. I'll try to work on that. From what i see this issue is one of the main show stoppers to the further development of Silex.

From what i see the error in the 7.2 Tests is triggered [here](https://github.com/silexphp/Silex/blob/5e032d0790118b66c1d7f4345c2d3d926d69780d/tests/Silex/Tests/Provider/SessionServiceProviderTest.php#L33) 

Does anyone have a clue why this variable $defaultStorage is initialized, but never used?

But anyway it's definatly a good solution do modernize the whole test suit.

**Comment by fabpot** [comment]
see #1598 where I've tweaked Travis's configuration (description tells more about what I've done -- this is just a first step).

**Comment by fabpot** [comment]
Tests now pass on PHP 7.2 (see #1600 which removes something that is not needed anyway as the tests do not use the native session handler, but the test one).

**Comment by GBeushausen** [comment]
@fabpot Great. Thank you very much.
