### ISSUE TITLE
[Form] [CSRF] Translation domain not set properly for CsrfExtension

### ISSUE THREAD

**Issue by eschultz-magix** [silexphp/Silex#1569]
The ```FormServiceProvider``` registers the ```form.extension.csrf``` service as an instance of ```Symfony\Component\Form\Extension\Csrf\CsrfExtension``` class that takes the ```translation_domain``` as third parameter.

The translation domain is passed to ```CsrfValidationListener``` and it used directly for translation. By default, validation errors are registered with the ```validators``` domain (see ```ValidatorServiceProvider```), but the translator has a fallback to the ```messages``` domain, so CSRF errors cannot get translated properly.

**TL;DR** The ```FormServiceProvider``` should check whether the ```ValidatorServiceProvider``` has been registered and use its translation domain as third parameter for the ```CsrfExtension```, null otherwise to allow correct translations of CSRF form errors.

**Comment by hkdobrev** [comment]
@eschultz-magix Could you please check out #1608? Thanks!
