### ISSUE TITLE
Unexpected behaivior: mount does not return ControllerCollection

### ISSUE THREAD

**Issue by MaPePeR** [silexphp/Silex#1572]
I tried to setup a simple 'user'-Service that has a `redirectIfNotLoggedIn(Request $request, Application $app)` function.
In my main file i registered this using `$app->mount('...)->before("user:redirectIfNotLoggedIn")`.
At first i thought it was working like i intended it to, but then i noticed, that it is executing the before-function for every route and not just the routes that match the `mount`.

Is there a way i can fix this? What is causing this? This behaivior was not really documented, so i was lucky to find out it at least somewhat does what i intended it to do, but i might be using it totally wrong?

Edit: Actually the same thing happens when i use `"Namespace\ClassName::function_name"` as the Argument.

**Comment by MaPePeR** [comment]
It seems like i was under the wrong assumption that `$app->mount()` returns the created `ControllerCollection`, but apparently it just returns `$app` again and I assume that this is something that is not going to change ever to preserve backwards compatibility. Am i right about that?

**Comment by fabpot** [comment]
Yes, you're right.

**Comment by MaPePeR** [comment]
Thats kind of sad, because i think it would be a very logical way to do it.

For example: If i define a mount-point with an argument like `$app->mount('/x/{a}/b, ...)` i would want to specify the validation of that argument where i define the route and not in the mountpoint itself. (I would  consider this the more logical place for such definitions)

I think `ControllerCollection` does not have a return value for `->mount`, so i still have some hope left.

I personally would make the usage of the return value of the `Application->mount` function deprecated, so this behaivior could be changed in a future version. (How to deprecate the return value, though? Return an object that redirects everything to the `Application`-Object, but generate a warning for every or the first call/access?)

But that's not up for me to decide. I would be happy if you could give it some thought, though.
