### ISSUE TITLE
Missing official statement regarding the EOL of Silex

### ISSUE THREAD

**Issue by xmarcos** [silexphp/Silex#1578]
Apparently, @fabpot announced at SymfonyCon's keynote that Silex will come to and EOL in June 2018, yet there is no **official** announcement on any of the sites (Silex, Symfony, Fabien's blog, etc).

![eol-slide](https://user-images.githubusercontent.com/58319/33533734-cb4cc48a-d881-11e7-9a7a-3605a3375241.png)

I think it would appropriate to show a warning for new users and offer a [migration path](https://github.com/symfony/symfony-docs/issues/8678)/advice for existing ones. A post explaining the reasoning behind the decision would be nice too.

Thanks!

**Comment by lukaszwit** [comment]
In my opinion the reason of EOL is obvious -> symfony flex (micro by default). 
But big warning on main pages should appear ASAP (maybe some ugly flaming marquee like we did in '90s ;))

**Comment by agilare** [comment]
The answer yesterday on Symfony blog : https://symfony.com/blog/the-end-of-silex

**Comment by derrabus** [comment]
From my point of view, that blog post and ad7cf125376bc01bdcfb0b375fe65b3973c32664 fix the issue.

**Comment by xmarcos** [comment]
@derrabus thanks for the heads up, that would do.
