### ISSUE TITLE
TwigRenderer deprecated since symfony 3.4

### ISSUE THREAD

**Issue by gpmaccari** [silexphp/Silex#1579]
Since Symfony version 3.4, TwigRenderer is deprecated. 
TwigServiceProvider needs to be updated in order to use FormRenderer, as suggested by the Symfony 3.4 changelog.

**Comment by quazardous** [comment]
same here

workaround: as pointed out by @jlayt have extended the `twig.runtimes` key:

```php
use Symfony\Component\Form\FormRenderer;
...
        $app->extend('twig.runtimes', function ($runtimes, $app) {
            return array_merge($runtimes, [
                FormRenderer::class => 'twig.form.renderer',
            ]);
        });
...

```

**Comment by macintoshplus** [comment]
@quazardous This solution not works for me. Where should we place it?

**Comment by gsirin** [comment]
@macintoshplus 

make sure to add  `use Symfony\Component\Form\FormRenderer;` at the top as well

**Comment by agilare** [comment]
Will TwigServiceProvider be corrected soon ?
