### ISSUE TITLE
When twig.path is an array the key is expected to be the path and the value the namespace, why?

### ISSUE THREAD

**Issue by InfopactMLoos** [silexphp/Silex#1585]
I stumbled upon a change which broke my code when converting my code from Silex 1 to 2. As can be read in the TwigServiceProvider#160 the key of the array value for config twig.path is used as the path and the value as the namespace.

https://github.com/silexphp/Silex/blob/014ac54ab286c5eb157732ea4a36bfc542dbcca5/src/Silex/Provider/TwigServiceProvider.php#L160

 It seems the namespace was never set in the old code (silex 1) but it seems more logical to me to use the key as namespace and the value as the path, but of course this might just be me. Anyone able to elaborate on this choice?

**Comment by srsbiz** [comment]
See https://github.com/silexphp/Silex/pull/1576#discussion_r153008892

**Comment by InfopactMLoos** [comment]
Ah so it was done to allow for assigning multiple paths to the same namespace. Ok thanks for answering so quickly!
