### ISSUE TITLE
New Module Integration

### ISSUE THREAD

**Issue by rameshmrm** [silexphp/Silex#1587]
silex with Symfony framework how to add new module to the existing project.

 Now I developed binary MLM project I am purchased in codester.com website, I need to add new module my project.

**Comment by stof** [comment]
there is no concept called `module` in Silex, so I don't understand what you are asking for.

**Comment by davidasrocha** [comment]
Hi, @rameshmrm 

What is `module` concept?
Do you need to add MLM code project to your Silex Application?

If this is, then you can create the Provider to integrate code with Silex Application.

You can see this use in [Providers](https://silex.symfony.com/doc/2.0/providers.html).

**Comment by fabpot** [comment]
Closing as there is no feedback anymore and Silex does not have modules anyway.
