### ISSUE TITLE
"Welcome!" page with $app['debug'] = true

### ISSUE THREAD

**Issue by ProgMiner** [silexphp/Silex#1591]
Is it right, "Welcome!" page opens with `$app['debug'] = true`?
I think in `RoutingServiceProvider` file in `RouterListener` must be also a `$app['debug']` parameter.
Sorry if it isn't.

https://github.com/silexphp/Silex/blob/e970d12a5b5a203fbd859525ce406b22e73f9f61/src/Silex/Provider/RoutingServiceProvider.php#L79

**Comment by flip111** [comment]
> I think in RoutingServiceProvider file in RouterListener must be also a $app['debug'] parameter.

why do you think so? can you be more specific here ?

**Comment by ProgMiner** [comment]
Because a Welcome page [contains](https://github.com/symfony/symfony/blob/b0facfec018093fb9ad65658f654ab7af06f6f87/src/Symfony/Component/HttpKernel/Resources/welcome.html.php#L79) that:
```
<div id="comment">
    <p>
        You're seeing this message because you have debug mode enabled and you haven't configured any URLs.
    </p>
</div>
```

**Comment by flip111** [comment]
What does that piece of html have to do with the RoutingServiceProvider ?

**Comment by ProgMiner** [comment]
Maybe I don't understand something, but I think this is obviously.
A `RouterListener` from the Symfony must sends Welcome page **only** when application in debug-mode.
Possibly I mistaked by sending a quote from HTML source. It's [from](https://github.com/symfony/symfony/blob/b0facfec018093fb9ad65658f654ab7af06f6f87/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php#L133) `RouterListener`:
```
} catch (ResourceNotFoundException $e) {
    if ($this->debug && $e instanceof NoConfigurationException) {
        $event->setResponse($this->createWelcomeResponse());

        return;
    }

    $message = sprintf('No route found for "%s %s"', $request->getMethod(), $request->getPathInfo());

    if ($referer = $request->headers->get('referer')) {
        $message .= sprintf(' (from "%s")', $referer);
    }

    throw new NotFoundHttpException($message, $e);
}
```

**Comment by flip111** [comment]
Hello, the RouterListener you linked is from 13th of januari as part of symfony 4.1 development branch (master). Silex matches http-kernel 2.8 or 3.* https://github.com/silexphp/Silex/blob/ec7d5b5334465414952d4b2e935e73bd085dbbbb/composer.json#L22

The code you point out is [also present](https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php#L131-L136) in version 3.4 of http-kernel (but not in 3.3)

Silex was never updated to work on 3.4 components. But that might happen depending on this issue https://github.com/silexphp/Silex/issues/1593

I recommend to keep this issue open as backlog what needs to be done for upgrading components. You can send in a PR .. it will be an easy one i think.
