### ISSUE TITLE
Make Silex-Providers a separate project

### ISSUE THREAD

**Issue by jnvsor** [silexphp/Silex#1592]
Since pimple is going to continue to exist (silexphp/pimple#243) can we turn the [Silex-Providers](https://github.com/silexphp/Silex-Providers) subtree-split into a full separate project?

**Comment by flip111** [comment]
If that happens it should be renamed to pimple-providers imo. What dependencies are there on silex itself actually?? If there are dependencies it can not be a standalone project without requiring silex .. which is a bit weird imo.

**Comment by jnvsor** [comment]
@flip111 It doesn't have any. It was moved to a separate packages ages ago - it's already available as the [silex/providers](https://packagist.org/packages/silex/providers) composer package. All it needs is issues turned on, the automatic subtree split turned off, and a description change and it's ready to go.

**Comment by hkdobrev** [comment]
The silex providers require `silex/api` as a dependency as some providers require more interfaces like the `BootableProviderInterface`. However, in order to be a separate project `silex/silex` package should remove them from the source and require `silex/providers` as a dependency. Later this package could be renamed.

**Comment by jnvsor** [comment]
@hkdobrev Oh, my bad!

**Comment by hkdobrev** [comment]
I'm happy to do the pull requests for that, but I'll wait for some of the maintainers to chime in, as a I definitely see why they did it like that. Pimple is usable without the providers, but you really need them for Silex to make it what it is and many of them are designed to be a part of Silex.

**Comment by jnvsor** [comment]
Yeah, now that I think about it making silex-api a separate one too would probably be the easiest way

**Comment by fabpot** [comment]
I'm closing this one as those 2 repositories are subtree-split of the main repository. If someone wants to maintain those, they should really be maintained as part of Silex.
