### ISSUE TITLE
Update silex.symfony.com about Silex end of life

### ISSUE THREAD

**Issue by agilare** [silexphp/Silex#1597]
A month after the [Symfony blog post announcing the end of Silex](http://symfony.com/blog/the-end-of-silex), the [homepage of the framework](https://silex.symfony.com/) is still unchanged.

It would be useful to put a warning like in [Silex README](https://github.com/silexphp/Silex/blob/master/README.rst).

**Comment by GBeushausen** [comment]
Please include the updated message as stated in #1593

**Comment by fabpot** [comment]
I'm closing this one for now as I'm quite confident someone will take over.
