### ISSUE TITLE
#silex-php on freenode

### ISSUE THREAD

**Issue by hkdobrev** [silexphp/Silex#1626]
[The Community section in the readme](https://github.com/silexphp/Silex#community) mentions the `#silex-php` channel on `irc.freenode.net` as the place to discuss Silex. However, it seems it's not active for years.

Should we:
- [x] remove it from the readme?
- [x] mention StackOverflow?
- [ ] suggest Reddit?
- [x] suggest using issues on the repository?

**Comment by fabpot** [comment]
Indeed, it should be removed. I would mention StackOverflow instead for questions and Github for issues.

**Comment by hkdobrev** [comment]
👌 I'll submit a PR. I've updated the tag wiki on StackOverflow. Awaiting peer review there.
