### ISSUE TITLE
Rebuild your code

### ISSUE THREAD

**Issue by giacomoniccoli** [silexphp/Silex#1635]
Hi,
i have to move a client website made by another agency to a new server. I moved the files and the DB but when i ask for the index.php the answer is "Rebuild your code". What's the problem? How can i rebuild it? Is the first time i look at silex and simfony so if you can give me some tips on how to get that website back online i'll be grateful.

Thanks a lot.
Giacomo

**Comment by stof** [comment]
I'm not aware of any place in Silex having a message saying `Rebuild your code`. So this looks like a project-specific thing.

**Comment by fabpot** [comment]
Closing as support should be done on StackOverflow. But indeed, it does not seem to come from Silex/Symfony anyway.
