### ISSUE TITLE
Middleware handlers with controller-like argument-resolving

### ISSUE THREAD

**Issue by MaPePeR** [silexphp/Silex#1637]
Because i always get the order of the `Request` and `Application`-Arguments in my `->before` handlers wrong and i see myself writing a lot of `$request->attributes->get('...')` in these handlers i think it would be great if we could use the same functionality, that is used to determine the controller arguments for these middleware handlers. (Because it extends the functionality it wouldn't even be a BC-break!)

I *think* one only would need to use something like [this](https://github.com/symfony/symfony/blob/e6302e2c920fc9c282389998dd30127bd1d48ad5/src/Symfony/Component/HttpKernel/HttpKernel.php#L140-L149) in the  [MiddlewareListener](https://github.com/silexphp/Silex/blob/dab325972d23bd1dd533fd86d4349672b1ec3224/src/Silex/EventListener/MiddlewareListener.php#L54):

```php
//untested (from the top of my head)
foreach ((array) $route->getOption('_before_middlewares') as $callback) {
    $c = $this->app['callback_resolver']->resolveCallback($callback);
    $arguments = $this->app['argument_resolver']->getArguments($request, $c);
    $ret = \call_user_func_array($c, $arguments);
    //[...]
}
```

What do you think?

**Comment by fabpot** [comment]
Closing as Silex is not maintained anymore.
