### ISSUE TITLE
[docs] Cookbook

### ISSUE THREAD

**Issue by igorw** [silexphp/Silex#64]
It would be great to have a cookbook with some recipes.

* Authentication (and Users)
* File upload
* Matching full paths ([discussion](http://groups.google.com/group/silex-php/browse_thread/thread/e9582b46a0266b73))
* AJAX requests in WebTestCase ([discussion](http://groups.google.com/group/silex-php/browse_thread/thread/f02c71305acf5d67))
* overriding services
* integrating libraries / Symfony2 bundles

Please suggest more.

**Comment by dominikzogg** [comment]
http://silex.sensiolabs.org/doc/cookbook/index.html

**Comment by fabpot** [comment]
Closing this old issue.
