### ISSUE TITLE
FallbackResource fails for root level routing.

### ISSUE THREAD

**Issue by danielyule** [silexphp/Silex#703]
In the documentation on the Webserver Configuration page, the it is suggested to use FallbackResource as an alternative to the mod_rewrite rules.  This works for most pages, but for requests to '/', when '/' is a defined route, the webserver is unable to return appropriate data.  On Chrome, it gives an encoding error.  Debugging shows the response is being generated, but no browser is able to receive it.

Switching back to mod_rewrite fixed the problem completely.

**Comment by fabpot** [comment]
Closing this as there is nothing we can do, except perhaps added more info in the docs. I will let someone do that as I haven't used Apache for years.
