### ISSUE TITLE
Session invalidate does not work (session not started automatically)

### ISSUE THREAD

**Issue by peschee** [silexphp/Silex#746]
Hi

I recently discovered what seems to be a bug in the latest silex version. It seems that sessions cannot be invalidated with ```$app['session']->invalidate()``` without an explicit ```$app['session']->start()``` in e.g. the ```before``` middleware.

It seems that sessions should be started automatically upon initial access (#274). I've created a quick sample app to demonstrate the problem ([https://github.com/peschee/silex-session-bug](https://github.com/peschee/silex-session-bug)) which has the following structure:

```php
<?php

require __DIR__ . '/../vendor/autoload.php';

use Silex\Application;
use Silex\Provider\SessionServiceProvider;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

define('SESSION_KEY', 'some_key');

$app = new Application();

$app->register(new SessionServiceProvider());

$app->before(function (Request $request) use ($app) {
//    $app['session']->start();
});

$app->get('/', function () use ($app) {
    return sprintf('Main<br /><br />Session: %s', $app['session']->get(SESSION_KEY));
});

$app->get('/set', function () use ($app) {
    $app['session']->set(SESSION_KEY, 'some_value');

    return sprintf('Set<br /><br />Session: %s', $app['session']->get(SESSION_KEY));
});

$app->get('/invalidate', function () use ($app) {
    $app['session']->invalidate();

    return sprintf('Set<br /><br />Session: %s', $app['session']->get(SESSION_KEY));
});

$app->run();
```

The ```/set``` route correctly sets the session value. However, if I visis ```/``` after having invalidated the session in ```/invalidate```, the stored session value is still there. Adding ```$app['session']->start()``` in the before middleware solves the problem.

Is this expected behavior? If so, we need to change the docs accordingly.

**Comment by fabpot** [comment]
Closing as there is a ticket on symfony/symfony about this problem.
