### ISSUE TITLE
SecurityServiceProvider pre_auth missing _proxy

### ISSUE THREAD

**Issue by Virakal** [silexphp/Silex#950]
I apologise if I am missing something, but I'm running into problems trying to use `pre_auth` security. The code "works" (it runs but doesn't do what I need it to) with `anonymous` and `http`, but `pre_auth` gives me the following exception:

> InvalidArgumentException: Identifier "security.authentication_listener.pre_auth._proto" is not defined. in /vagrant/public/silex/vendor/pimple/pimple/lib/Pimple.php on line 78

but I can't find any documentation of _proto.

My bootstrap code is:
```php
$app->register(new Provider\SecurityServiceProvider(), array(
	'security.firewalls' => array(
		'cp' => array(
			'pattern' => '^/cp/',
			'pre_auth' => true,
			'users' => $this->share(function () {
				return new CP\UserProvider();
			}),
		),
	),
));
```

**Comment by polarbearhandler** [comment]
@kwisatz Any chance to do this PR in the near future? :)

**Comment by kwisatz** [comment]
@alaczi Unfortunately, I haven't received any feedback on my questions above. I don't think a PR would make sense with those issues unresolved. I'm also really busy these days, so near future, as in this WE or this week seems rather unlikely. I'll make a note though to remind me of looking back into this whenever I need a break from some other stuff.

**Comment by alaczi** [comment]
@kwisatz Thanks, I will also take a look on it. I solve it in a hacky way in our projects but it would be better to use in a proper way.

**Comment by ragboyjr** [comment]
Can we close this then?

**Comment by fabpot** [comment]
Doesn't the new Guard support in Silex 2.0 fixes this issue?

**Comment by Virakal** [comment]
I no longer have access to the project from the original issue, but it seems as though Guard would simplify things and pre_auth is no longer documented (was it ever? I may have just imagined it at the time :) ) so if the official solution to "something else has already authenticated me before I ever got to Silex but I want to use the security components anyway" is to write your own custom Guard auth system, I think that's a good enough reason to close the issue, personally.
