### ISSUE TITLE
Calling $app->abort() in a middleware returns 500

### ISSUE THREAD

**Issue by robomc** [silexphp/Silex#951]
This is consistent with the documentation for middlewares, once you know that ->abort doesn't return a Response object.

But I feel like it's not the behaviour people will expect. The description for abort() says 'Aborts the current request by sending a proper HTTP error.', which kind of implies a response object, and it behaves much like returning a response in normal routes.

Not a bug, but I think should consider allowing "return $app->abort(403, 'No session!');" type syntax in middlewares, as it seems consistent and intuitive.

**Comment by mgurov** [comment]
Is the issue still reproducible? Following code works OK for me on `dev-master e12be31` and `1.3.x-dev 244dbef` : 

```php
$app = new Silex\Application();

$rejectWith403 = function($request, $app) {
    $app->abort(403, 'You shall not pass');
};

$app->get('/hello/{name}', function ($name) use ($app) {
    return 'Hello '.$app->escape($name);
})->before($rejectWith403);

//would also work
//$app->before($rejectWith403);

$app->run();
```

**Comment by mironoff111** [comment]
I don't want to use Doctrine or etc. So, how to return 500 error page in this case?
`//PDO
try {
    $DBH = new PDO($PartCCTV_ini['db']['dsn'], $PartCCTV_ini['db']['user'], $PartCCTV_ini['db']['password']);
}
catch(PDOException $e) {
    $app->abort(500, 'Ошибка соединения с БД : '.$e->getMessage());            
} `
