### ISSUE TITLE
Fix Testing Documentation

### ISSUE THREAD

**Issue by bradberger** [silexphp/Silex#974]
Not sure if this is the right place for this, so sorry in advance if it's not.

It's not clear from the docs that using one's own `setUp()` method will break everything as explained in the [testing docs](http://silex.sensiolabs.org/doc/testing.html#webtestcase), and as this is quite common to PHPUnit usage, that might cause issues - I know it did for me.

Obviously, as you already know, simply doing this works:

    public function setUp() {
        parent::setUp();
        // Do some more setup here....
    }

But the issue is that this isn't documented too well. I had to look through the source to figure out why nothing was working.

There is also no documentation that indicates what the `/path/to/app.php` file should look like, so it takes some trial and error to figure out that it end with:

    return $app;

Of course, chance are I simply don't understand the process, but in any case that, too, would indicate that the docs could use a bit more explanation.

Thanks for the awesome software!

**Comment by fabpot** [comment]
6f559e4
