### ISSUE TITLE
[DOC] $app['some_service'] a new instance of the service is created

### ISSUE THREAD

**Issue by liuggio** [silexphp/Silex#982]
at:
https://github.com/silexphp/Silex/blob/master/doc/services.rst#service-definitions

`Every time you call $app['some_service'], a new instance of the service is created.`

Using the new version of Pimple  this is true using factory method.

*References*:
- http://pimple.sensiolabs.org/#defining-factory-services

**Comment by petrgrishin** [comment]
:+1:
