### ISSUE TITLE
LocalServiceProvider not needed for TranslationServiceProvider

### ISSUE THREAD

**Issue by freepius** [silexphp/Silex#987]
At https://github.com/silexphp/Silex/blob/master/src/Silex/Provider/TranslationServiceProvider.php#L32 , it's said that LocalServiceProvider is mandatory to use TranslationServiceProvider.

But in fact, no ! TranslationServiceProvider only needs that $app['locale'] is defined.

Do not insert some unneeded dependencies.

**Comment by fabpot** [comment]
Closing this old issue as the code has been updated since then.
